- packages/roosterjs-editor-api/lib/format/toggleBullet.ts
- packages/roosterjs-editor-api/lib/format/toggleNumbering.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- sample/sample.htm
- sample/scripts/sample.ts
1. Toggle bullet/numbering for empty line may put cursor in incorrect position in Edge, fix it by adding a space before toggle, and remove it after toggle.
2. Add a function in Editor class to allow suspending undo snapshot.
3. Add git and wiki link to sample site.
> Fix bullet bug

- packages/roosterjs-editor-api/lib/format/createLink.ts
- packages/roosterjs-editor-api/lib/linkMatch/defaultLinkMatchRules.ts
- packages/roosterjs-editor-api/lib/linkMatch/matchLink.ts
- packages/roosterjs-editor-api/lib/test/linkMatch/defaultLinkMatchRulesTests.ts
- packages/roosterjs-editor-api/lib/test/linkMatch/matchLinkTests.ts
- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
- tslint.json
Use ExtractContentEvent to extract hyperlink content, avoid using mouseover/mouseout event in plugin.
Make LinkMatchOption parameter optional.
> Hyperlink plugin use ExtractContentEvent

- package.json
- packages/roosterjs-editor-api/lib/format/removeLink.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-dom/lib/test/utils/convertInlineCssTests.ts
- packages/roosterjs-editor-dom/lib/utils/convertInlineCss.ts
- packages/roosterjs-editor-plugins/lib/PasteManager/PasteManager.ts
- packages/roosterjs-editor-types/lib/editor/ContentPosition.ts
Fix several bugs
1. Fix the tag check in Editor class to allow creating editor in a different window
2. When paste text, insert the whole pasted node first then unwrap, to improve perf a little.
3. Persist cursor position when remove link
4. Paste, insert the hidden div right after editor to keep cursor not run out to far, allow each editor instance has its own hidden div
5. convertInlineCss, use get/setAttribute instead of cssText to persist non-standard css texts.
> RoosterJs 6.3.1

- package.json
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-dom/lib/test/utils/fromHtmlTest.ts
- packages/roosterjs-editor-dom/lib/utils/fromHtml.ts
- packages/roosterjs-editor-dom/lib/utils/wrap.ts
- packages/roosterjs-editor-dom/lib/utils/wrapAll.ts
- packages/roosterjs-editor-plugins/lib/PasteManager/PasteManager.ts
For popouts, one cannot call document.createElement and expect it to be able to be adopted to the child window's document. For IE & Edge, those have to be created inside the ownerDocument of the child window.
> prevent fromHtml from accessing document directly

- package.json
- packages/roosterjs-editor-api/lib/format/clearFormat.ts
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-dom/lib/utils/applyFormat.ts
- packages/roosterjs-editor-types/lib/editor/DefaultFormat.ts
1. Fix clear format behavior for IE and Edge
2. Fix Indent command to remove top and bottom margin.
> Rooster 6.3.4

- packages/roosterjs-editor-core/lib/undo/Undo.ts
We should add undo snapshot add the beginning when delete something, even if selection range is collapsed. And we also need to set hasNewContent to true when delete, so that after delete if undo, we will take one more snapshot then undo to the previous one before deleting.
> Fix cursor position issue after undo

- package.json
- packages/roosterjs-editor-api/lib/format/insertImage.ts
- packages/roosterjs-editor-api/lib/format/insertTable.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-api/lib/test/format/clearFormatTest.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/editor/EditorOptions.ts
- packages/roosterjs-editor-core/lib/undo/Undo.ts
- packages/roosterjs-editor-core/lib/utils/insertNode.ts
- packages/roosterjs-editor-dom/lib/utils/convertInlineCss.ts
- packages/roosterjs-editor-plugins/lib/PasteManager/PasteManager.ts
- packages/roosterjs-editor-plugins/lib/PasteManager/wordConverter/convertPastedContentFromWord.ts
- sample/sample.htm
- sample/scripts/initFormatBar.ts
1. Add API: insertTable
2. Add API: insertImage, change pasteManager to use this API
3. Add an editor option param "doNotRestoreSelectionOnFocus", when set it to true, editor will not restore selection when focus
4. Fix a code bug in undo: we should allow empty undo snapshot ( #23 )
5. Fix insertNode API to allow insert a HTML fragment
6. Fix pasteManager to use HtmlDocumentFragment to have a better performance
7. Allow passing in extra Css Style node to convertInlineCss API
8. Add buttons for insertTable and insertImage in sample page
> RoosterJs 6.4.0: Add APIs, some other fixes

- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/editor/EditorOptions.ts
Added omitContentEditableAttributeChanges editor option for scenarios that will handle adding and removing those attributes directly. This will allow those scenarios to better control reflows.
> Added omitContentEditableAttributeChanges editor option

- package.json
- packages/roosterjs-editor-api/lib/format/clearFormat.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
- sample/sample.htm
- sample/scripts/initOptions.ts
- sample/scripts/updateSampleCode.ts
- webpack.config.js
Also set bold, italic, and underline if it's in the default format, when clearing format.
> Allow empty default format

- package.json
- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
Fixed HyperLink plugin's TEMP_TITLE_REGEX where after replace anchor tag has an extra space (i.e. &lt;a href="..." &gt;foo&lt;/a&gt;). This creates dirty content when getContent is called.
> Fixed HyperLink plugin's TEMP_TITLE_REGEX

- packages/roosterjs-editor-dom/lib/inlineElements/resolveInlineElement.ts
We should always use the node we are checking to build inline element
> Fix bug in resolveInlineElement

- package.json
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
Once remove node by Backspace key in PickerPlugin, always put cursor after the replaced node.
> 6.14.9 Fix cursor position issue in PickerPlugin

- packages/roosterjs-editor-dom/lib/selection/Position.ts
There was a build break introduced by #100 where the Browser import was not removed. This fixes the issue.
> Fixes build break

- packages/roosterjs-editor-api/lib/format/processList.ts
- packages/roosterjs-editor-dom/lib/selection/Position.ts
- packages/roosterjs-editor-dom/lib/test/utils/matchLinkTests.ts
- packages/roosterjs-editor-dom/lib/utils/matchLink.ts
The existing url regex is super permissable as to what is considered a
domain slug (e.g. any non-whitespace characters were considered
domains).
This work updates the regex to be compliant with the ietf domain name
spec, and removes erroneous test cases that were testing for invalid
regexes.
Note that this will also mean that _Invalid urls with valid punycode
encodings will no longer work_. Is this an acceptable tradeoff?
> Tighten url regex

- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
When you type a whitespace character after an @, that usually means that you'd like to not search anything.
We could possibly expand this to all non-whitespace characters.... but I think this is valid all the same.
> Dismiss the picker when you type a whitespace after the trigger symbol.

- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
.which is deprecated, we should use .key instead, so this change will do that.
Open question: Does this break in IE / Edge which have spotty support for .key?
> Switch from .which to .key

- package.json
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
In the change for 6.16, we added functionality to dismiss the picker when the only text in the query string would be whitespace. However, empty query strings are a special case, so, we should do an additional check to ensure that the wordBeforeCursor isn't the trigger character, capturing this case.
> Update the query string when just the cursor character is present.

- package.json
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/shortcutFeatures.ts
In Edge, AltGr (right ALT in some languages, like Polski) key sets both e.altKey and e.ctrlKey to true. We need to check e.altKey not to be true before treat them as CTRL+* shortcut.
> Fix issue 118

- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
- packages/roosterjs-plugin-image-resize/lib/ImageResize.ts
I rewrote HyperLink plugin to change the way of implementing hyperlink title. The new approach doesn't need to add temporary attribute into A tag, so copy/paste won't have other side effect.
> Rewrite Hyperlink plugin, fix #131

- packages/roosterjs-editor-core/lib/editor/CorePlugin.ts
Fixes an issue where typing normalization did not run on ctrl+a -> typing 
The bug is because normalization runs before the keypress, and only on an empty div.
so
- have text content
- ctrl+a to select all
- press a button that would type text
- text format normalization does not run because you have text
- browser CED behaviour puts the text into a div at the root level of the document
- text is not formatted.
See #189 for tests.
> fix ctrl+a -> typing issue

- packages/roosterjs-plugin-picker/lib/PickerDataProvider.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
This makes it so Undo happens when hitting Backspace. The emoji is re-autocompleted after because the KeyUp event triggers queryStringUpdated - so this should be fixed in another PR.
Code Changes
1. Add `handleAutoComplete` flag to PickerPluginOptions
2. When defined, use `performAutoComplete` instead of `addUndoSnapshot `
Deploy Link: https://outlook-sdf.office.com/mail/?branch=DESKTOP-ONVDVE4-u-titrongt-testRoosterJs
> [PickerPlugin] Use performAutoComplete when flagged in PickerPluginOptions

- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
Currently, PickerPlugin's insertNode callback does nothing when the wordToReplace is empty 
In order for the ExpressionPane in client-web to use this callback, it needs to be able to insert nodes even when there is no text to replace
> Insert node on empty wordToReplace in PickerPlugin

- package.json
- packages/roosterjs-editor-api/lib/utils/processList.ts
- packages/roosterjs/package.json
1. Fix #209 Start a number list which has text with background color at beginning of the line, causes the background color fill the whole line
2. Add a new plugin CustomReplace
3. Fix issue when insert node on empty wordToReplace in PickerPlugin
4. Fix a missing package dependency
> 7.1.0 Fix #209

- package.json
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-plugins/lib/Paste/Paste.ts
- packages/roosterjs-editor-types/lib/interface/DarkModeOptions.ts
1. Move the dark mode transform logic to be post insertion of the node. This means we can use getComputedStyles if desired in the future to compute dark mode transformations, which is necessary for proper and accessible color normalization.
2. Add a parameter to set content to declare you want the content inserted to be transformed for dark mode.
3. Add a parameter to DarkModeOptions to be used when initializing to transform the content when inserted.
> Modify Dark Mode transform order, and enable setContent to transform as well.

- package.json
- packages/roosterjs-editor-api/lib/format/replaceWithNode.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/autoLinkFeatures.ts
- packages/roosterjs-editor-plugins/lib/Paste/Paste.ts
- packages/roosterjs-editor-plugins/lib/Paste/textToHtml.ts
In an earlier change I fixed an issue when paste a link next to existing charactor, e.g.
Before paste: ()
After paste: (www.test.com)
And the fix allows do auto link to the pasted text. However, this won't trigger ContentChangedEvent with the new anchor element.
So the fix here is to defer this action after text is pasted, and go through the same code path of regular autolink.
> 7.1.2 Fix #218

- packages/roosterjs-plugin-picker/lib/PickerDataProvider.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
When we get a content changed event, and it's set content, we can assume that something drastic has changed about the state of the editor document. This is used for Undo for instance.
When we get one of these events, we can scan through the document and report any picker placed elements that still exist, and report it to the data provider. For instance, if the data provider is maintaining a list of elements for some reason (like if it needs to track how many are inserted for logging), they currently can't tell if elements are removed through that system. This adds a way for a DataProvider to be informed of the current element list's state after the change happens.
> Track content changed events and report up to PickerPluginDataProvider

- packages/roosterjs-editor-api/lib/format/replaceWithNode.ts
- packages/roosterjs-editor-core/lib/coreAPI/insertNode.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-types/lib/enum/ContentPosition.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/InsertOption.ts
- publish/samplesite/scripts/controls/sidePane/apiPlayground/insertContent/InsertContentPane.tsx
ReplaceWithNode currently manipulates the dom directly, when there exists an editor API for inserting nodes to begin with. If we extend the definition of the core API to allow for replacing an existing node (instead of relying on calculating what node to replace every time), we can use the editor API. This also will help us with dark mode, as replacing with node is a common operation, and centralizing dom manipulation calls helps us maintain good editor state.
> Refactor ReplaceWithNode to use the editor core API

- packages/roosterjs-editor-api/lib/format/replaceWithNode.ts
- packages/roosterjs-editor-core/lib/coreAPI/insertNode.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-types/lib/enum/ContentPosition.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/InsertOption.ts
- packages/roosterjs-plugin-picker/lib/PickerDataProvider.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
- publish/samplesite/scripts/controls/sidePane/apiPlayground/insertContent/InsertContentPane.tsx
I want to make a few more changes prior to 7.1.3 going out on the dark mode branch, so this PR is to separate out the merge of the current state of master so the resulting PRs can be clean.
> Merge in current master in preperation for additional changes prior to 7.1.3

- packages/roosterjs-editor-core/lib/coreAPI/select.ts
- packages/roosterjs-editor-types/package.json
- publish/samplesite/scripts/controls/ribbon/RibbonButton.tsx
- tools/build.js
1. Add "@types/dom-inputevent" to dependency of roosterjs-types package to avoid build error from other projects that take roosterjs as dependency  (package.json)
2. Remove "insertLicense" step from build script. I added this step in order to mark version number of a packed file, however this causes source map doesn't work. So let's remove it. (build.js)
3. In select.ts, we have a browser check and skip setting selection if browser is already selecting the same range. Currently we only do this for Edge, but we need to do this for all browser so that we won't deselect and reselect when focus to editor. This is the first step of fixing the state of B/I/U issue. (select.ts)
I also removed related workaround code in RibbonButton.tsx since we don't need them after this fix.  (RibbonButton.tsx) …
> Fix 4 issues

- .vscode/extensions.json
- package.json
I noticed the recommended tslint package was deprecated. Microsoft has it's own TSLint extension, so I replaced our current recommendation with the microsoft one.
> Replace deprecated TSLint extension with MSFT TSLint

- packages/roosterjs-editor-core/lib/editor/Editor.ts
When we call setContent, we get a reference to the core CED and set the content that way. However, when we do this, all we have left that's an HTML node is that root CED. We actually don't want to modify the CED, but we do want to modify the content coming into it. So, we add a parameter to the dark mode transform function to skip that root element, meaning the only thing that gets transformed is the actual editor content itself.
> Skip the root element when setContent is called w/ dark mode transform.

- packages/roosterjs-editor-core/lib/coreAPI/attachDomEvent.ts
For printable key inputs (a-z, 0-9, ...), call stopPropagation() to avoid the event being handled by parent container in order to improve perf.
> stopPropagation for key inputs

- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
Today in PickerPlugin the dataProvider is always in DataProvider type. But when we use it we usually have a derived interface. And if we need to get the data provider from picker plugin we need to do type casting.
So in this change I make PickerPlugin to have type parameter of data provider, and set default value to PickerDataProvider for compatibility.
> Make picker plugin generic

- package.json
- packages/roosterjs-editor-core/lib/coreAPI/attachDomEvent.ts
In my previous check in I added stopPropagation() for keyboard event. But this should only be added for text input key event. Event such as ALT+, CTRL+, META+ should still be propagated.
> Fix keyboard event issue

- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
Allow Hyperlink onLinkClick to fall back to default handling to reduce redundant code.
> Improved Hyperlink plugin onLinkClick option

- packages/roosterjs-editor-core/lib/editor/Editor.ts
Instead of looking at the editor options object, we should instead base off of if inDarkMode is set to true. This allows an editor to be provided dark mode options, but be in non-dark mode, at least to start.
> Set content should base itself off of inDarkMode

- packages/roosterjs-editor-plugins/lib/ContentEdit/features/autoLinkFeatures.ts
Bug: Enter key can't trigger auto link.
Reason: in my earlier change I removed the searcher object from autolink function.
But this is required since we need to get the searcher object before Enter key is accepted.
Fix: add back the searcher.
> fix autolink bug

- package.json
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/autoLinkFeatures.ts
- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
Merge in latest master changes.
> 7.2.5 darkmode.0

- package.json
I did a bad and ran yarn package, which has changed behavior recently and doesn't run our build script. So, 7.2.5-darkmode.0's name is spiked, so I'm bumping the name here. No other changes.
> 7.2.5-darkmode.1

- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
- packages/roosterjs-editor-core/lib/interfaces/EditorCore.ts
When we toggle dark mode, the default formatting can sometimes get re-applied by ensureTypeInElement. This requires us to re-set the default format based on the dark mode state. We can achieve this by exporting the calcDefaultFormat function from createEditorCore to do this calculation. Open to placing this somewhere else.
> Recalculate default format when dark mode toggles

- package.json
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/FormatState.ts
- tools/dts.js
1. Split Format state into 4 parts:
1.1 Pendable format  (B/I/U/Strikethrough/superscript/subscript)
1.2 Element based format (Bullet, numbering. quote, link, image, header)
1.3 Style based format (font name, font size, colors)
1.4 (deprecated) Editor managed state (canundo, canredo)
2. Add functions to get format state of 1.1, 1.2, 1.3, so that user only need to get subset of the format state when need. This is to save the call to getComputedStyles()
3. Don't call getComputedStyles() when initialize editor if default format already contains everything
4. Fix dts tool to support multiple extends
> Fix some perf issue and some other changes

- packages/roosterjs-editor-core/lib/coreAPI/attachDomEvent.ts
- packages/roosterjs-editor-core/lib/eventApi/isCharacterValue.ts
- packages/roosterjs-editor-core/lib/eventApi/isModifierKey.ts
- packages/roosterjs-editor-core/lib/index.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
We got feedback that the picker was not dismissing after hitting Backspace on the trigger character. 
This is because of the change I made removing the KeyPress event. Instead of checking the event onKeyPress, we were checking that the key isCharacterValue for the event onKeyUp. This included `event.key && event.key.length == 1`
Backspace was not passing this check, so it was not being registered and thus `queryStringUpdated` was never called. This check was originally in attachDomEvent, so I call it directly there and changed the function to be just the common code.
> [PickerPlugin] Modify check to register Backspace key onKeyUp

- package.json
- packages/roosterjs-editor-core/lib/coreAPI/attachDomEvent.ts
- packages/roosterjs-editor-core/lib/eventApi/isCharacterValue.ts
- packages/roosterjs-editor-core/lib/eventApi/isModifierKey.ts
- packages/roosterjs-editor-core/lib/index.ts
- packages/roosterjs-plugin-picker/lib/PickerDataProvider.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
A recent change makes onKeyUp handler will be called when functional keys like Backspace, ... are pressed. This causes isSuggesting is set to true even when it was not suggesting.
In this change, I make it check isCharacterValue as well:
isSuggesting && isCharacterValue => call onKeyUp
isSuggesting && !isCharacterValue && !isModifierKey => call onKeyUp
isSuggesting && isModifierKey => NOT call onKeyUp
!isSuggesting && isCharacterValue => call onKeyUp
!isSuggesting && !isCharacterValue && !isModifierKey => NOT call onKeyUp
!isSuggesting && isModifierKey => NOT call onKeyUp
> Fix an issue when call onKeyUp handler in PickerPlugin

- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
Adjust the order of how the plugins are added so that the PickerPlugin's `willHandleExclusively` takes precedence over EditPlugin. 
Deploy Link: https://outlook-sdf.office.com/mail/?branch=TISHAPC-u-titrongt-testTabShouldResolveAtMention
> [Bullets] Tab should resolve AtMention instead of indenting bullet

- packages/roosterjs-editor-dom/lib/selection/isPositionAtBeginningOf.ts
- packages/roosterjs-editor-dom/lib/test/selections/isPositionAtBeginningOfTest.ts
```html
<UL>
<LI><BR>
<CURSOR>test
</LI>
</UL>
```
When backspace, today the content edit feature "MergeInNewLine" will treat it as the beginning of a list item so it will add a BR tag back. Acutally since there is already a BR tag before the cursor, we should not treat it as at beginning of list.
> Fix cursor stuck at list issue

- packages/roosterjs-editor-core/lib/corePlugins/EditPlugin.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/editor/adjustBrowserBehavior.ts
- packages/roosterjs-editor-core/lib/editor/mapPluginEvents.ts
- packages/roosterjs-editor-core/lib/interfaces/ContentEditFeature.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/autoLinkFeatures.ts
- packages/roosterjs-editor-types/lib/browser/DocumentCommand.ts
The regression in 7.4.0 is caused by ContentEditFeature.initialize(). I realized this function can potentially break editor since when call it, EditPlugin.initialize() may not been called yet so EditPlugin.editor is null.
So I decide  to remove this method. And actually it is only used in one place -- AutoLinkPlugin, to run a command for IE. So I also move all initial "execCommand" call to a new function "adjustBrowserBeahvior"
Also move the event mapping part to a new file to make Editor.ts a little shorter.
> Remove initialize method from edit feature

- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-api/lib/utils/execCommand.ts
- packages/roosterjs-editor-core/lib/coreAPI/selectRange.ts
- packages/roosterjs-editor-core/lib/corePlugins/DOMEventPlugin.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/utils/getPendableFormatState.ts
- packages/roosterjs-editor-types/lib/event/PendingFormatStateChangedEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEventType.ts
- packages/roosterjs-editor-types/lib/index.ts
- publish/samplesite/scripts/controls/sidePane/eventViewer/EventViewPane.tsx
styles like bold, italic, underline, ... are pending style if selection is empty (collapsed), which means if selection is changed before user type something (apply the change), the pending style will be lost. This causes user can't set pending style at the same time with other formats like font and color since those styles needs open a picker which will cause editor loses focus.
The fix here is:
1. Add a new event "PendingFormatStateChangedEvent", and it is fired when user is change such styles
2. Handle the event in DomPlugin and cache current position and format
3. When editor got focused, or we call editor.select() to change selection, check if the selection is still the same with the cached one. If so, apply the cached format
> Support pending format management, fix #224, #313

- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/undo/Undo.ts
- packages/roosterjs-editor-plugins/lib/Paste/Paste.ts
I fixed dark mode undo so the undo buffer always has normalized content, and when inserted back into the editor, it is normalized appropriately.
> Fix for dark mode undo

- packages/roosterjs-editor-core/lib/editor/Editor.ts
When set initial content, we should not trigger ContentChangedEvent, otherwise plugin will think content is always changed on init, and it can break the "restore editor" scenario which allows bring back an editor with existing undo snapshots, a ContentChangedEvent will cause undo plugin clear all redo snapshots so that redo will be broken.
> do not trigger event when set initial content

- packages/roosterjs-editor-plugins/lib/Watermark/Watermark.ts
#270 Watermark plugin creates empty trailing div
This is caused by an empty DIV tag left in editoir after Watermark plugin remove the watermark DOM. The fix is to insert a BR tag into the empty DIV to make it a regular empty line.
> Fix #270 Watermark plugin creates empty trailing div

- packages/roosterjs-editor-api/lib/test/format/clearFormatTest.ts
- packages/roosterjs-editor-api/lib/test/format/createLinkTest.ts
- packages/roosterjs-editor-api/lib/test/format/toggleBoldTest.ts
- packages/roosterjs-editor-api/lib/test/format/toggleItalicTest.ts
- packages/roosterjs-editor-api/lib/test/format/toggleUnderlineTest.ts
- packages/roosterjs-editor-core/lib/test/coreApi/hasFocusTest.ts
- packages/roosterjs-editor-core/lib/test/editor/EditorTest.ts
- packages/roosterjs-editor-core/lib/undo/UndoSnapshots.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/snapshots/addSnapshot.ts
- packages/roosterjs-editor-dom/lib/snapshots/canMoveCurrentSnapshot.ts
- packages/roosterjs-editor-dom/lib/snapshots/clearProceedingSnapshots.ts
- packages/roosterjs-editor-dom/lib/snapshots/clearSnapshotsAfterCurrent.ts
- packages/roosterjs-editor-dom/lib/snapshots/createSnapshots.ts
- packages/roosterjs-editor-dom/lib/snapshots/moveCurrentSnapsnot.ts
- packages/roosterjs-editor-dom/lib/test/snapshots/addSnapshotTest.ts
- packages/roosterjs-editor-dom/lib/test/snapshots/canMoveCurrentSnapshotTest.ts
- packages/roosterjs-editor-dom/lib/test/snapshots/clearProceedingSnapshotsTest.ts
- packages/roosterjs-editor-dom/lib/test/snapshots/moveCurrentSnapsnotTest.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/Snapshots.ts
- publish/samplesite/scripts/controls/sidePane/snapshot/SnapshotPlugin.tsx
- publish/samplesite/scripts/controls/sidePane/snapshot/UndoSnapshots.ts
This is to move function implementations out of UndoSnapshot class so that developer can easily build their own UndoSnapshot and reuse our existing logic. This can help the OWA code clean up and be able to put undo snapshot on store so that the code can easily clear undo snapshots without knowing Undo plugin.
> Refactor UndoSnapshot

- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/utils/adjustNodeInsertPosition.ts
- packages/roosterjs-editor-dom/lib/utils/applyTextStyle.ts
- packages/roosterjs-editor-dom/lib/utils/splitTextNode.ts
#277 Insert <A> tag inside a [A] tag, should split outer [A] tag
The fix is to follow Chrome CED behavior:
- If the node to insert doesn't contain any [A] tag, no change.
- If the node to insert contains [A] tag, but there isn't any [A] tag around current insert position, no change
- If the node to insert contains [A] tag, and there is [A] tag around current position within current block, split the existing [A] tag into two and insert the new nodes between them.
#330 When replacing links using ctrl-v, link doesnt disappear
Before insert, let's check if there is an empty [A] tag around current insert position. If yes, remove it.
> Fix #277 and #330

- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
Outlook on Android has integrated the AtMentions plugin, but is missing some of the functionality we see on OWA. 
On Android, the code for the keyboard event is "Unidentified". which causes `isCharacterValue-->onKeyUp` and `onKeyDown `to fail. This makes it so the inline picker does not appear and backspace will not properly remove the AtMention node. This change works around this by looking at input events for Android.
https://outlook-sdf.office.com/mail?branch=titrongt-refs-heads-u-titrongt-testFixPickerPluginForMobile
> PickerPlugin for Android 

- packages/roosterjs-editor-core/lib/coreAPI/insertNode.ts
- packages/roosterjs-editor-core/lib/test/editor/EditorTest.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/SelectionBlockScoper.ts
- packages/roosterjs-editor-types/lib/enum/ContentPosition.ts
- packages/roosterjs-editor-types/lib/interface/InsertOption.ts
Fixing an issue with the `insertNode()` function, where if two elements are inserted with `ContentPosition.End` then the last one is inserted inside the last child instead of inside the container.
Added unit tests to demonstrate the issue, and fixed in `coreApi/insertNode.ts`
> Fix insertNode at end

- packages/roosterjs-editor-plugins/lib/Paste/wordConverter/convertPastedContentFromWord.ts
- packages/roosterjs-html-sanitizer/lib/test/getInheritableStylesTest.ts
Previously I added code to remove <o:p> tag for Word to make it work with bullet list. Now let's preserve it if its inner html is &nbsp;.
> Fix #355:  when paste from Word and empty lines are dropped

- packages/roosterjs-editor-plugins/lib/CustomReplace/CustomReplace.ts
Bug 57080: Backspace should not convert text back into emoji
In CustomReplace plugin, we should not perform the auto complete action if user input is "backspace".
So the fix is to check input event data should not be null
> Fix OWA 57080

- packages/roosterjs-editor-dom/lib/selection/Position.ts
In Position.normalize(), if the offset value is beyond a valid range, there will be exception. 
The fix is to check returned value of node, if it is null, stop and use the last good value.
> Fix exception in Position.normalize()

- README.md
THe block formatting for "Inline Element was a bit incorrect in the Repo readme file. Raising a Pull request to correct that.
> Fixing a Readme Issue containing incorrect formatting

- package.json
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-html-sanitizer/lib/test/getInheritableStylesTest.ts
Add new APIs:
1. Editor.getSelectionPath(), directly get a selection path from current editor selection
2. Editor.getEditorDomAttribute(), get DOM attribute value from editor DIV
Add new override:
1. Editor.select() supports selecting with a selection path.
> Add selectionPath related API

- package.json
- packages/roosterjs-editor-plugins/lib/Watermark/Watermark.ts
Watermark is working in an incorrect way. The first time evaluation is done too early before editor is fully initialized. So if there is some content like "[DIV][/DIV]" watermark will be replaced.
Fix this by delay the first evaluation to EditorReady event
> Fix a watermark bug

- packages/roosterjs-plugin-image-resize/lib/ImageResize.ts
Reproduce:
Set max-width or max-height to an image, and then drag it.
> Fix preserve ratio bug.

- package.json
- packages/roosterjs-editor-plugins/lib/Watermark/Watermark.ts
Watermark text is not generated by user, and it is possible to contain some special word which can't pass spell check. So We should disable spellcheck when watermark is shown.
> Disable spell check when watermark is shown

- .travis.yml
- package.json
- packages/roosterjs-editor-api/lib/format/createLink.ts
- packages/roosterjs-editor-api/lib/format/toggleHeader.ts
- packages/roosterjs-editor-core/lib/corePlugins/FirefoxTypeAfterLink.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
#349 ToggleHeader doesn't remove current font-size
Currently we only remove 'font-size' for selected inlineElement. But we actually should do this for all related BlockElements, and use HtmlSanitizer to help loop each elements
#380 Hyperlinks absorb all text/images pasted next to them
We already have a similar fix for inserting text for Firefox, we just need to also apply that fix to paste event in all browsers
#388 HTML sanitizer bypass
Add a XSS check to the link url when insert link using HtmlSanitizer
Bump version to 7.10.3
> 7.10.3: Fix #388, #380, #349

- package.json
- packages/roosterjs-html-sanitizer/lib/sanitizer/HtmlSanitizer.ts
- packages/roosterjs-html-sanitizer/lib/test/sanitizeHtmlTest.ts
- packages/roosterjs-html-sanitizer/package.json
I was misunderstanding the bug. Now fix it again inside HtmlSanitizer.
The fix is to use a regex to be able to match any NewLine char inside the script prefix since browser will ignore them.
e.g:
```
javascript
:
```
will be treated as 
```
javascript:
```
by browser. So we need to match the NewLine and also treat as "javascript:".
> Fix #388 (2nd try)

- packages/roosterjs-editor-api/lib/test/utils/processListTest.ts
- packages/roosterjs-editor-api/lib/utils/processList.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/ContentEditFeatures.ts
Chromium has a bug (https://bugs.chromium.org/p/chromium/issues/detail?id=944178#c4) which nukes a bunch of stuff when you outdent. We added some logic in a prior PR to attempt to clone the node when we outdent in a list.
This PR further extends this work to
1) Apply when enter is pressed on the end of the list (in an attempt to preserve style information in these cases)
2) Append the image element to the end instead of to the beginning to prevent Chromium from thinking that the span element should be removed due to no content.
> Fix bullet style loss when exiting a list

- package.json
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/test/editor/EditorTest.ts
When call Editor.insertContent() with HTML represents multiple HTML nodes, insertContent() will insert them in a reversed order, because we insert nodes one by one but cursor is not changed.
The fix is to create a fragment and put all nodes under it first, then insert the fragment with a single insertNode() call.
> 7.11.1 Fix bug in Editor.insertContent

- package.json
- packages/roosterjs-editor-api/lib/test/utils/processListTest.ts
- packages/roosterjs-editor-api/lib/utils/processList.ts
Chromium's CED implementation is lacking, and I've decided to give up on using `execCommand` as much as possible and instead use our own behaviors. With a couple utility functions we use elsewhere in the code, this should fix the bulk of issues we've been seeing recently.
> Manual handling for bulleting for Chrome

- package.json
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/tableFeatures.ts
`editor.getFocusedPosition()` can return a null value. Without checking for it, we throw an exception inside of `cacheGetTableCell`. Adding an explicit null check should help.
> Fix potential null in tableFeatures

- webpack.config.js
There is a breaking change in url-loader 3.0.0: https://github.com/webpack-contrib/url-loader/releases/tag/v3.0.0
So let's follow their change and make demo site icon works.
> Fix icons in demo site

- packages/roosterjs-editor-dom/lib/test/utils/shouldSkipNodeTest.ts
- packages/roosterjs-editor-dom/lib/utils/shouldSkipNode.ts
Empty div "< div>< /div>" renders nothing. So it should not be treated as a block element. We should skip it when get next/previous inline/block element
> Skip Empty DIV when traverse

- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/interfaces/EditorOptions.ts
- publish/samplesite/scripts/controls/BuildInPluginState.ts
- publish/samplesite/scripts/controls/editor/Editor.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/EditorCode.ts
This is the second preparation step of upcoming VList change. This will add a new editor option "useExperimentFeatures", by default it is fause. When set it to true, we will automatically enable experiment feature, such as VList and Region in next PR.
This change also add an option in the demo site to allow swich the experiment option.
> VList preparation Step 2

- packages/roosterjs-editor-api/lib/test/format/createLinkTest.ts
- packages/roosterjs-editor-api/lib/test/utils/processListTest.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/ContentTraverser.ts
- packages/roosterjs-editor-dom/lib/selection/Position.ts
- packages/roosterjs-editor-dom/lib/test/selections/getPositionRectTest.ts
- packages/roosterjs-editor-dom/lib/test/utils/getLeafSiblingTest.ts
- packages/roosterjs-editor-dom/lib/test/utils/queryElementsTest.ts
- packages/roosterjs-editor-dom/lib/utils/getLeafSibling.ts
- packages/roosterjs-editor-dom/lib/utils/queryElements.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/listFeatures.ts
This is a preparation step of the upcoming VList change. It includes:
1. Add an optional parameter "skipTags" to ContentTraverser and getNext/PreviousLeafSibling to allow skip some child nodes. These nodes will be ignored when traverse under a region (will be included in later change). e.g.
```html
<div>...</div>
<table>...</table>
<div>...</div>
```
When a selection covers all these nodes, they will be treated in the same region, so table structure should not be changed during formatting, then we can set TABLE as a skip tag so all child nodes under table will be ignored.
2. queryElements should check the real start and end nodes, but not their container. e.g.
```html
<div id="outerDiv">
<div id="innerDIV1">...</div>
<div id="innerDIV2">...</div>
</div>
```
When selection range equal to: …
> VList preparation Step 1

- packages/roosterjs-editor-api/lib/experiment/experimentSetIndentation.ts
- packages/roosterjs-editor-api/lib/experiment/experimentToggleListType.ts
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-api/lib/format/toggleBullet.ts
- packages/roosterjs-editor-api/lib/format/toggleNumbering.ts
- packages/roosterjs-editor-api/lib/utils/blockFormat.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/list/VList.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/createVListFromRegion.ts
- packages/roosterjs-editor-dom/lib/list/getListTypeFromNode.ts
- packages/roosterjs-editor-dom/lib/test/list/VListItemTest.ts
- packages/roosterjs-editor-dom/lib/test/list/VListTest.ts
- packages/roosterjs-editor-dom/lib/test/list/createVListFromRegionTest.ts
- packages/roosterjs-editor-dom/lib/test/list/getListTypeFromNodeTest.ts
- packages/roosterjs-editor-dom/lib/test/utils/shouldSkipNodeTest.ts
- packages/roosterjs-editor-dom/lib/utils/getLeafSibling.ts
- packages/roosterjs-editor-dom/lib/utils/isBlockElement.ts
- packages/roosterjs-editor-dom/lib/utils/shouldSkipNode.ts
- packages/roosterjs-editor-types/lib/enum/ListType.ts
- packages/roosterjs-editor-types/lib/index.ts
This is the implementation of VList and VListItem.
The design:
Each list item will map to a VListItem object. For example:
```html
<ol>
<li>line 1</li>
<ul>
<li>line 2</li>
</ul>
<li>line 3</li>
</ol>
```
This will be mapped to a VList object: (pseudo code)
```json
{
"items": [{
"listTypes": ["None", "OL"],
"node": "line 1"
}, {
"listTypes": ["None", "OL", "UL"],
"node": "line 2"
}, {
"listTypes": ["None", "OL"],
"node": "line 3"
}],
}
```
For convience, we always put a "None" as the first element of list type so that even we outdent the list item to top level, we can still easily know the list type.
Then when we need to do action to the list, like indent, outdent, ..., we just need to change the list type array, then call writeBack() to write the change back to DOM.
Related test cases …
> VList implementation

- package.json
- packages/roosterjs-editor-dom/lib/utils/queryElements.ts
Bugs found:
1. In queryElements.ts, we need to check if range.startContainer[range.startOffset] is valid because startOffset can be length + 1 when focus is after the last child node.
> Fix bugs of 7.12.0

- package.json
- packages/roosterjs-editor-core/lib/editor/Editor.ts
In Editor.getContent(), when we want to include selection path in the content and editor is in dark mode, the selection path won't be included. 
This change fixed this issue.
> Fix regression in Editor.getContent() with selection path

- package.json
- packages/roosterjs-cross-window/package.json
- packages/roosterjs-editor-plugins/lib/plugins/Entity/EntityFeatures.ts
- packages/roosterjs-editor-plugins/lib/plugins/Entity/EntityInfo.ts
- packages/roosterjs-editor-plugins/lib/plugins/Entity/insertEntity.ts
- packages/roosterjs-html-sanitizer/package.json
- packages/roosterjs-plugin-image-resize/package.json
- packages/roosterjs-plugin-picker/package.json
- tools/build.js
Fix two null-check issues
Don't set display to "inline-block" for editable entity since it will cause a resize border in IE
Modify the build script to respect the explicitly specified dependency version
Modify the dependency versions to make a final version of deprecated packages
> 7.13.2 Fix some entity bugs

- package.json
- packages/roosterjs-editor-core/lib/coreAPI/createPasteFragment.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/Paste.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/excelConverter/convertPastedContentFromExcel.ts
The issue is when move a STYLE tag from a document into a fragment, it will lose all style sheets.
The fix is to consume the sanitizer options and use "additionalGlobalStyleNodes" to include the style nodes to avoid it lose info.
> Fix paste from Excel issue

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/Paste/Paste.ts
Google sheet generates a special tag "google-sheets-html-origin" when copy and our code will filter it out. So that content can't be pasted.
The fix is to allow that tag.
> Fix paste from google sheet

- package.json
- tools/build.js
- yarn.lock
We use typedoc to generate API reference doc. However, it will generate "References" sections for each "re-export" functions/interfaces/... and unfortunately, we re-export everything from index.ts file which means everything will have a duplicated "reference" in the API reference file:
I found there is a plugin "typedoc-plugin-exclude-references" that can remove such references which works pretty well. So I add this plugin to our build script.
> Remove "references" from API reference doc

- package.json
- packages/roosterjs-editor-core/lib/coreAPI/insertNode.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/tableFeatures.ts
When call Editor.insertContent() to insert some text on new line, the inserted text is still on the same line.
This issue is related to [PR](https://github.com/microsoft/roosterjs/pull/401). The root cause is Node.insertBefore() returns an empty DocumentFragment if the node to be inserted is DocumentFragment, so the inserted node will not be wrapped with DIV.
The solution is use childNodes of DocumentFragment as insertedNode and pass them to wrap(), so that they can be wrapped.
@JiuqingSong Could you help review it? Thanks!
> Fix insert DocumentFragment node

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/Paste/excelConverter/convertPastedContentFromExcel.ts
When handle the pasted content from Excel, there is code bug to operate the html string which misused variable "html" and "newHtml". Fix it bug only use "html" var.
> Fix paste from excel bug

- packages/roosterjs-editor-dom/lib/htmlSanitizer/HtmlSanitizer.ts
- packages/roosterjs-editor-dom/lib/htmlSanitizer/createDefaultHtmlSanitizerOptions.ts
- packages/roosterjs-editor-dom/lib/htmlSanitizer/getAllowedValues.ts
- packages/roosterjs-editor-dom/test/htmlSanitizer/sanitizeHtmlTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/Paste.ts
- packages/roosterjs-editor-types/lib/interface/HtmlSanitizerOptions.ts
Provide an option to decide how to handle unknown HTML tags when do sanitization.
- A valid string: replace unknown tags with this tag name
- An empty string: keep as it is
- null/undefined: Drop unknown tags and all its children
> HtmlSanitizer: Handle unknown tags

- demo/scripts/controls/BuildInPluginState.ts
- demo/scripts/controls/editor/Editor.tsx
- demo/scripts/controls/editor/EditorInstanceToggleablePlugins.ts
- demo/scripts/controls/sidePane/editorOptions/ContentEditFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/Plugins.tsx
- demo/scripts/controls/sidePane/editorOptions/codes/PluginsCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/SimplePluginCode.ts
- packages/roosterjs-editor-api/lib/experiment/experimentCommitListChains.ts
- packages/roosterjs-editor-api/lib/experiment/experimentToggleListType.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-api/lib/utils/blockFormat.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/list/VList.ts
- packages/roosterjs-editor-dom/lib/list/VListChain.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/createVListFromRegion.ts
- packages/roosterjs-editor-dom/lib/list/getRootListNode.ts
- packages/roosterjs-editor-dom/test/list/VListChainTest.ts
- packages/roosterjs-editor-dom/test/list/VListItemTest.ts
- packages/roosterjs-editor-dom/test/list/VListTest.ts
- packages/roosterjs-editor-dom/test/list/createVListFromRegionTest.ts
- packages/roosterjs-editor-dom/test/list/getRootListNodeTest.ts
- packages/roosterjs-editor-plugins/lib/CutPasteListChain.ts
- packages/roosterjs-editor-plugins/lib/index.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-plugins/lib/plugins/CutPasteListChain/CutPasteListChain.ts
- packages/roosterjs-editor-plugins/lib/plugins/CutPasteListChain/index.ts
- packages/roosterjs-editor-types/lib/enum/ChangeSource.ts
- packages/roosterjs-editor-types/lib/interface/ContentEditFeatureSettings.ts
Introduce the new VListChain concept.
e.g, we have two lists:
1
2
3
and
4
5
6
VListChain will chain them together so that if we make any change to the first list, the second one can also be maintained.
This change can handle the following changes:
- Enter in list to generate new item
- Delete/Backspace in list to remove/merge item
- Select some lists then type to replace items
- Tab/Shift+Tab to indent/outdent list items
- Auto start new list item (type number + "." + Space)
- Enter/Backspace on empty list item to quite current list
- Cut from list
- Paste into list
- Drag and drop with list
All features can only work when "useExperimetalFeatures" flag is on (by default enabled in demo site)
> Continued List -- VListChain

- packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts
If a Picker is active (isSuggesting == true), and a user backspaces over the trigger character we do not immediately deactivate the Picker. The result is that we continue calling the getRangeUntilAt method and look for all the text between the current cursor and the previous trigger character.  If the result is empty, then we deactivate the Picker. If there happens to be another trigger character located earlier in the selection context, we return that incorrect result and display it in the active Picker. 
This PR stops that behavior by detecting the backspace over the trigger character and deactivating the Picker. I tested this in the Rooster demo (using the sample color picker) and then in OWA using the emoji and at mentions pickers.
See Issue #483
> Fix for issue #483 - Problems with multiple trigger characters in Picker Plugin 

- packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResize.ts
Adding ability to resize in single direction.
- Created new handles for n, s, e and w in the resizeDiv.
- When the resize is happening, reposition the handles in reference to the changing width and height of the image.
- When dragging the single direction handles, only allow the change in either width or height.
- Note: The forcePreserveRatio setting only applies to the corner handles and not the single direction ones.
> Adding single direction resize

- packages/roosterjs-editor-plugins/lib/plugins/HyperLink/HyperLink.ts
This is an attempted fix for #254 where editing a link's URL does not update the href attribute.
The fix has the following behavior:
In the Hyperlink plugin, if we have either mouse up or key up events and the keycode is a directional key (pageup, pagedown, home, end, left/up/right/down), the code checks if the link's display text matches the href value of the link. If it does, it stores the link element away so that we can know if the cursor has moved away from the link. When we receive another event of the same kind, we will check if the current element at the cursor is different from the one that was stored away. If it is different, and the display text is a valid URL, then we will clone the element, update the href attribute on the cloned element to match the display text URL, and …
> Allow editing of link URLs through display text

- packages/roosterjs-editor-types/lib/interface/PickerDataProvider.ts
In Issue #484, it appears that the documentation for the PickerDataProvider interface needs clarification with respect to the setIsSuggestingCallback method.
This PR attempts to clarify that interface.
> Clarify documentation for the PickerDataProvider interface

- demo/scripts/controls/BuildInPluginState.ts
- demo/scripts/controls/editor/Editor.tsx
- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
- demo/scripts/controls/sidePane/editorOptions/Plugins.tsx
- packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResize.ts
Issues:
When force preserve ratio, can't do single dir resize, it always resize both directions
When force preserve ratio, single dir resize can't make image smaller
When force preserve ratio, hard to resize image smaller using corner handle
Fix:
Change the algorithm of size calculation
Add option in demo site to allow force preserve ratio
> Improve image resize

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
* Fixed the bug where a long word in a TD doesn't auto-wrap during resizing
* Fixed the bug where it would do vertical resizing after user resized the cell horizontally
* Enlarged the region of detecting the resizer so it would be easier to be triggered when the table is on top or on the most left in the container
> Fix some table resize issues

- packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResize.ts
Moving image is natively supported by browser, but our ImageResize plugin has event handler for MouseDown plugin and make change to the image, which causes the image can't be moved.
The fix is to split the action of mouse down event into mouse down and mouse up. For mouse down, we deselect image if any, then reselect when mouse up. So that for drag event, the image can be detected by browser.
> Allow move image

- packages/roosterjs-editor-core/lib/corePlugins/TypeAfterLinkPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/typeAfterLinkPluginTest.ts
We have such check for "paste after link", now we also handle this for "before link"
> When paste before a link, make sure the pasted text is not inserted into link

- packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResize.ts
For some special image, style inline-flex makes it shows incorrectly. So for safari, use inline-block instead.
> Fix Inline image resize bug for safari

- packages/roosterjs-editor-plugins/lib/plugins/Paste/Paste.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/teamsConverter/convertPastedContentFromTeams.ts
It is possible to paste LI tag directly under DIV when copy from Teams. We need to convert the DIV to UL tag.
> Fix list issue when paste from Teams

- demo/scripts/controls/sidePane/eventViewer/EventViewPane.tsx
- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-core/lib/corePlugins/createCorePlugins.ts
- packages/roosterjs-editor-core/test/coreApi/createPasteFragmentTest.ts
- packages/roosterjs-editor-core/test/corePlugins/copyPastePluginTest.ts
- packages/roosterjs-editor-dom/lib/utils/extractClipboardEvent.ts
- packages/roosterjs-editor-types/lib/corePluginState/CopyPastePluginState.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/ClipboardData.ts
- packages/roosterjs-editor-types/lib/interface/CorePlugins.ts
- packages/roosterjs-editor-types/lib/interface/EditorOptions.ts
- packages/roosterjs-editor-types/lib/interface/ExtractClipboardEventOption.ts
Add a new editor option: allowedCustomPasteType. Use this option to allow retrieving more content type when paste besides default types.
To use it, pass your custom values when init editor.
```ts
const editor = new Editor(div, {
...
allowedCustomPasteType: [ 'type1', 'type2' ],
};
```
Note that only **text types** as supported, and no need to add the "text/" prefix.
To get the custom value, use ClipboardData.customValues:
```ts
onPluginEvent(e) {
if (e.eventType == PluginEventType.BeforePaste) {
const valueOfType1 = e.clipboardData.customValues['type1'];
...
}
}
```
> All custom paste type

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
Repro:
1. Enable content edit feature "Merge in new line when Backspace on first char in list"
2. create a list
3. locate to the beginning of the second list item, shift+right to select some text
4. BackSpace
Expect: selected text is deleted, no other change
Actual: a new line is created
Reason: the content edit feature "Merge in new line when Backspace on first char in list" is run here which should not
Fix: check if the selection is collapsed.
> fix backspace in list issue

- packages/roosterjs-editor-dom/lib/selection/getSelectionPath.ts
- packages/roosterjs-editor-dom/test/selections/getSelectionPathTest.ts
When there are continuous text node, selection path will treat them as a single text node. This is fine when we get HTML with selection path and set them back into editor. However, if we want to clone the DOM tree and set selection with selection path (e.g. shadow edit scenario), it becomes a problem. To fix it, we can do text node normalization before getting selection path.
> Fix selectionPath bug

- packages/roosterjs-editor-dom/lib/list/VList.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/test/list/VListItemTest.ts
- packages/roosterjs-editor-dom/test/list/VListTest.ts
- packages/roosterjs-editor-dom/test/list/createVListFromRegionTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
A "dummy" list item is a list item without a bullet or a number. In below example "line 2" is a dummy list item.
To create a dummy list item:
1. Enable content edit feature "Merge in new line when Backspace on first char in list":
2. Create a regular list
3. Put cursor at the beginning of a list item
4. Press backspace
Also fix auto bullet bug on iOS. (#532 )
> Support "dummy list item"

- packages/roosterjs-editor-core/lib/corePlugins/DOMEventPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/domEventPluginTest.ts
We have a lot of duplicated code to listen to scroll event from both scroll container and window. We can trigger the same event from window scroll from roosterjs, so that plugins just need to listen to one event.
> Trigger scroll event when window scroll

- demo/scripts/controls/ribbon/RibbonButton.tsx
- packages/roosterjs-editor-core/lib/corePlugins/DOMEventPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/domEventPluginTest.ts
We save selection range when editor got onblur event. But this doesn't work for safari. When we get selection range when blur in Safari, it will return the range of new focus, so we can't get the range to save. Currently we have a lot of workaround to fix this issue. Here I'd like to make a final fix.
The idea is to get selection range before any chance of losing focus, including:
- Press TAB key
- Click on other part of the page
- The whole window is blurred
When one of these conditions happens, we get currente selection range and save it. Then next time when we call editor.focus(), it will retrieve this saved range and restore it.
> Fix Safari lost focus issue

- package.json
- packages/roosterjs-editor-core/lib/coreApi/getContent.ts
- packages/roosterjs-editor-core/lib/coreApi/switchShadowEdit.ts
- packages/roosterjs-editor-core/test/coreApi/getContentTest.ts
There is a bug when copy/cut content if there is empty text node insde or before the selection. Please see the new test case for the scenario.
Normally an empty text node means nothing, we should remove them. And when we get selection path, continuous text node will be treated as single text node, empty text node will be ignored. However, if we apply a selection path on the original DOM tree or a cloned DOM tree, this becomes a problem because those text node still exist.
e.g. DOM tree:
"text1"
"" <-- empty node
"text2"
It will be renderred as 
"text1text2"
But the offset inside text2 will be calculated together with "text1" and "". So if the original DOM tree or cloned DOM tree is not normalized (merge those text nodes), selection path becomes wrong.
To fix it, we can normalize the DOM …
> 8.2.8: Fix a bug when copy/cut with empty text node

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- When we add a new row/column to the table, the table size will be changed, as a result, we need to update the resizer position accordingly to avoid visual inconsistency. 
- Hide table resize on scrolling for the same reason
> Fix table resizer position when adding new row/column

- packages/roosterjs-editor-core/lib/coreApi/switchShadowEdit.ts
My previous fix https://github.com/microsoft/roosterjs/pull/555 cause an issue that shadow edit may focus on wrong selection. It is because we do text node normalization before content is really appended. Fix it by move the the normalization code.
> Fix shadow edit bug

- packages/roosterjs-editor-dom/lib/htmlSanitizer/HtmlSanitizer.ts
- packages/roosterjs-editor-dom/lib/htmlSanitizer/createDefaultHtmlSanitizerOptions.ts
- packages/roosterjs-editor-dom/test/htmlSanitizer/sanitizeHtmlTest.ts
- packages/roosterjs-editor-types/lib/interface/HtmlSanitizerOptions.ts
Hello,
this is a proposal to add an option to keep HTML comments when using `sanitizeHtml`.
I don't think HTML comments are a risk, but if I'm wrong I'd love to know why.
> Add HtmlSanitizer preserveHtmlComments option

- packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResizeHandler.ts
Hello,
If `ExperimentalFeatures.SingleDirectionResize` is disabled, there is a JS error when disposing of the resize handlers here
https://github.com/microsoft/roosterjs/blob/a79ba502b6a53a8a625b538eed6428a3dbf9f3d3/packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResizeHandler.ts#L118-L121
because we are skipping an index in here (step = 2)
https://github.com/microsoft/roosterjs/blob/a79ba502b6a53a8a625b538eed6428a3dbf9f3d3/packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResizeHandler.ts#L149-L150
resulting in `this.resizeHelpers` having undefined on every odd index
> Fix JS error if !ExperimentalFeatures.SingleDirectionResize

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResizeHandler.ts
This is a temp fix to show resize border when single direction image resize is not enabled.
(This fix will be overwritten by the new image edit plugin in #572 )
> 8.5.0 Fix resize border

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- packages/roosterjs-editor-plugins/test/TableResize/tableResizeTest.ts
**Description**
When we move the mouse out of the inserter and land on other components, we need to hide the inserter element.
**Bug description:** 
When moving the mouse to other components the inserter bar was not being removed from the table and this was causing issues when resizing the screen.
**Solution** 
This bug is an edge case when the table is touching a border of the editor.
My approach is to add add a "mouseout" event handler in the [inserterTd ](https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts#L288) element to avoid the bug when the "+" button is rendered passing the border of the editing zone 
I also modified the [current](https://github.com/microsoft/roosterjs/blob/cfe4f3515833480b66f4c0214f93bc337410 …
> Hide inserter when moving mouse to another component

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/listFeaturesTest.ts
Autobullet should allow for additional patterns to trigger its behavior.
Current pattern:
"1."
New Patterns available:
"1-"
"1)"
"1>"
"(1)"
**Tests**
* Tested locally with demo deployment of roosterjs
* Unit tests added to cover new behavior
> Add additional patterns to autobullet feature

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/Paste/commonConverter/convertPastedContentForLI.ts
- packages/roosterjs-editor-plugins/test/paste/convertPastedContentForLITest.ts
There is a regression in 8.5.0 when paste a single element without any child node. It will always change the element tag to UL since it can pass the check if all child nodes are LI.
Fix it by checking there must be at least one LI child node. Related test case added.
> 8.6.1 Fix #592

- packages/roosterjs-editor-plugins/test/TableResize/tableResizeTest.ts
Fixed failing test cases in tableResize plugin, two tests were failing then running the CI pipeline,.
Reduced the pixel measures to avoid pixel related errors.
Update: the CI pipeline is still failing after the changes, removing RTL tests to unblock the pipeline and investigate locally why the tests are not always failling.
> Fix failing test case in tableResize plugin

- README.md
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-core/lib/coreApi/ensureTypeInContainer.ts
- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/createVListFromRegion.ts
- packages/roosterjs-editor-dom/lib/region/getSelectedBlockElementsInRegion.ts
- packages/roosterjs-editor-dom/lib/utils/createElement.ts
- packages/roosterjs-editor-dom/lib/utils/fromHtml.ts
- packages/roosterjs-editor-dom/lib/utils/wrap.ts
- packages/roosterjs-editor-dom/test/utils/createElementTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/structuredNodeFeatures.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContextMenu/ContextMenu.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Cropper.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Resizer.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Rotator.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/types/ImageHtmlOptions.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- packages/roosterjs-editor-types/lib/enum/KnownCreateElementDataIndex.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/CreateElementData.ts
- packages/roosterjs-editor-types/lib/interface/ImageEditOptions.ts
innerHTML is widely used in roosterjs. To support TrustedType, we need to avoid assigning value to innerHTML.
This is the first step, since function fromHtml() is based on innerHTML, we deprecate it, and replace with a new function createElement()
> Support TrustedType step 1: Replace fromHtml with createElement

- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/samplepicker/SampleColorPickerPluginDataProvider.tsx
- packages/roosterjs-editor-api/lib/format/toggleHeader.ts
- packages/roosterjs-editor-core/lib/coreApi/createPasteFragment.ts
- packages/roosterjs-editor-core/lib/coreApi/switchShadowEdit.ts
- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/selection/getPositionRect.ts
- packages/roosterjs-editor-dom/lib/table/VTable.ts
- packages/roosterjs-editor-dom/lib/utils/changeElementTag.ts
- packages/roosterjs-editor-dom/lib/utils/moveChildNodes.ts
- packages/roosterjs-editor-dom/test/utils/moveChildNodesTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/excelConverter/convertPastedContentFromExcel.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/pptConverter/convertPastedContentFromPowerPoint.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/wordConverter/convertPastedContentFromWord.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/wordConverter/converterUtils.ts
In this change I remove most of the places where we assign value to innerHTML.
I also add a new util moveChildNodes() to help move child nodes from one node to another, this also helps remove innerHTML usage.
> Support TrustedType step 2: Remove usage of innerHTML

- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
We use a Regex to match existing Entity Id. However the regex misses a ( ) to capture the id number. We need to fix it.
> Fix the EntityId Regex

- demo/scripts/utils/trustedHTMLHandler.ts
- packages/roosterjs-editor-dom/lib/selection/setHtmlWithSelectionPath.ts
- packages/roosterjs-editor-dom/test/selections/setHtmlWithSelectionPathTest.ts
With DOMPurify, comment will be removed when sanitize html, so that selection path won't work since it is based on HTML commment. To fix it, let's add a fallback logic in setHtmlWithSelectionPath in case comment is removed.
Related test added.
> Fix setHtmlWithSelectionPath with DOMPurify

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
When selecting photo and the text align was center or right, the image was overflowing the Image Edit Wrapper. Also when debugging I found another behavior when the RTL was enabled causing the overflow when the text align was center or left.
Previous behavior:
After code changes
> Fix image Overflowing the editor wrapper

- demo/scripts/controls/editor/EntityHydratingPlugin.ts
- demo/scripts/controls/plugins.ts
- demo/scripts/controls/sidePane/apiPlayground/insertEntity/InsertEntityPane.tsx
- demo/scripts/controls/sidePane/eventViewer/EventViewPane.tsx
- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/corePlugins/copyPastePluginTest.ts
- packages/roosterjs-editor-core/test/corePlugins/entityPluginTest.ts
- packages/roosterjs-editor-core/test/editor/newEditorTest.ts
- packages/roosterjs-editor-dom/test/DomTestHelper.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
- packages/roosterjs-editor-types/lib/corePluginState/EntityPluginState.ts
- packages/roosterjs-editor-types/lib/enum/EntityOperation.ts
- packages/roosterjs-editor-types/lib/event/EntityOperationEvent.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
This is the change to introduce Shadow DOM entity. Shadow DOM entity is the new functionality of entity API. It allows hydrate an entity under a shadow DOM root, and benefit React Entity, undo snapshot, memory management.
The new API is fully compatible with existing API. Existing code based on Entity API can still work.
To use shadow DOM entity, just need to handle EntityOperation event (event.operation==EntityOperation.NewEntity), and put the hydrated content under event.contentForShadowEntity. Then Entity API will mount it and do memory management.
Two new EntityOperation enum values are added:
- AddShadowRoot triggers when a new shadowRoot is added into entity
- RemoveShadowRoot triggers when an existing shadowRoot is removed
> Shadow DOM entity

- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/entityPluginTest.ts
In my previous change I added a new ContentEditFeature in EntityPlugin to workaround some issue with ShadowDomEntity. However, this feature is conflict with another ContentEditFeature - MergeInNewLine in listfeatures.ts.
As a short term fix, I temporarily removed this workaround code. For long term, we need to reconsider the design of ContentEditFeature to better handle conflict.
> Fix a conflict issue between list features and entity plugin

- package.json
- packages/tsconfig.json
- yarn.lock
With my previous PR (#666), roosterjs package document shows a lot of exports that are actually exported from other packages. This can be fixed by adding an "exclude" param in the typedoc param list.
Also remove an unnecessary plugin of typedoc.
Before:
After:
> Remove "reference  export" from doc of roosterjs package

- package.json
- packages/roosterjs-editor-core/lib/corePlugins/LifecyclePlugin.ts
In 8.11.1 there is a change to remove webkitUserSelect style when init. This causes sometimes use can't type in the editor in Safari. So let's add it back
> 8.11.2 Fix a bug for Safari

- packages/roosterjs-editor-dom/lib/clipboard/extractClipboardItems.ts
- packages/roosterjs-editor-dom/test/clipboard/extractClipboardItemsTest.ts
When paste an image with image/svg+xml content type, our code try to get the content blob as file but it is actually string. 
Let's ignore those images for now by checking the clipboard item kind property.
> fix paste SVG issue

- demo/index.html
- demo/scripts/controls/sidePane/apiPlayground/sanitizer/SanitizerPane.tsx
- demo/scripts/utils/trustedHTMLHandler.ts
- index.html
- packages/roosterjs-editor-dom/lib/htmlSanitizer/HtmlSanitizer.ts
- packages/roosterjs-editor-types/lib/interface/SanitizeHtmlOptions.ts
Most of our code already support this security level. The only places are:
1. In HtmlSanitizer.ts, we create sanitizer function with our own code. We can remove the code and mark the related functions as deprecated since we are actually not using them at alll.
2. In trustedHTMLHandler.ts in demo site, we can directly use DOMPurify.sanitize() and no need to create a new security policy. This is for demo site only and no impact to production code.
> Support "trusted-types dompurify"

- packages/roosterjs-editor-core/lib/coreApi/transformColor.ts
- packages/roosterjs-editor-core/test/coreApi/transformColorTest.ts
When color style is "inherit", color transform function will incorrectly calculate its color for dark mode. So we can skip calculating them and let them keep "inherit" parent element's color.
> Support "inherit" color for dark mode color transform

- .github/workflows/build-and-deploy.yml
- .github/workflows/build-and-test.yml
It seems like the default version of node in github actions is not working fine when building.
The latest npm version that the github actions is 8.1.0 which is stricter with the dependencies.
Lowering the node version to 14.18.2 and the npm version to 6.14.15 works fine.
> Change Node version in Github actions

- package.json
- packages/roosterjs-editor-dom/lib/utils/changeElementTag.ts
- packages/roosterjs-editor-dom/test/utils/changeElementTagTest.ts
Due to a conflict with table format feature, table cell is not working now. Fix it by preserving the same node when changeElementTag to the same tag name
> 8.15.0 Fix table resize bug

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
If the editor is in a scrollable container and you start scrolling the TableResize plugin breaks.
The error can be reproduced by adding min-height to the .mainPane container on the demo page and setting it to a value at which the scrollbar appears. If you then add a table and scroll down a bit the resize function is broken.
The reason seems to be that in the onMouseMove event the cursor coordinates are directly compared with the table rect coordinates. But the cursor coordinates are the absolute position on the page and the table rect coordinates are relative to the browser window. So subtracting the scroll position from the cursor coordinates should fix the issue.
I was able to reproduce the issue and also test the fix in Firefox, Chrome und Edge.
> Fix for scroll issue in the table resize plugin

- packages/roosterjs-editor-dom/lib/clipboard/extractClipboardEvent.ts
- packages/roosterjs-editor-dom/lib/clipboard/extractClipboardItems.ts
- packages/roosterjs-editor-dom/lib/clipboard/extractClipboardItemsForIE.ts
- packages/roosterjs-editor-dom/lib/clipboard/tsconfig.child.json
- packages/roosterjs-editor-dom/lib/event/isCharacterValue.ts
- packages/roosterjs-editor-dom/lib/event/tsconfig.child.json
- packages/roosterjs-editor-types/lib/interface/ClipboardData.ts
Enable strict mode for 
roosterjs-editor-dom/lib/event
roosterjs-editor-dom/lib/clipboard
> Enable strict mode for event and clipboard

- packages/roosterjs-editor-core/lib/coreApi/getSelectionRangeEx.ts
- packages/roosterjs-editor-core/test/coreApi/getSelectionRangeExTest.ts
When editor hasn't got focus, there is no range. So when we call getSelectionRangeEx(), we should return empty array but not an array with null element.
> Fix bug in shadowEditTableSelection

- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
Cut operation is no longer working on Android. Its behavior becomes the same as copy. Selected range will not be deleted, even though it will still be coped to clipboard.
For more details: #797
Before:
After:
> Fix Cut failed on Android since we collapse selection range before deleteSelectedContent #797

- package.json
- packages-ui/roosterjs-react/package.json
- Bump roosterjs to 8.18.0
- Start to publish roosterjs-react
> Bump version to 8.18.0

- packages/roosterjs-editor-api/lib/table/editTable.ts
- packages/roosterjs-editor-api/lib/table/formatTable.ts
- packages/roosterjs-editor-core/lib/coreApi/transformColor.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/coreApi/transformColorTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableInserter.ts
- packages/roosterjs-editor-types/lib/interface/EditorCore.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
1. To fix #838 , read colors at once when do color transform, then write back together for all elements
2. To fix #835 , add new API IEditor.transformToDarkColor() to allow trigger color transformation outside editor
3. Fix existing usage of editor.replaceNode() with transformToDarkColor.
> Dark and undo step 1: Improve color transformation

- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-dom/lib/list/VList.ts
We were checking whether the List Item was Ordered, but this is not required. 
Checking if the LI was a Ordered Item caused the API to not work with UL Lists, removing this check will fix this issue.
> Remove unneeded check in getListItemIndex in VList

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/textFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/textFeaturesTest.ts
When using the tab key with the TabKeyFeatures experimental feature enabled, we add the tab spaces correctly, but the cursor is not updated.
Before
After
> Fix issue when using Tab before Anchor Element

- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
After copying the focus is lost, is because a recent change when trying to restore the Selection after copy.
Before
After
> Fix after copy the focus is lost.

- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
Try fix the following error:
Uncaught TypeError: Cannot set properties of null (setting 'firstCell')
roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts:259
roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts:234
roosterjs-editor-core/lib/editor/Editor.ts:708
ORIGINAL ERROR:
Uncaught TypeError: Cannot set properties of null (setting 'firstCell')
Not sure why this error is happening, as we only set this.tableRange to null when setting the content to the editor.
> Uncaught TypeError: Cannot set properties of null (setting 'firstCell')

- packages/roosterjs-editor-core/lib/coreApi/ensureTypeInContainer.ts
- packages/roosterjs-editor-core/lib/corePlugins/NormalizeTablePlugin.ts
- packages/roosterjs-editor-core/test/editor/newEditorTest.ts
#872
When setting initial content to start with a table with colgroup the ensureTypeInContainer selected the colgroup element as the initial position.
Then select the block element of the initial position is going to be the thead element that is containing the Colgroup Node. Then the collapseToSingleElement causes the thead to be moved to another table.
Changes:
If the initialContent is a table, try select the first td/th and use it as initial position.
> Fix Problem with setting content with colgroup #872

- demo/scripts/controls/sidePane/editorOptions/ContentEditFeatures.tsx
- packages/roosterjs-editor-types/lib/interface/ContentEditFeatureSettings.ts
Add content to empty Checkboxes in the demo page:
Fix:
> Fix demo page ContentEdit Pane

- tools/buildTools/normalize.js
- tools/buildTools/processConstEnum.js
- tools/start.js
After the latest change, if you run "npm start" or "yarn start" before the first time run "yarn build", it will fail. Because the code to generate compatible types is not run. This change make sure the script will run before start.
> Fix start script

- packages/roosterjs-editor-core/lib/coreApi/transformColor.ts
When copy from dark mode reading pane, sometimes the data-ogsb attribute is not removed, this causes we skip those elements when convert back to dark mode. So add a check, if the data-ogsb value is the same with current value, ignore those data-ogsb value.
> Fix a dark mode issue

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
- packages/roosterjs-editor-types/lib/enum/Keys.ts
Right now, on key up the table selection is cleared when the key is different from SHIFT, adding other keys to prevent the selection from being cleared on CTRL, ALT, Meta Key, Print screen.
> Prevent Table Selection to be cleared on some keys

- packages/roosterjs-editor-api/lib/format/insertImage.ts
Add optional `attributes` parameter to `insertImage` function to enable setting optional attributes on the `<img>` element which allows specifying `aria-` and `alt` tags for accessibility support.
> Add optional image element attributes.

- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/metadata/definitionCreators.ts
- packages/roosterjs-editor-dom/lib/metadata/metadata.ts
- packages/roosterjs-editor-dom/lib/metadata/validate.ts
- packages/roosterjs-editor-dom/lib/selection/setHtmlWithSelectionPath.ts
- packages/roosterjs-editor-dom/test/metadata/definitionCreatorsTest.ts
- packages/roosterjs-editor-dom/test/metadata/metadataTest.ts
- packages/roosterjs-editor-dom/test/metadata/validateTest.ts
- packages/roosterjs-editor-dom/test/selections/deleteSelectedContentTest.ts
- packages/roosterjs-editor-types/lib/enum/DefinitionType.ts
- packages/roosterjs-editor-types/lib/enum/index.ts
- packages/roosterjs-editor-types/lib/type/Definition.ts
- packages/roosterjs-editor-types/lib/type/index.ts
- tools/buildTools/dts.js
In order to store/retrieve metadata for a given element, add types and functions below:
- API to get/set metadata `getMetadata`, `setMetadata`, `removeMetadata`
- API to validate metadata object `validate`
- Helper functions to create type definition `create*Definition`
- Types of definitions
When get a metadata, we can do:
```ts
const metadata = getMetadata(element, def);
```
Here `def` is an optional type definition object used for validating if the metadata object is valid. For example, we have a metadata type:
```ts
interface MyMetadata {
x: number;
y: string;
}
```
and when retrieve it, we can use a type definition object to help validate if the given element contains a valid object with this type:
```ts
const MyMetadataDefinition = createObjectDefinition<MyMetadata>({
x: …
```
> Add metadata API for roosterjs

- packages/roosterjs-editor-api/lib/format/insertImage.ts
Add optional `attributes` parameter to `insertImage` function to enable setting optional attributes on the `<img>` element which allows specifying `aria-` and `alt` tags for accessibility support.
> Adding custom attributes to image element.

- packages/roosterjs-editor-dom/lib/utils/shouldSkipNode.ts
- packages/roosterjs-editor-dom/test/utils/shouldSkipNodeTest.ts
shouldSkipNode() function uses a regex to check if a text node contains only new line char (\r, \n). But the regex actually matches any string that starts with \r\n in a single line.
Change to do full string match instead.
This impact the format API to apply format to a selection with multiple paragraphs.
> Fix #974: change regex so that text node starts with \r\n should not be skipped

- packages/roosterjs-editor-dom/lib/inlineElements/applyTextStyle.ts
- packages/roosterjs-editor-dom/test/inlineElements/applyTextStyleTest.ts
Add sup and sub scripts tag to STYLET_AGS to prevent applyTextStyles to set style directly to these tags.
Then these tags will be wrapped by a span tag and the style will be set to the span tag. 
**Before:**
**After:**
> Add sup and sub tags to apply style outside them

- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
at TableCellSelection.handleKeyDownEvent (webpack-internal:///./node_modules/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.js:250:61)
at TableCellSelection.onPluginEvent (webpack-internal:///./node_modules/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.js:159:30)
> TypeError: Cannot read properties of null (reading 'node')

- demo/scripts/controls/MainPane.scss
- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/sidePane/SidePane.scss
- demo/scripts/controls/sidePane/apiPlayground/region/GetSelectedRegionsPane.scss
- demo/scripts/controls/sidePane/formatState/FormatStatePane.scss
- demo/scripts/controls/sidePane/snapshot/SnapshotPane.scss
- demo/scripts/controls/theme/theme.scss
- demo/scripts/controls/titleBar/TitleBar.scss
1. Add dark theme using FluentUI ThemeProvider
2. Apply dark them when browser is in dark mode
3. Apply dark mode to editor when browser is in dark mode
4. Auto change theme when browser theme is changed
Light Mode:
Dark Mode:
> Support dark theme in demo site

- packages/roosterjs-editor-types/lib/interface/UndoSnapshotsService.ts
We are returning null for this function today when no more undo/redo snapshot to move. However the function signature doesn't allow it, this prevent us moving towards strict mode.
> Allow return null for UndoSnapshotService.move

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/shortcutFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/shortcutFeatureTest.ts
Currently we lack a keyboard shortcut for clearing the format of the selection. 
This change binds this action to the Ctrl + Spacebar press.
> Add key binding for clearing format

- packages/roosterjs-editor-core/lib/corePlugins/UndoPlugin.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/shortcutFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/shortcutFeatureTest.ts
This PR removes the unpredictability of pressing Alt+Backspace multiple times, see issue for additional context
This was done by adding a new keyboard shortcut to the ContentEdit plugin, as well as making UndoPlugin ignore Alt+Backspace presses
> Introduce new Alt+Backspace combo for undo

- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
Sometimes there is a null exception during the extractClipboardEvent. Adding a null check in case the editor got disposed during the Async promise to extract the ClipboardData.
> Add null check during to editor instance in extractClipboardEvent callbacks

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
In a previous change we added a check to only display the TableSelector when the top is inside of the EditorDiv, but we also need to check if the table is inside of the visible part of the scroll container.
> Show table selector if it is inside of the Scroll Container

- packages/roosterjs-editor-core/lib/corePlugins/NormalizeTablePlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/normalizeTablePluginTest.ts
Error
-------------------
COMPONENT ERROR: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
Callstack
-------------------
/roosterjs-editor-core/lib/corePlugins/NormalizeTablePlugin.ts:118
Native Browser Function(Array.forEach):undefined
/roosterjs-editor-core/lib/corePlugins/NormalizeTablePlugin.ts:109
/roosterjs-editor-core/lib/corePlugins/NormalizeTablePlugin.ts:94
/roosterjs-editor-core/lib/corePlugins/NormalizeTablePlugin.ts:58 
/roosterjs-editor-core/lib/editor/Editor.ts:554
> Fix issue in Normalize Table.

- packages/roosterjs-editor-api/lib/format/toggleBullet.ts
- packages/roosterjs-editor-api/lib/utils/toggleListType.ts
- packages/roosterjs-editor-dom/lib/list/VList.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/setBulletListMarkers.ts
- packages/roosterjs-editor-dom/lib/list/setNumberingListMarkers.ts
- packages/roosterjs-editor-dom/test/list/VListItemTest.ts
- packages/roosterjs-editor-dom/test/list/VListTest.ts
Apply list style using the ListStyleMetadata object 
Part of the refactor Auto Format series: 
[Refactor list triggers](https://github.com/microsoft/roosterjs/pull/1025)
[Refactor Apply List Style](https://github.com/microsoft/roosterjs/pull/1026)
[AutoBulletList and AutoNumberingList](https://github.com/microsoft/roosterjs/pull/1028)
[Trigger list with Hyphen](https://github.com/microsoft/roosterjs/pull/1029)
> [Part 2] Refactor Auto format - Refactor Apply List Style

- demo/scripts/controls/MainPane.scss
- demo/scripts/controls/sidePane/formatState/FormatStatePane.tsx
- demo/scripts/controls/theme/theme.scss
1. Fix the style of link in title bar for dark mode
Before: 
After:
2. Remove "isEdge" from demo site
> Fix dark mode style for demo site

- tools/buildTools/dts.js
If we export a react type from a file, we may see something like:
`import * as React from 'react';`
Our dts.js will use a regex to match and replace the keyword "React" to something else. So we need to replace the character "*" to be "\*" to make it work in a regex. Also replace some other characters for regex such as ".", "[", "\\", ...
> Fix dts.js to be compatible for react export

- packages-ui/roosterjs-react/lib/emoji/components/EmojiNavBar.tsx
- packages-ui/roosterjs-react/lib/emoji/components/EmojiPane.tsx
- packages-ui/roosterjs-react/lib/emoji/plugin/createEmojiPlugin.ts
1. Fix emoji navigation tab focus
2. Show the callout quick picker callout, only after quick picker render
3. Dismiss callout after keydown or inserted emoji
> [Rooster-react]: Emoji plugin fixes

- packages/roosterjs-editor-core/lib/coreApi/triggerEvent.ts
- packages/roosterjs-editor-types/lib/event/BeforeCutCopyEvent.ts
- packages/roosterjs-editor-types/lib/event/BeforeDisposeEvent.ts
- packages/roosterjs-editor-types/lib/event/BeforePasteEvent.ts
- packages/roosterjs-editor-types/lib/event/BeforeSetContentEvent.ts
- packages/roosterjs-editor-types/lib/event/ContentChangedEvent.ts
- packages/roosterjs-editor-types/lib/event/EditImageEvent.ts
- packages/roosterjs-editor-types/lib/event/EditorReadyEvent.ts
- packages/roosterjs-editor-types/lib/event/EntityOperationEvent.ts
- packages/roosterjs-editor-types/lib/event/ExtractContentWithDomEvent.ts
- packages/roosterjs-editor-types/lib/event/PendingFormatStateChangedEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginDomEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEvent.ts
- packages/roosterjs-editor-types/lib/event/ShadowEditEvent.ts
- packages/roosterjs-editor-types/lib/event/ZoomChangedEvent.ts
- packages/roosterjs-editor-types/lib/event/index.ts
When people wants to use CompatiblePluginEventType in their plugin code like:
```ts
onPluginEvent(e) {
if (e.eventType == CompatiblePluginEventType.KeyDown) { ... }
}
```
They got compile error since our PluginEvent is not using CompatiblePluginEventType as the type value now. So we need to add it.
To make all other API works, such as IEditor.triggerPluginEvent, I need to create separate event types, for example:
```ts
interface ContentChangedEvent {
type: PluginEventType.ContentChanged;
...
}
interface CompatibleContentChangedEvent {
type: CompatiblePluginEventType.ContentChanged;
...
}
```
They are actually same type so we can use any one of them
> Fix #1062 PluginEvent should support CompatiblePluginEventType

- packages/roosterjs-editor-core/lib/coreApi/selectTable.ts
The while loop in ensureUniqueId caused mistake generating id. If we do ``getElement`` before ``cont++``, we will get **2** if id0 is used, while **1** should be the right one.
> Fix(#1073): Order in ensureUniqueId

- packages/roosterjs-editor-core/lib/editor/Editor.ts
In a previous change (#1044 ) we added the format api name that was executed to the EditorApi Interfaces, but did not modify the editor api itself, so the editorApi Invoked was not being provided to the ContentChanged event.
In this PR we add the parameter added to the EditorApi interface to the editor API
> Modify the editor.addUndoSnapshot to add formatApiName to the request

- demo/scripts/utils/trustedHTMLHandler.ts
By default the trustHTMLHandler function of demo site is using DOMPurify and it will remove blob:// and other unknown protocols. This causes some issue when copy/paste content in MacOS. So let's set ALLOW_UNKNOWN_PROTOCOLS to true to allow those protocols.
This will only impact demo site, no impact to roosterjs dev code.
> Allow unknown protocol in demo site

- packages/roosterjs-editor-dom/lib/edit/adjustInsertPosition.ts
In some scenarios when adjusting the Position that was created based on a document fragment, the element property of the Position is going to be null. So, adding a null check to prevent code to crash
> Add null check in AdjustInsertPosition

- packages/roosterjs-editor-api/lib/format/toggleBullet.ts
- packages/roosterjs-editor-api/lib/format/toggleNumbering.ts
- packages/roosterjs-editor-api/lib/utils/toggleListType.ts
- packages/roosterjs-editor-plugins/lib/plugins/AutoFormat/AutoFormat.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
Change autoFormat parameter to apiOverrideName, with this parameter the user can change the formatApiName of the toggleListType Api.
> Customize api name

- packages/roosterjs-editor-dom/lib/contentTraverser/SelectionBlockScoper.ts
We saw weird bug report from SelectionBlockScoper before (https://github.com/microsoft/roosterjs/issues/1045) which hard to repro. I added some debugging info and made a fix in https://github.com/microsoft/roosterjs/pull/1046. It seems after that fix the issue is gone. So we can safely remove the debugging info from SelectionBlockScoper now.
> Fix #1090 Remove debug info from SelectionBlockScoper .ts

- packages/roosterjs-editor-dom/lib/table/VTable.ts
After Deleting rows or columns, see if the table is empty. If so, set cells to null.
> Fix(#1103): Delete the whole table if the table is empty after deletion

- package.json
- packages-ui/roosterjs-react/lib/emoji/plugin/createEmojiPlugin.ts
- tools/build.js
- tools/buildTools/buildMjs.js
- tools/buildTools/generateTargetWindow.js
This change adds the buildmjs step which builds the esmodule version of rooster and puts the output in lib-mjs.
> Add buildmjs to export esmodules under lib-mjs

- packages/roosterjs-editor-core/lib/corePlugins/TypeInContainerPlugin.ts
#1071 Replace highlighted text not working
From what I can tell, this is caused by iOS has different executing order of async call (and very likely related to CPU speed).
We have a call to editor.runAsync() which is using window.requestAnimationFrame(). On desktop browser, the callback of runAsync() will be called after current execution flow and event is handled by browser. But in iOS Safari (on higher speed CPU), it seems the callback is called before event is handled by browser.
So the fix here is to set a longer time delay for mobile device to make sure current event is handled by browser first, then let the callback handle it.
Using async call to handle event is a very tricky way and can somehow cause problems. So we should consider removing it as a long term goal. Opened #1128 to …
> Fix #1071 Replace highlighted text not working

- packages/roosterjs-editor-dom/lib/utils/normalizeRect.ts
A ClientRect of all 0 is possible. i.e. chrome returns a ClientRect of 0 when the cursor is on an empty p.
Currently we check that the sum of all the properties of the Rect are more than 0, but There are scenarios where the sum of all the properties is negative and still is a valid Rect
Changing the validation to verify that all the properties are not 0.
> Modify the Check in normalizeRect

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
**Describe the bug**
When resizing a big table where the top of the table is not visible, the Table Editors are getting disposed on the middle of the edit.
**Code change**
When the TableEditors are editing prevent the dispose function to be called
**Before**
**After**
> Stop Table Resizer disposal while editing

- karma.conf.js
- package.json
- packages/roosterjs-editor-dom/test/DomTestHelper.ts
From #1121, I have switched to use Chrome as default test browser. However, I realized that there are more than 100 test cases are marked as for Firefox only. So that this causes our coverage reduced. 
In this change I'll enable both Chrome and Firefox for test code coverage. With this change our code coverage is increased from 78.16% to 79.4%
> Run test coverage for both browsers

- package.json
- packages/roosterjs-editor-types-compatible/package.json
- packages/roosterjs-editor-types/package.json
- tools/buildTools/normalize.js
- yarn.lock
#1145 
- Bump version to 8.28.1:
- Use caret version dependency between packages
- Remove an unused dependency "@types/dom-inputevent"
> 8.28.1 Stop using pinned version

- packages/roosterjs-content-model/lib/domToModel/creators/createBr.ts
- packages/roosterjs-content-model/lib/domToModel/processors/brProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/containerProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/getProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/singleElementProcessor.ts
- packages/roosterjs-content-model/lib/formatHandlers/table/tableMetadataFormatHandler.ts
- packages/roosterjs-content-model/lib/formatHandlers/utils/createMetadataFormatHandler.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleSegment.ts
- packages/roosterjs-content-model/lib/publicTypes/enum/SegmentType.ts
- packages/roosterjs-content-model/lib/publicTypes/index.ts
- packages/roosterjs-content-model/lib/publicTypes/segment/ContentModelBr.ts
- packages/roosterjs-content-model/lib/publicTypes/segment/ContentModelSegment.ts
- packages/roosterjs-content-model/test/domToModel/creators/creatorsTest.ts
- packages/roosterjs-content-model/test/domToModel/processors/brProcessorTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleSegmentTest.ts
#1093 
1. Support BR segment
2. Create a comment format handler for Metadata
3. Split out "processElement" from containerProcesser.ts to be singleElementProcessor, used for processing an element itself and its child nodes, while containerProcess process child nodes only,
These are preparation steps for table format api.
> Content Model: Support BR segment

- packages/roosterjs-editor-api/lib/table/insertTable.ts
- packages/roosterjs-editor-api/test/table/insertTableTest.ts
- packages/roosterjs-editor-dom/lib/utils/setColor.ts
https://github.com/microsoft/roosterjs/issues/1159
When the format contains background color and we insert a table, the table is wrapped by a span with the background color style. When pasting text inside of the table, the pasted content gets formatted to have the same background color as the span wrapping the table.
Code Change:
Remove background color when inserting a table, so the issue stops happening
> Remove bgColor on insert table

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages-ui/roosterjs-react/lib/contextMenu/menus/createImageEditMenuProvider.tsx
- packages-ui/roosterjs-react/lib/contextMenu/types/ContextMenuItem.ts
- packages-ui/roosterjs-react/lib/contextMenu/utils/createContextMenuProvider.ts
- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-dom/lib/clipboard/extractClipboardItems.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/editInfoUtils/applyChange.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
- packages/roosterjs-editor-types/lib/interface/ExtractClipboardEventOption.ts
- packages/roosterjs-editor-types/lib/interface/ImageEditOptions.ts
1. Graduate the following featrues:
- ExperimentalFeatures.PasteWithLinkPreview,
- ExperimentalFeatures.SingleDirectionResize,
- ExperimentalFeatures.ImageRotate,
- ExperimentalFeatures.ImageCrop,
2. Add parameter to ImageEdit plugin to still allow disable image side resize/crop/rotate functionalities
> Graduate some features

- packages-ui/roosterjs-react/lib/common/utils/renderReactComponent.ts
- packages-ui/roosterjs-react/lib/contextMenu/plugin/createContextMenuPlugin.tsx
- packages-ui/roosterjs-react/lib/emoji/components/showEmojiCallout.tsx
- packages-ui/roosterjs-react/lib/inputDialog/utils/showInputDialog.tsx
- packages-ui/roosterjs-react/lib/pasteOptions/component/showPasteOptionPane.tsx
A uiUtilities object is required for those plugins that will render a react component. Today the `<Rooster />` component will initialize uiUtilities for us. However, if editor is not rendered using `<Rooster />` component, editor creator need to manually set uiUtilites to all React plugins. In this change I add an error message to let developer understand this issue.
> Fix #1163 Provide a friendly error message when uiUtilities is not set to react plugin

- .github/workflows/build-and-deploy.yml
- .github/workflows/publish.yml
After this change, check in to master branch will not publish new npm packages. To publish new npm package, we need to integrate code into release branch and bump up version. I'll investigate if we can automatically bump up version later. For now we still need to do it manually.
> Engineering improvement: Publish from release branch only

- packages/roosterjs-editor-api/lib/format/getFormatState.ts
Modified a line to guarantee multiline is always boolean and calls are not made if endingBlock is null.
> Fix for case where endingBlock is null

- packages/roosterjs-editor-dom/lib/edit/adjustInsertPosition.ts
If the editor does not contain any element when inserting a table, an infinite loop happens, add a check before entering the loop to avoid this issue
> Fix infinite loop when inserting a table and editor does not contain any element.

- tools/tsconfig.doc.json
Since we have set version to be "0.0.0" in master branch, we also need to hide version from the reference doc to avoid it to be "0.0.0"
> Temporarily hide version from doc

- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-core/lib/corePlugins/NormalizeTablePlugin.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
Fix #1189 
Add an experimental feature to move `<LI style="display:block">... </LI>` into previous list item and change tag to DIV when export HTML.
> Fix #1189 list item not showing correctly in Win32 Outlook

- packages/roosterjs-content-model/package.json
Allow publishing roosterjs-content-model@0.0.1-dev.0 to npm
> Publish the first version of content model

- .github/workflows/build-and-deploy.yml
- .github/workflows/build-and-test.yml
- .github/workflows/publish.yml
- README.md
It seems there's something changed recently to fluentui packages that causes roosterjs fail to build. Let's try fix it by using yarn instead of npm
> try fix build

- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/ribbonButtons/contentModel/ContentModelRibbon.tsx
- demo/scripts/controls/ribbonButtons/contentModel/setTableHeaderButton.ts
- demo/scripts/controls/sidePane/formatState/FormatStatePane.tsx
- packages/roosterjs-content-model/lib/modelApi/table/applyTableFormat.ts
- packages/roosterjs-content-model/lib/modelApi/table/splitTableCellHorizontally.ts
- packages/roosterjs-content-model/lib/modelApi/table/splitTableCellVertically.ts
- packages/roosterjs-content-model/lib/publicApi/table/editTable.ts
- packages/roosterjs-content-model/lib/publicApi/table/formatTable.ts
- packages/roosterjs-content-model/lib/publicApi/table/setTableCellShade.ts
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/table/tableFormatInfo.ts
- packages/roosterjs-editor-types/lib/interface/FormatState.ts
1. Add "tableHasHeader" and "tableFormat" to ElementBasedFormatState and FormatState to easily get table format
2. Export getTableFormatInfo funtion from roosterjs-editor-dom
1. Improve applyTableFormat() to get prepared for text color adjustment
2. Fix bug in split table cell API that can cause table size changed incorrectly
1. Create a dedicate component for ContentModel ribbon in demo site
2. Add a toggle table header button
3. Show table header state in format state pane
#1093
> Content Model Table API improvement

- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
Fix range selection for table selection. 
When table is selected, the table must be used to create the range added to the selection.
> Fix copy/cut safari

- packages/roosterjs-content-model/package.json
I realize that OWA doesn't allow tagged version now, so change content model version to 0.0.1
> Change content model version to 0.0.1

- packages/roosterjs-content-model/lib/modelApi/table/normalizeTable.ts
- packages/roosterjs-content-model/test/modelApi/table/normalizeTableTest.ts
When merge table cells, we should keep the merged cell has the same size with before, especially when whole column/row are merged.
> Fix merge table cell behavior for ContentModel

- packages-ui/roosterjs-react/lib/contextMenu/menus/createImageEditMenuProvider.tsx
Steps to repro:
1. Paste an image
2. Right click
3. "Add alternate text"
Current:
Fix:
> Demo: Fix typo in Add alt text prompt

- packages/roosterjs-editor-plugins/lib/plugins/Watermark/Watermark.ts
As requested by https://github.com/microsoft/roosterjs/issues/1079, there's no easy way to query for watermark elements without reverse-engineering Rooster a little. 
Given that the current class name (`_EId_WATERMARK_WRAPPER`) is also used for the entity system, overriding is not an option. As such, an optional extra class can be added to these entities specifically. This is done when constructing the Watermark plugin by adding a `string` as a third parameter.
> Allow setting custom classname to Watermark entities for easy querying

- demo/scripts/controls/contentModel/components/model/ContentModelTableView.tsx
- package.json
- packages/roosterjs-content-model/lib/formatHandlers/table/tableMetadataFormatHandler.ts
- packages/roosterjs-content-model/lib/modelApi/table/applyTableFormat.ts
- packages/roosterjs-content-model/lib/modelApi/table/normalizeTable.ts
- packages/roosterjs-content-model/package.json
- packages/roosterjs-content-model/test/modelApi/table/normalizeTableTest.ts
- packages/roosterjs-editor-dom/lib/table/tableFormatInfo.ts
1. Table metadata validation requires "keepCellShade" exist in the format, which has been removed from content model code, so make it as optional
2. Table metadata validation only allows 0-7 for table border format, but the actual max value is TableBorderFormat.CLEAR = 8. So change it to be TableBorderFormat.CLEAR. Later we will use Min/Max value to specify valid value range
3. When both hasBandedColumns and hasBandedColumns are true, the background color is not correctly applied when use ContentModel format api. Fix related code.
4. When merge table cells, we should keep the merged cell has the same size with before, especially when whole column/row are merged.
This is not a regression fix, but just to help integrate content model faster.
> RoosterJs 8.30.1 and Content Model 0.0.2

- packages/roosterjs-editor-dom/lib/list/setBulletListMarkers.ts
- packages/roosterjs-editor-dom/test/list/setBulletListMarkersTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/utils/getAutoBulletListStyle.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/utils/getAutoBulletListStyleTest.ts
- packages/roosterjs-editor-types/lib/enum/BulletListType.ts
Both --> and -> trigger a bullet list with the →  marker, then to identify the characters that triggered the list, a new list type called DoubleLong arrow was add. Then, when the unordered list style is DoubleLongArrow, the characters that triggered the list was -->
> Add double long arrow bullet type

- packages/roosterjs-editor-dom/lib/utils/Browser.ts
Using it in Next.js with RoosterJS causes an exception when building the project
```
ReferenceError: window is not defined
at Object.<anonymous> (C:\Users\Work\RiderProjects\TVGuide\six-tv-guide\node_modules\roosterjs-editor-dom\lib\utils\Browser.js:71:1)
at Module._compile (node:internal/modules/cjs/loader:1119:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Module.load (node:internal/modules/cjs/loader:997:32)
at Module._load (node:internal/modules/cjs/loader:838:12)
at Module.require (node:internal/modules/cjs/loader:1021:19)
at require (node:internal/modules/cjs/helpers:103:18)
at Object.<anonymous> (C:\Users\Work\RiderProjects\TVGuide\six-tv-guide\node_modules\roosterjs-editor-dom\lib\utils\createElement.js:7:17)
at Module._compile …
```
> Fix "ReferenceError: window is not defined" when used with Next.js

- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-api/lib/utils/blockFormat.ts
- packages/roosterjs-editor-api/lib/utils/commitListChains.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-plugins/lib/plugins/CutPasteListChain/CutPasteListChain.ts
- packages/roosterjs-editor-plugins/test/CutPasteListChain/cutPasteListChainTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
List Chain, as an experimental feature, has been graduated for long time. So we should not keep the word "experiment" in its function name. So rename to `commitListChains`.
Still keep exporting experimentCommitListChains  for backward compatibility.
> Rename experimentCommitListChains to commitListChains

- packages/roosterjs-editor-dom/lib/list/VListItem.ts
fixing a bug where list style type was applied to inner lists even when the type was toggled
https://github.com/microsoft/roosterjs/issues/1256
> fix: toggling inner list type

- demo/scripts/controls/contentModel/components/format/FormatView.tsx
- demo/scripts/controls/contentModel/components/format/utils/FormatRenderer.ts
- demo/scripts/controls/contentModel/components/format/utils/createCheckboxFormatRenderer.tsx
- demo/scripts/controls/contentModel/components/format/utils/createColorFormatRender.tsx
- demo/scripts/controls/contentModel/components/format/utils/createDropDownFormatRenderer.tsx
- demo/scripts/controls/contentModel/components/format/utils/createTextFormatRenderer.tsx
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleBlockGroup.ts
- packages/roosterjs-content-model/test/domToModel/processors/containerProcessorTest.ts
- packages/roosterjs-editor-core/test/coreApi/selectTableTest.ts
- packages/roosterjs-editor-dom/lib/metadata/validate.ts
- packages/roosterjs-editor-types/lib/enum/BulletListType.ts
This is a preparation step of Content Model List
Improve demo site to allow content model view know that a format item value is changed by adding an onUpdate callback.
Also fix bugs:
- Handle selection in general segment: no need to set current segment for selection if the segment is a general one and it has child nodes, since the selection will be finally handled by its child nodes.
- Metadata validation need to properly handle null and undefined value
- Bullet list type need to support "Circle" type
> Content Model: improve demo site, and minor bug fixes

- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/sidePane/contentModel/ContentModelPlugin.ts
Thanks @BryanValverdeU for finding the ribbon button not working issue. It is because the related plugin was not added into editor so after a strict mode fix, there is a check for uiUtilities which has never been set so the button is not working.
Fix it by adding the plugin into editor.
> Fix content model ribbon button issue in demo site

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/utils/getAutoNumberingListStyle.ts
If the a list is already trigger, it is possible to trigger another list where it stopped,  even after a space between lists. 
Then getAutoNumberingListStyle check if the where the previous list stopped and set the correct style.
> Keep list chain even after space

- packages/roosterjs-editor-plugins/lib/plugins/Paste/wordConverter/commentsRemoval.ts
- packages/roosterjs-editor-plugins/test/paste/word/convertPastedContentFromWordTest.ts
Copied elements mso-comment-continuation, should not be removed as they contain text in some scenarios. Instead just remove the style property.
> Comment Removal, remove style attribute instead of removing whole element

- packages-ui/roosterjs-react/lib/contextMenu/menus/createImageEditMenuProvider.tsx
- packages-ui/roosterjs-react/lib/contextMenu/types/ContextMenuItem.ts
- packages-ui/roosterjs-react/lib/contextMenu/utils/createContextMenuProvider.ts
This is a regression from the strict mode change of roosterjs-react package. It has a check to context object and if it is not passed, context menu onclick handler is not triggered.
Fix by skipping checking context and allow undefined context to be passed since that is the default scenario.
> Fix context menu not working issue

- packages/roosterjs-editor-core/lib/coreApi/addUndoSnapshot.ts
- packages/roosterjs-editor-core/lib/coreApi/switchShadowEdit.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-types/lib/interface/EditorCore.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
We should always return a selectionRangeEx object. When there is no selection, we can just return it with an empty ranges[] array so that we don't need to check null for this result everywhere.
> Revert "Update getSelectionRangeEx typings to match desc"

- packages/roosterjs-content-model/lib/domToModel/processors/listProcessor.ts
- packages/roosterjs-content-model/test/domToModel/processors/containerProcessorTest.ts
- packages/roosterjs-content-model/test/domToModel/processors/listProcessorTest.ts
When two lists that belong to different container, and there is other block between them, e.g.
```html
<div><ol>...</ol></div>
<div>other block</div>
<div><ol>...</ol></div>
```
Content Model will incorrectly append the second list into the same parent of the first one. This is because after processing the OL/UL element, we didn't clean up the list parent from context, so next time when we hit another list, the previous list parent is reused. The fixed is to clean up list parent after OL/UL element is processed.
> Content Model List bug fix

- tools/buildTools/checkDependency.js
The check dependency tool in our build system has some bug that it will always check to the same files so many times. This change fix this issue to improve the building speed.
> Improve building speed

- packages-ui/roosterjs-react/lib/pasteOptions/component/showPasteOptionPane.tsx
- packages-ui/roosterjs-react/lib/pasteOptions/plugin/createPasteOptionPlugin.ts
This PR fixes a regression introduced in #1285, we never expected strings in `showPasteOptionPane` to be required.
To fix it we should either:
- Make the parameter optional and remove the check, or
- Provide localized strings when creating the pane
This PR goes with option 1, feel free to close if you think there's a better option.
> It should be OK in production since we will likely provide localized strings.
> Fix broken paste option plugin in demo app

- demo/scripts/controls/editor/ExperimentalContentModelEditor.ts
- packages/roosterjs-editor-api/lib/utils/blockFormat.ts
- packages/roosterjs-editor-api/lib/utils/execCommand.ts
- packages/roosterjs-editor-core/lib/coreApi/addUndoSnapshot.ts
- packages/roosterjs-editor-core/lib/coreApi/selectImage.ts
- packages/roosterjs-editor-core/lib/coreApi/selectTable.ts
- packages/roosterjs-editor-core/lib/coreApi/setContent.ts
- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/coreApi/selectImageTest.ts
- packages/roosterjs-editor-dom/lib/selection/setHtmlWithSelectionPath.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/tableFeaturesTest.ts
- packages/roosterjs-editor-types/lib/interface/ContentMetadata.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
- packages/roosterjs-editor-types/lib/interface/index.ts
To prepare the support for image selection in Content Model, do some refactoring for selection code. This includes:
1. Hide cursor when image selection/table selection happens
2. Support passing in SelectionRangeEx into editor.select()
3. Better support image selection/table selection when do inline format and block format
4. Better support image selection/table selection when restore selection
> Improve image selection and table selection

- packages/roosterjs-content-model/lib/modelToDom/handlers/handleSegment.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleSegmentTest.ts
- packages/roosterjs-editor-api/lib/format/changeFontSize.ts
- packages/roosterjs-editor-api/lib/format/setFontSize.ts
- packages/roosterjs-editor-core/lib/corePlugins/PendingFormatStatePlugin.ts
Repro step:
1. Type some text
2. Select all, and apply some format such as font, color
3. Add some new empty lines after the text
4. Open content model side pane, click "Create DOM tree" button
5. focus to the empty lines, type text
Expect: typed text is still in the applied format
Actual: format is lost
This is because when create DOM tree, those empty lines doesn't have a SPAN tag to hold its format, so format got lost
Fix:
Create SPAN tag for BR tag as well. So the SPAN tag can hold the format.
Also fix bugs:
1. When apply pending format, remove "content editable" attribute since we don't need it in the body, in order to make the SPAN tag clean so that it can be recognized correctly by Content Model.
2. When apply font size, no need to apply line-height format if there it was not set …
> Fix empty line bug for content model

- packages/roosterjs-content-model/lib/modelApi/common/isEmpty.ts
- packages/roosterjs-content-model/test/modelApi/common/isEmptyTest.ts
For block group, when we check if it is empty, we need to check according to its type.
For example, a General block group or a TableCell should never be treated as empty.
> Content Model: Fix the check of block group empty

- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
- packages/roosterjs-editor-types/lib/enum/Keys.ts
Fix #1356 
Add a check to Ctrl/Meta key when handle key down event with table selection. Also allow Home/End key to dismiss table selection.
> Fix a regression in TableCellSelection

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/api/resizeByPercentage.ts
When resize by percentage get the image src, so the cropped images can be resized and not reseted.
> Resize cropped image

- packages-ui/roosterjs-react/lib/ribbon/component/buttons/clearFormat.ts
Fix the behavior of clear format button in roosterjs-react, auto detect clear mode.
- If only part of a paragraph is selected, clear inline format only
- If a full paragraph or multiple paragraphs are selected, clear both inline format and block format
> Auto detect clear mode when clear format

- packages/roosterjs-editor-core/lib/corePlugins/DOMEventPlugin.ts
We have code to stop propagation for character keys. We can expand this logic for the following keys as well:
- Home
- End
- PageUp
- PageDown
- Left
- Right
- Up
- Down
Because these keys are already handled by editor, so no need to expose them to parent containers.
> Stop propagation for HOME and other keys

- karma.conf.js
Change the order of karma plugins in order to get consistent test coverage result between web page report and command line
> Change the order of karma plugins

- packages/roosterjs-content-model/lib/domToModel/processors/generalProcessor.ts
- packages/roosterjs-content-model/lib/modelApi/selection/getSelectedParagraphs.ts
- packages/roosterjs-content-model/lib/modelToDom/context/defaultContentModelHandlers.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleBlockGroup.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleBr.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleGeneralModel.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleSegment.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleText.ts
- packages/roosterjs-content-model/lib/publicTypes/context/ModelToDomSettings.ts
- packages/roosterjs-content-model/test/modelApi/selection/getSelectedParagraphsTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleBlockGroupTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleBlockTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleBrTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleEntityTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleGeneralModelTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleSegmentTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleTextTest.ts
Content Model Bug Fix  part 1. Select lines and apply list change, the next line is also impacted
This is because there is a selection marker added in the next line to indicate end of line is selected. To fix it, we check if there is only selection marker selected in the line, then remove it from selected paragraphs
Also refactor handleSegment() function to split it into separate files, and update test.
> Content Model Bug fix: part 1

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
When the list does not have metadata, return previous list style as null.
> [Hot fix] Add null check to list metadata

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-api/test/format/toggleBlockQuoteTest.ts
- packages/roosterjs-editor-core/lib/coreApi/ensureTypeInContainer.ts
- packages/roosterjs-editor-core/test/coreApi/ensureTypeInContainerTest.ts
- packages/roosterjs-editor-dom/lib/utils/createElement.ts
- packages/roosterjs-editor-dom/test/list/createVListFromRegionTest.ts
- packages/roosterjs-editor-dom/test/utils/createElementTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
- packages/roosterjs-editor-types/lib/interface/EditorCore.ts
Today, when we start editor or start typing, we will add a wrapper element if there is not to make sure always type under an element. Then if there is default format, we will apply this format to this wrapper element.
However, with content model, we will move this format from wrapper DIV element to an inner SPAN element. This causes the height of DIV changes when some default format is specified. So I'd like to change this behavior to apply format directly to a inner SPAN element instead. 
This change adds a new experimental feature to apply this behavior.
```html
<div><br></div>
```
- Before change
```html
<div style="...">test</div>
```
- After change
```html
<div><span style="...">test</span></div>
```
> Apply default format on SPAN instead of DIV

- packages/roosterjs-editor-api/lib/utils/applyInlineStyle.ts
Note that, this bug affects Safari only, it can be reproduced using the roosterjs demo and other clients too.
A typical scenario is that we want to change the font size for an empty draft, or use a different font size before typing.
To apply these changes, we create an editable span to apply pending format state. Unfortunately, for elements that are not added to the DOM tree, `HTMLElement.isContenteditable` is always `false` on Safari, for example:
```js
const span = document.createElement('span');
span.contentEditable = 'true';
// document.body.appendChild(span);
console.log(span.isContentEditable); // --> false
```
Since we already know the element is editable in `editor.triggerPluginEvent(PluginEventType.PendingFormatStateChanged`, we simply remove the check to avoid running into this …
> Fix changing font size doesn't work for empty selections

- packages/roosterjs-editor-api/test/utils/toggleListTypeTest.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/setListItemStyle.ts
- packages/roosterjs-editor-dom/test/list/VListTest.ts
With change #1380 , now we will put a `<SPAN>` tag under `<DIV>` tag as initial content and use the `<SPAN>` tag to hold format. However, this causes auto bullet loses format since it requires all child nodes inside the list have the same format (https://github.com/microsoft/roosterjs/blob/9f1e7c0544948fe5927fba501ef8daea070d3737/packages/roosterjs-editor-dom/lib/list/setListItemStyle.ts#L25). And when we do auto bullet, a `<BR>` node will be added to avoid format issue (https://github.com/microsoft/roosterjs/blob/9f1e7c0544948fe5927fba501ef8daea070d3737/packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts#L399), which will cause a different style (no style) than existing `<SPAN>`.
To fix it, add a check to node content, and ignore any node that doesn't have …
> Fix list style issue

- packages/roosterjs-content-model/lib/formatHandlers/list/listItemMetadataFormatHandler.ts
- packages/roosterjs-content-model/lib/modelApi/list/setListType.ts
- packages/roosterjs-content-model/test/modelApi/list/setListTypeTest.ts
- yarn.lock
1. When convert existing paragraph to list, no need to keep its DIV tag by setting paragraph.isImplicit = true. So when quit the list (keep press Enter key on empty list element), there will be no CSS applied to newly added DIV tag and make the layout consistent before we start a list.
e.g.: Before change, turn on a list will cause a DIV tag inside:
```html
<ol>
<li>
<div><span style="...">text</span></div>
</li>
</ol>
```
after change, DIV tag is gone:
```html
<ol>
<li>
<span style="...">text</span>
</li>
</ol>
```
2. For deep bullet list, we need to apply its list style by default to override browser's default behavior.
Browser default style tags: disc, circle, square, square, square, ...
Our behavior: disc, circle, square, disc, circle, square, ...
> Content Model: Fix two list issues

- packages/roosterjs-editor-plugins/lib/plugins/HyperLink/HyperLink.ts
- packages/roosterjs-editor-plugins/test/HyperLink/HyperLinkTest.ts
Ctrl+Clicking an anchor with the Hyperlink plugin enabled no longer opens a new tab on Firefox. Restore behavior by removing the Firefox specific code found in Hyperlink plugin and calling `window.open` always.
> Restore Ctrl+Click behavior on Firefox

- demo/scripts/controls/contentModel/components/model/ContentModelEntityView.tsx
- packages/roosterjs-content-model/lib/domToModel/processors/entityProcessor.ts
- packages/roosterjs-content-model/lib/modelApi/creators/createEntity.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleEntity.ts
- packages/roosterjs-content-model/test/modelApi/creators/creatorsTest.ts
When an entity is put under some element which has inline format, we need to apply this format to the entity when write back to make sure it has the same layout.
> Content Model: fix inline entity loses format issue

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
Every time space character is triggered, rooster checks if a list can be trigger, it caused getPreviousListItem() to be triggered and by consequence collapseToSingleNode() causing the an odd behavior after pressing space. 
To avoid that problem collapseToSingleNode() was removed and getEndNode() was used to get the previous list item. 
Before the fix:
After the fix:
> Fix cursor jump bug. 

- packages/roosterjs-editor-api/lib/utils/applyListItemWrap.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/setListItemStyle.ts
- packages/roosterjs-editor-dom/test/list/VListItemTest.ts
- packages/roosterjs-editor-dom/test/list/setListItemStyleTest.ts
Fix bug #1428 
This is because when start/end a list, we copied the text styles (font, size, color), but we didn't copy the original light mode color if editor is in dark mode. The fix is to copy them as well.
> Fix a list color issue in dark mode (#1428)

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/utils/getAutoNumberingListStyle.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/utils/getAutoNumberingListStyleTest.ts
Add proper validation to list index to avoid list being triggering by special characters. 
Ex: 1:1. was triggering list because the first character is a number and the last is a proper marker character. 
To avoid that behavior change we check if the string before the marker is number or string without number and special characters
> Valid numbering

- packages/roosterjs-content-model/lib/formatHandlers/common/datasetFormatHandler.ts
- packages/roosterjs-content-model/test/formatHandlers/common/datasetFormatHandlerTest.ts
The following dataset names should be ignored by datasetFormatHandler, because they will also be handled by textColorFormatHandler and backgroundColorFormatHandler in dark mode. If they are handled by both handlers, it is possible a new value be overwritten with old ones by the second handler.
> Content Model: Fix data set conflict between format handlers

- packages/roosterjs-content-model/lib/modelApi/table/applyTableFormat.ts
Fix VSO 180500 Table options not work.
This is caused by the new method of metadata handling in Content Model. We need to explicitly get table metadata format from table model instead of using its format object since now metadata is not part of format.
> Fix 180500 Table options not work

- packages/roosterjs-editor-dom/lib/table/cloneCellStyles.ts
- packages/roosterjs-editor-dom/lib/table/pasteTable.ts
- packages/roosterjs-editor-dom/test/table/cloneCellStylesTest.ts
- packages/roosterjs-editor-dom/test/table/pasteTableTest.ts
When paste a table within a table, also copy the cell style.
> Copy table cell styles

- packages/roosterjs-content-model/lib/domToModel/processors/entityProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/fontProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/imageProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/knownElementProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/listItemProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/listProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/tableProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/utils/stackFormat.ts
- packages/roosterjs-content-model/test/domToModel/utils/stackFormatTest.ts
- packages/roosterjs-editor-core/lib/coreApi/selectTable.ts
Consider HTML
```html
<span style="background-color: red">
line 1
<div> line 2</div>
line 3
</span>
```
It will be rendered as 
Because the background color is declared in an inline element (SPAN) so it can't be inherited by a block element (DIV). So we need to respect this behavior in Content Model, when processing a block element, need to remove the background color from segment format in context.
This also causes a problem, when doing table selection, the text inside may incorrectly get background (or people can explicitly set background color to the text), then this color will cover table selection background color. To fix it, add a css rule for all elements under selected table cells to apply the same background for selection as well.
> Fix background color issue that can go across block element (ContentModel and original)

- demo/scripts/controls/contentModel/components/format/formatPart/WordBreakFormatRenderer.ts
- demo/scripts/controls/contentModel/components/model/ContentModelTableCellView.tsx
- packages/roosterjs-content-model/lib/formatHandlers/common/wordBreakFormatHandler.ts
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/index.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelTableCellFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/format/FormatHandlerTypeMap.ts
- packages/roosterjs-content-model/lib/publicTypes/format/formatParts/WordBreakFormat.ts
- packages/roosterjs-content-model/test/formatHandlers/common/wordBreakFormatHandlerTest copy.ts
Repro:
1. insert a table
2. type some very long word in table cell
3. resize table to make the word wrap
4. recreate the doc using content model
result: word break style is lost so the table cell width changes
Fix: support word break style in table cell
> Fix #1443: Support CSS style word-break in ContentModel for table cell

- demo/scripts/controls/sidePane/apiPlayground/region/GetSelectedRegionsPane.tsx
- packages/roosterjs-editor-api/lib/format/clearFormat.ts
- packages/roosterjs-editor-api/lib/format/setAlignment.ts
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-api/lib/utils/blockWrap.ts
- packages/roosterjs-editor-api/test/format/toggleBlockQuoteTest.ts
- packages/roosterjs-editor-core/lib/coreApi/ensureTypeInContainer.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/coreApi/ensureTypeInContainerTest.ts
- packages/roosterjs-editor-dom/lib/list/createVListFromRegion.ts
- packages/roosterjs-editor-dom/lib/region/getSelectedBlockElementsInRegion.ts
- packages/roosterjs-editor-dom/lib/utils/createElement.ts
- packages/roosterjs-editor-dom/test/utils/createElementTest.ts
- packages/roosterjs-editor-types/lib/enum/KnownCreateElementDataIndex.ts
In #1380, we introduced adding Format in Span instead of DIV. 
We added an Experimental Feature but we did not use it to modify the behavior.
Since we added new enums to the repo we cannot fully revert as it would be a breaking change. 
So the fix I propose is to start using the Experimental Feature DefaultFormatInSpan to decide if we want the new behavior to add format to the block div or to the span that is nested in the div.
> Add a check for Experimental Feature DefaultFormatInSpan

- demo/scripts/controls/sidePane/apiPlayground/region/GetSelectedRegionsPane.tsx
- packages/roosterjs-editor-api/lib/format/clearFormat.ts
- packages/roosterjs-editor-api/lib/format/setAlignment.ts
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-api/lib/utils/blockWrap.ts
- packages/roosterjs-editor-api/test/format/toggleBlockQuoteTest.ts
- packages/roosterjs-editor-core/lib/coreApi/ensureTypeInContainer.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/coreApi/ensureTypeInContainerTest.ts
- packages/roosterjs-editor-dom/lib/list/createVListFromRegion.ts
- packages/roosterjs-editor-dom/lib/region/getSelectedBlockElementsInRegion.ts
- packages/roosterjs-editor-dom/lib/utils/createElement.ts
- packages/roosterjs-editor-dom/test/utils/createElementTest.ts
- packages/roosterjs-editor-types/lib/enum/KnownCreateElementDataIndex.ts
Reverts microsoft/roosterjs#1469
> Revert "Add a check for Experimental Feature DefaultFormatInSpan"

- packages/roosterjs-editor-plugins/lib/plugins/Paste/wordConverter/convertPastedContentFromWord.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/wordConverter/converterUtils.ts
- packages/roosterjs-editor-plugins/test/paste/word/convertPastedContentFromWordTest.ts
If a list from word contains a Heading, the list wont be converted correctly. To fix this, we can query the elements with h# tags in addition to the p tags.
Example of Word Content:
Before Change
After
> Fix Paste issue from Word

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
If the image top is bigger than the editor scroll container, use clip-path css property to cut the top to avoid overlay the content above. 
**Before:**
**After:**
> Keep image wrapper under scroll container. 

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
When the image is selected it is cloned and this clone is added to the editing wrapper. Then it is necessary to remove the id in the cloned image, so the addUniqueId function do not change the original image id. 
Before: 
After:
> Remove id from cloned image

- demo/scripts/controls/editor/ExperimentalContentModelEditor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/knownElementProcessor.ts
- packages/roosterjs-content-model/lib/index.ts
- packages/roosterjs-content-model/lib/modelApi/common/isEmpty.ts
- packages/roosterjs-content-model/lib/modelApi/common/normalizeContentModel.ts
- packages/roosterjs-content-model/lib/modelApi/common/wrapBlock.ts
- packages/roosterjs-content-model/lib/modelApi/table/getSelectedCells.ts
- packages/roosterjs-content-model/lib/publicApi/contentModelToDom.ts
- packages/roosterjs-content-model/lib/publicApi/domToContentModel.ts
- packages/roosterjs-content-model/lib/publicApi/selection/hasSelectionInBlock.ts
- packages/roosterjs-content-model/lib/publicTypes/block/ContentModelDivider.ts
- packages/roosterjs-content-model/lib/publicTypes/group/ContentModelTableCell.ts
- packages/roosterjs-content-model/lib/publicTypes/segment/ContentModelSegmentBase.ts
- packages/roosterjs-content-model/lib/publicTypes/selection/Selectable.ts
- packages/roosterjs-content-model/test/domToModel/processors/knownElementProcessorTest.ts
- packages/roosterjs-content-model/test/modelApi/common/isEmptyTest.ts
- packages/roosterjs-content-model/test/modelApi/common/normalizeContentModelTest.ts
- packages/roosterjs-content-model/test/publicApi/selection/hasSelectionInBlockTest.ts
To improve existing selection API in content model, we first do some change to existing API
- Add an interface `Selectable`
- Modify existing interfaces to consume Selectable
- Other minor refactors
> Content Model Selection API step 1: Improve existing code

- packages/roosterjs-editor-core/lib/corePlugins/ImageSelection.ts
Bug: if ImageEditPlugin and TableCellSelection are disable, image selection does work properly. 
After an image is selected, is not possible unselect it. 
Fix: verify if a element was click and if the a image is selected, then if the condition is true, select the element selected.
> Fix for image selection

- packages-ui/roosterjs-react/lib/ribbon/component/buttons/insertTable.tsx
To fix #1509 , explicitly add CSS for box-sizing to avoid global CSS style break the UI
> Fix #1509: Make insert table pane better shown when there is global CSS for box-sizing

- demo/scripts/controls/contentModel/components/format/BlockFormatView.tsx
- demo/scripts/controls/contentModel/components/model/ContentModelDividerView.scss
- demo/scripts/controls/contentModel/components/model/ContentModelDividerView.tsx
- demo/scripts/controls/contentModel/components/model/ContentModelQuoteView.tsx
- demo/scripts/controls/sidePane/contentModel/ContentModelPanePlugin.ts
- packages/roosterjs-content-model/lib/domToModel/processors/hrProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/knownElementProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/quoteProcessor.ts
- packages/roosterjs-content-model/lib/formatHandlers/common/borderFormatHandler.ts
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/index.ts
- packages/roosterjs-content-model/lib/modelApi/block/toggleModelBlockQuote.ts
- packages/roosterjs-content-model/lib/modelApi/creators/createQuote.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleDivider.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleQuote.ts
- packages/roosterjs-content-model/lib/publicApi/block/toggleBlockQuote.ts
- packages/roosterjs-content-model/lib/publicTypes/block/ContentModelDivider.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelBlockFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelDividerFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelFormatMap.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelQuoteFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/group/ContentModelQuote.ts
- packages/roosterjs-content-model/test/domToModel/processors/hrProcessorTest.ts
- packages/roosterjs-content-model/test/domToModel/processors/knownElementProcessorTest.ts
- packages/roosterjs-content-model/test/formatHandlers/common/borderFormatHandlerTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleDividerTest.ts
Support the following CSS styles for HR block:
- display
- width, height, ...
Move `BorderFormat` from `ContentModelQuoteFormat` to `ContentModelBlockFormat`, and remove `ContentModelQuoteFormat`.
Improve the handling of divider in `knownElementProcessor`, add handling for border and padding to make Content Model more like original content.
For DIV-based divider, if there is also requirement, we can support it later.
> ContentModel: Improve Divider

- packages/roosterjs-content-model/lib/publicApi/segment/setBackgroundColor.ts
- packages/roosterjs-content-model/lib/publicApi/segment/setTextColor.ts
- packages/roosterjs-content-model/test/publicApi/segment/setBackgroundColorTest.ts
- packages/roosterjs-content-model/test/publicApi/segment/setTextColorTest.ts
Allow passing null as color value and remove existing color to implement "no color" functionality.
> Content Model: Support "no color" when set color

- demo/index.html
- demo/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
- index.html
It seems the unpkg site for fluentui is pretty unstable. So let's use cdnjs instead.
This will only impact demo site.
> Load fluent ui from cdnjs for demo site

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/editInfoUtils/applyChange.ts
When apply changes to a image that was resized, do not set maxWidth to initial.
> remove new max-width

- packages-ui/roosterjs-react/lib/ribbon/component/buttons/code.ts
- packages/roosterjs-content-model/lib/modelApi/common/retrieveModelFormatState.ts
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-types/lib/interface/FormatState.ts
Support isCode in FormatState.
This change doesn't include the format state change for Content Model. It will be covered later.
> Fix #1532: Support isCode in FormatState

- demo/scripts/controls/contentModel/components/model/ContentModelListItemView.tsx
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/modelApi/block/setModelIndentation.ts
- packages/roosterjs-content-model/lib/modelApi/list/setListType.ts
- packages/roosterjs-content-model/lib/publicApi/block/setDirection.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelListItemLevelFormat.ts
- packages/roosterjs-content-model/test/modelApi/block/setModelIndentationTest.ts
- packages/roosterjs-content-model/test/modelApi/list/setListTypeTest.ts
- packages/roosterjs-content-model/test/publicApi/block/setDirectionTest.ts
#1529 
Carry direction format when set list type
#1530 
Only set one side margin when indent, and swap margin and padding when change direction
187095: The blank space of a line will also be highlighted when bulleting or numbering the highlighted lines
When convert paragraph to list, only carry fontFamily, fontSize and textColor to the list so background color won't be impacted.
> Fix #1529 #1530 and 187095

- packages/roosterjs-content-model/lib/publicApi/link/adjustLinkSelection.ts
- packages/roosterjs-content-model/test/publicApi/link/adjustLinkSelectionTest.ts
When adjust selection for link, if selection is collapsed, try to expand it to select a whole word.
> Content Model: Adjust selection for link to select a word

- packages/roosterjs-content-model/lib/domToModel/processors/reducedModelChildProcessor.ts
- packages/roosterjs-content-model/lib/modelApi/common/retrieveModelFormatState.ts
- packages/roosterjs-content-model/test/domToModel/processors/reducedModelChildProcessorTest.ts
- packages/roosterjs-content-model/test/modelApi/common/retrieveModelFormatStateTest.ts
Bug: when there is segment under a selected table cell, existing code can't retrieve table format info correctly.
1. We always need to remember the first table context when retrieve format, so that we can compare the selected table cell index later
2. When compare table cell index, if current table cell index is the same with previous one, we need to keep running because there may be more selections in other table cell, so we can't stop the loop.
This causes the result of "canMergeTableCell" in FormatState may not be accurate.
Fix dev code and add test case as well.
> Content Model: Fix table format

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
If a trigger character is added at the beginning of the sentence, trigger the list. 
This change should verify if the 4 first characters of a text is equal to a trigger character.
> Fix list trigger before a paragraph

- packages/roosterjs-content-model/lib/modelToDom/handlers/handleImage.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleImageTest.ts
Outlook can't show resized image correctly if it doesn't have "width" and "height" property. So we need to add them when regenerate content from Content Model.
> Content Model: Fix image size for outlook

- packages/roosterjs-content-model/lib/domToModel/processors/quoteProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/processors/tableProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/utils/stackFormat.ts
- packages/roosterjs-content-model/lib/modelApi/creators/createTable.ts
- packages/roosterjs-content-model/test/domToModel/processors/quoteProcessorTest.ts
- packages/roosterjs-content-model/test/domToModel/processors/tableProcessorTest.ts
When align a table to center using a DIV around:
```html
<div align="center">
<table><tr><td>test</td></tr></table>
</div>
```
Content Model need to remember those inheritable block formats such as textAlign when process table so that the table can be centered. Similarly for Quote.
In this PR we handle the following block formats to inherit them:
- BackgroundColorFormat
- DirectionFormat
- LineHeightFormat
- WhiteSpaceFormat
Known issue: Background color from outer DIV can't be correctly handled. We can handle it later when need.
Test HTML:
```html
<div align=center style="background-color:red;line-height:2;white-space:pre" dir=rtl><blockquote style="border-left: 3px solid rgb(200, 200, 200); border-top-color: rgb(200, 200, 200); border-right-color: rgb(200, 200, 200); …
```
> Content Model: Support align table to center

- packages/roosterjs-editor-dom/lib/utils/getIntersectedRect.ts
Change `getIntersectedRect` to also filter `additionalRects ` to avoid undefined values.
> Add filter to client rects

- packages/roosterjs-content-model/lib/formatHandlers/block/whiteSpaceFormatHandler.ts
- packages/roosterjs-content-model/test/formatHandlers/block/whiteSpaceFormatHandlerTest.ts
I found that "style: white-space: pre" is not well-handled by CTS. So let's use `<PRE>` tag instead.
> Content Model: Fix PRE tag

- packages/roosterjs-content-model/lib/publicApi/image/insertImage.ts
- packages/roosterjs-content-model/test/publicApi/image/insertImageTest.ts
- packages/roosterjs-editor-api/lib/format/insertImage.ts
Support insert image with src using insertImage API in content model, to match the original API's behavior.
> Content Model: Support insert image with src

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Rotator.ts
For some editing operations, the rotate handle are not rendered. Then we need to check if they exist, before we update them.
> Check if there is rotate  handle, before update the rotate handles

- packages/roosterjs-editor-core/lib/corePlugins/PendingFormatStatePlugin.ts
https://bugzilla.mozilla.org/show_bug.cgi?id=1813591
In the pending format code (non-ContentModel), when we apply pending format we put a format SPAN into doc and select before and end of the SPAN to allow the input event replace the SPAN content. This works well in Chrome but not for Firefox. So we change to start at Begin and End of the SPAN to fix the issue.
> Fix a pending format issue in firefox

- demo/scripts/utils/trustedHTMLHandler.ts
- packages/roosterjs-content-model/lib/domToModel/processors/entityProcessor.ts
- packages/roosterjs-content-model/test/domToModel/processors/entityProcessorTest.ts
In a recent change (https://github.com/microsoft/roosterjs/pull/1567) I added default segment format when create content model. However this change will also apply format to block entities so it breaks the "keep root level entity" behavior. That means:
1. Insert a root level block entity
2. Regenerate document using Content Model
Expect: Entity node is not touched during content regeneration
Actual: A SPAN tag is created around the entity node so the node is moved
To fix it, we need to avoid applying default segment format to block entity.
Add test case to protect this behavior.
> Content Model: Keep root level entity when format with Content Model

- packages/roosterjs-content-model/lib/modelApi/common/mergeModel.ts
- packages/roosterjs-content-model/lib/modelApi/table/normalizeTable.ts
- packages/roosterjs-content-model/lib/publicApi/table/insertTable.ts
- packages/roosterjs-content-model/test/modelApi/common/mergeModelTest.ts
- packages/roosterjs-content-model/test/modelApi/table/normalizeTableTest.ts
When insert table, the new table should carry over current segment format.
> Content Model: Preserve segment format when insert table

- demo/scripts/controls/sidePane/editorOptions/ContentEditFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/tableFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/tableFeaturesTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
- packages/roosterjs-editor-types/lib/interface/ContentEditFeatureSettings.ts
If the whole table is selected, delete the table if backspaced was pressed.
> Delete table with backspace, if whole table is selected.

- demo/scripts/controls/sidePane/snapshot/SnapshotPane.tsx
- packages/roosterjs-editor-core/lib/coreApi/addUndoSnapshot.ts
- packages/roosterjs-editor-core/lib/coreApi/restoreUndoSnapshot.ts
- packages/roosterjs-editor-core/lib/corePlugins/UndoPlugin.ts
- packages/roosterjs-editor-core/lib/editor/DarkColorHandlerImpl.ts
- packages/roosterjs-editor-core/test/coreApi/addUndoSnapshotTest.ts
- packages/roosterjs-editor-core/test/corePlugins/undoPluginTest.ts
- packages/roosterjs-editor-types/lib/interface/DarkColorHandler.ts
- packages/roosterjs-editor-types/lib/interface/Snapshot.ts
Fix #1585 by adding a knownColors property in undo snapshot so that we can save the color info inside undo snapshot. Then when restore undo snapshot. also register those colors.
> Fix #1585: DarkColorHandler need to remember used color across editor session

- packages/roosterjs-content-model/lib/modelApi/common/clearModelFormat.ts
- packages/roosterjs-content-model/test/modelApi/common/clearModelFormatTest.ts
Better match Word's behavior:
1. When selection is collapsed, clear segment format for the impacted word if any
2. When selection is collapsed, clear list if any
3. When selection is not collapsed, clear segment format for selected content, but do not clear list
4. When selection covers full paragraph, or across multiple paragraphs, clear segment format for selected content, and clear block format for impacted blocks
5. Do not remove link
> Content Model: Improve clearFormat API

- packages/roosterjs-content-model/lib/formatHandlers/utils/color.ts
- packages/roosterjs-content-model/lib/modelApi/table/setTableCellBackgroundColor.ts
- packages/roosterjs-content-model/test/formatHandlers/utils/colorTest.ts
- packages/roosterjs-editor-core/lib/coreApi/transformColor.ts
- packages/roosterjs-editor-core/lib/editor/DarkColorHandlerImpl.ts
- packages/roosterjs-editor-core/test/editor/DarkColorHandlerImplTest.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/utils/parseColor.ts
- packages/roosterjs-editor-dom/lib/utils/setColor.ts
- packages/roosterjs-editor-dom/test/utils/parseColorTest.ts
- packages/roosterjs-editor-types/lib/interface/DarkColorHandler.ts
When input with IME in dark mode in Chrome, it is possible Chrome add a FONT tag and add color attribute but there is not dark color info. So when switch back to light mode, the color will be wrong.
Fix: with VariableBasedDarkColor feature enabled, we now remember all used colors. So we can query from dark color and transform it back to light color in that case.
> Fix color issue with Font tag

- packages/roosterjs-editor-dom/lib/htmlSanitizer/getAllowedValues.ts
We set "none" as default value for text-decoration, but for A tag it is not default value.
So the easiest way to fix is to remove this default value. 
(With content model this issue will be auto fixed)
> Fix #1586 text-decoration is removed from HtmlSanitizer

- packages/roosterjs-content-model/lib/modelApi/common/retrieveModelFormatState.ts
- packages/roosterjs-editor-core/lib/coreApi/getStyleBasedFormatState.ts
- packages/roosterjs-editor-types/lib/interface/FormatState.ts
Add dir and text-align info in FormatState. They will be used to calculate the alignment (left | center | right) of text at cursor. This state will be displayed to the users through the icons of the button.
> Add `dir` and `textAlign` in `FormatState`

- packages/roosterjs-content-model/lib/publicApi/block/setIndentation.ts
- packages/roosterjs-content-model/lib/publicApi/block/toggleBlockQuote.ts
- packages/roosterjs-content-model/lib/publicApi/format/applyPendingFormat.ts
- packages/roosterjs-content-model/lib/publicApi/link/insertLink.ts
- packages/roosterjs-content-model/lib/publicApi/list/toggleBullet.ts
- packages/roosterjs-content-model/lib/publicApi/list/toggleNumbering.ts
- packages/roosterjs-content-model/lib/publicApi/table/insertTable.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatParagraphWithContentModel.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatWithContentModel.ts
- packages/roosterjs-content-model/test/publicApi/block/paragraphTestCommon.ts
- packages/roosterjs-content-model/test/publicApi/link/insertLinkTest.ts
- packages/roosterjs-content-model/test/publicApi/list/toggleBulletTest.ts
- packages/roosterjs-content-model/test/publicApi/list/toggleNumberingTest.ts
- packages/roosterjs-content-model/test/publicApi/utils/formatParagraphWithContentModelTest.ts
1. Fix #879 When there is pending format, apply other format such as alignment, direction, toggle list, ... will dismiss pending format. Fix it by preserve pending format and update the position for pending format so when apply the format, it can pass the check.
2. Press SPACE may dismiss pending format because space from keyboard event is 32 but existing space in HTML document is 160. Fix it by treating them as the same character
> Content Model: Improve pending format behavior

- packages/roosterjs-content-model/lib/formatHandlers/block/whiteSpaceFormatHandler.ts
- packages/roosterjs-content-model/lib/modelToDom/optimizers/mergeNode.ts
- packages/roosterjs-content-model/test/formatHandlers/block/whiteSpaceFormatHandlerTest.ts
With a previous change (#1559), we are using PRE tag instead of CSS white-space: pre for this kind of format. However, this causes another problem that each PRE tag will have additional top and margin bottoms. So we need to set them to 0 to override this behavior.
This is not an ultimate solution, but for now let's go with this way and try to find a better solution later.
> Content Model: Improve PRE again

- packages/roosterjs-editor-core/lib/coreApi/getContent.ts
- packages/roosterjs-editor-core/lib/coreApi/setContent.ts
- packages/roosterjs-editor-core/lib/coreApi/transformColor.ts
- packages/roosterjs-editor-core/lib/editor/DarkColorHandlerImpl.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/coreApi/transformColorTest.ts
- packages/roosterjs-editor-core/test/editor/DarkColorHandlerImplTest.ts
- packages/roosterjs-editor-types/lib/interface/DarkColorHandler.ts
- packages/roosterjs-editor-types/lib/interface/EditorCore.ts
Sometimes there can be DOM element inserted programmatically into dark mode editor without light color info. In that case we can first try to match the color with known dark color to see if we can find a related light color when transform to light mode. If we can't find a color, just drop the color.
This is because:
```html
<span style="color:white">test</span>
```
The content above can be shown correctly in dark mode, but when transform to light mode, if we don't drop this color, it will become a "white on white" content. So to avoid this, we need to drop it.
> Improve dark color again

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/tableFeatures.ts
1. set a font, type something
2. insert a table using content model
3. put cursor in table, and use Up/Down/Left/Right/Tab to move cursor between cells, see the current font
The existing code always set focus to the beginning of a table, where there is no font info there since the font is declared in the SPAN inside a TD:
```html
<td>
[CURSOR]<span style="..."><br></span>
</td>
```
After this change, we will set focus into the SPAN:
```html
<td>
<span style="...">[CURSOR]<br></span>
</td>
```
So that font can show correctly.
> Show correct font when jump between table cells

- packages/roosterjs-content-model/lib/modelApi/common/normalizeContentModel.ts
`normalizeContentModel` can sometimes receive `undefined` and throw an exception when accessing `group.blocks`.
This is caused by attempting to normalize an `undefined` block.cells[r][c]:
https://github.com/microsoft/roosterjs/blob/332fc4d7296351faa4156bdf1ef95bd12b949806/packages/roosterjs-content-model/lib/modelApi/common/normalizeContentModel.ts#L22-L27
Mitigate by type asserting before normalization
Could be caused by table processor skipping an index and creating a longer than expected row, however that's just a theory
https://github.com/microsoft/roosterjs/blob/332fc4d7296351faa4156bdf1ef95bd12b949806/packages/roosterjs-content-model/lib/domToModel/processors/tableProcessor.ts#L87
> Prevent table block from passing undefined cell to normalizeContentModel

- packages/roosterjs-content-model/lib/modelApi/common/normalizeContentModel.ts
- packages/roosterjs-content-model/test/modelApi/common/normalizeContentModelTest.ts
When call normalizeContentModel and recreate DOM,
Case 1:
input: 
```html
<div>text<br></div>
```
Output:
```html
<div>text</div>
```
This is correct
Case 2:
input: 
```html
<div>text<br><br></div>
```
Output:
```html
<div>text<br></div>
```
This is wrong. Because we need the two BR at the end to make sure there is an empty line below "text".
Fix: check there must be only one BR at the end then we can remove it.
> Content Model: Fix a bug in normalization

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/inlineEntityFeatureTest.ts
**Describe the bug**
Cursor stuck in a delimiter
**To Reproduce**
Steps to reproduce the behavior:
1. Add a readonly inline entity
2. select text around it a bold it
3. place cursor before text
4. user RIGHT arrow Keys
5. Notice that you need to do Right twice because of the zws
6. Expected should only one right key press to move after entity
To fix, use ContentSearcher to get the next/previous Inline element
Before
After
> Fix Arrow Keys + Delimiter bug

- demo/scripts/controls/contentModel/components/model/ContentModelListItemView.tsx
- packages/roosterjs-content-model/lib/domToModel/processors/listItemProcessor.ts
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/formatHandlers/list/listItemThreadFormatHandler.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelListItemLevelFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/format/formatParts/ListThreadFormat.ts
- packages/roosterjs-content-model/test/domToModel/endToEndTest.ts
- packages/roosterjs-content-model/test/domToModel/processors/listItemProcessorTest.ts
- packages/roosterjs-content-model/test/formatHandlers/list/listItemThreadFormatHandlerTest.ts
1. For list item with style: display = block, we need to still treat it as a list item but mark it as dummy so we won't show list bullet/number for it and no need to add list number with 1.
2. For list with margins, need to remember the margin value.
> Content Model: Fix fidelity issue of list

- packages/roosterjs-content-model/lib/editor/ContentModelPlugin.ts
- packages/roosterjs-content-model/lib/publicApi/block/setIndentation.ts
- packages/roosterjs-content-model/lib/publicApi/block/toggleBlockQuote.ts
- packages/roosterjs-content-model/lib/publicApi/editing/handleDelete.ts
- packages/roosterjs-content-model/lib/publicApi/format/applyPendingFormat.ts
- packages/roosterjs-content-model/lib/publicApi/format/getFormatState.ts
- packages/roosterjs-content-model/lib/publicApi/format/getSegmentFormat.ts
- packages/roosterjs-content-model/lib/publicApi/list/toggleBullet.ts
- packages/roosterjs-content-model/lib/publicApi/list/toggleNumbering.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatParagraphWithContentModel.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatSegmentWithContentModel.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatWithContentModel.ts
- packages/roosterjs-content-model/test/editor/ContentModelPluginTest.ts
- packages/roosterjs-content-model/test/publicApi/editing/handleDeleteTest.ts
- packages/roosterjs-content-model/test/publicApi/format/applyPendingFormatTest.ts
- packages/roosterjs-content-model/test/publicApi/utils/formatWithContentModelTest.ts
When edit with Enter, Backspace, Delete keys, it is possible to cause the current content lose format especially when all content inside a paragraph is removed.
To finally fix this issue, we need to let Content Model handle all these editing operations and generate modified content for us.
This is just a first step. It will not change the content using Content Model, but just save a pending format so if user keep editing, the correct format will be applied.
This can't fix the case when user do Enter/Delete/Backspace then move the cursor away. That need a full fix later.
> Content Model: Fix format change while editing

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/inlineEntityFeatureTest.ts
The Content Edit was not working when cursor was between Entities, this PR fixes it,
To Repro add multiple Readonly inline entities together. Without this change we had to use Arrow Key twice, now we only need to press it once
> Improve Movement Between Delimiters

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
Sometimes the selected image can be wrapped by a element while in editing mode, such as a hyperlink. 
To avoid removed the element that wrappers the image, do not remove image parent element, but the shadow span.
> Remove shadow wrapper

- packages/roosterjs-editor-api/lib/format/insertImage.ts
Max-width is making image resize, when the image is cropped. 
Before: 
After:
> Remove max-width from insertImageWithSrc

- packages/roosterjs-content-model/lib/editor/ContentModelPlugin.ts
- packages/roosterjs-content-model/test/editor/ContentModelPluginTest.ts
We found an issue that when apply pending format using Content Model with Delete/Backspace key, there can be other part go broken. Although this is not a problem of roosterjs, but let's make a temp fix to disable such features for now. Later we can rethink about other solution that will not trigger the issue, or wait for the real issue got fixed.
> Add a parameter to enable/disable handling keyboard editing from Content Model

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
Due to TAB & Shift+Alt+L/R indenting for lists being on the same features, tab indenting was being disabled on Mac
Fix by not assigning Left/Right to such features when client is Mac
> Fix Tab/ShiftTab indenting for lists on Mac

- packages/roosterjs-editor-plugins/lib/plugins/Paste/lineMerge/handleLineMerge.ts
- packages/roosterjs-editor-plugins/test/paste/handleLineMergeTest.ts
When pasting two LI elements we are adding a BR in the last block, we should not do that. Issue instroduced here:
To repro:
1. Restore snapshot:
```
<span><ul><li><div><span>asdf</span></div></li><li><span><span>asdf&nbsp;</span></span></li></ul></span>
```
2. Copy the two LI elements
3. Paste them again.
Before:
A br element is added to the pasted content.
After
We do not add the BR element
> Do not had BR when pasting two LI blocks.

- packages/roosterjs-editor-core/lib/corePlugins/utils/inlineEntityOnPluginEvent.ts
- packages/roosterjs-editor-core/test/corePlugins/inlineEntityOnPluginEventTest.ts
Change the way we are handling Enter on a delimiter due to an issue. Instead of removing the node, just remove the class and the ZWS
Add the delimiter classes to the sanitizing option so they do not get removed on paste
> Enter on Delimiter change and Add classes to sanitizing option

- packages/roosterjs-content-model/lib/domToModel/domToContentModel.ts
- packages/roosterjs-content-model/lib/editor/ContentModelEditor.ts
- packages/roosterjs-content-model/lib/modelApi/common/clearModelFormat.ts
- packages/roosterjs-content-model/lib/modelApi/creators/createContentModelDocument.ts
- packages/roosterjs-content-model/lib/modelApi/selection/deleteSelections.ts
- packages/roosterjs-content-model/lib/publicApi/format/clearFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/context/EditorContext.ts
- packages/roosterjs-content-model/lib/publicTypes/group/ContentModelDocument.ts
- packages/roosterjs-content-model/test/editor/ContentModelEditorTest.ts
- packages/roosterjs-content-model/test/modelApi/common/clearModelFormatTest.ts
- packages/roosterjs-content-model/test/modelApi/creators/creatorsTest.ts
- packages/roosterjs-content-model/test/modelApi/selection/deleteSelectionTest.ts
- packages/roosterjs-content-model/test/publicApi/domToContentModelTest.ts
- packages/roosterjs-content-model/test/publicApi/format/clearFormatTest.ts
- packages/roosterjs-content-model/test/publicApi/segment/changeFontSizeTest.ts
Add default format to ContentModelDocument, so that in format API (e.g. clearFormat), we don't need to pass default format separately.
Later when we handle delete/backspace key, we also need this info to create new selection marker.
> Support default format in Content Model

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/inlineEntityFeatureTest.ts
When trying to move between the delimiters after using the Format API without Content Model and a delimiter element in the selection, The cursor is stuck in the ZWS so use the arrow key twice is needed.
The root cause of the issue is that we are using (Next/Previous)ElementSibling and since the delimiter element is wrapped in a new element it is returning null
To fix this intead use ContentTraverser to get the next sibling.
> Fix Movement Between Entity Delimiter issue

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableInserter.ts
The plus sign in the table handle used to add more rows and columns is misaligned with the circle.
Modified the value on line-height to rise by 2 pixels the position of the plus sign on the table handler. This was done to better center its position, especially when the handle is on a horizontal position.
Observed the handle in vertical and horizontal position.
**Before:**
**After:**
- There is still some misalignment of the overall handle top and stick.
> Fixed plus sign position on table handle

- packages/roosterjs-content-model/lib/publicApi/table/setTableCellShade.ts
- packages/roosterjs-content-model/test/publicApi/table/setTableCellShadeTest.ts
- packages/roosterjs-editor-core/lib/coreApi/selectTable.ts
1. Allow passing "null" as parameter in API `setTableCellShade` to remove existing cell shade
2. Remove alpha value of table selection since it makes the selected text looks bad:
Before change:
After change:
> Support "No Color" for table cell shade

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/test/imageEdit/imageEditTest.ts
When editing image mode we restore the original image and use the wrapper to overlay the part the was cut, then we cannot use max-width in the editing image, because it will fit the whole image inside the wrapper instead of overlay it. 
So if the selected image has max-width, when create the editing image, remove max-width. 
Before:
After:
> Remove max-width when editing image

- packages/roosterjs-editor-dom/lib/blockElements/getBlockElementAtNode.ts
If the head node or the tail node is undefined, the block element at node cannot be returned, so return null. 
Fix for error: 
Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode');
Call stack: 
at webpack://owa/packages/roosterjs-editor-dom/lib/blockElements/getBlockElementAtNode.ts:65
at webpack://owa/packages/roosterjs-editor-dom/lib/inlineElements/getInlineElementAtNode.ts:31
at webpack://owa/packages/roosterjs-editor-dom/lib/contentTraverser/BodyScoper.ts:39
at webpack://owa/packages/roosterjs-editor-dom/lib/contentTraverser/ContentTraverser.ts:146
at webpack://owa/packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts:374
at webpack://owa/packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts:337
at …
> Fix unexpected error in getBlockElementAtNode.ts

- packages-ui/roosterjs-react/lib/pasteOptions/plugin/createPasteOptionPlugin.ts
- packages-ui/roosterjs-react/lib/pasteOptions/type/PasteOptionStringKeys.ts
- packages-ui/roosterjs-react/lib/pasteOptions/utils/buttons.ts
- packages/roosterjs-editor-core/lib/coreApi/createPasteFragment.ts
- packages/roosterjs-editor-core/lib/editor/EditorBase.ts
- packages/roosterjs-editor-core/test/coreApi/createPasteFragmentTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/excelConverter/convertPastedContentFromExcel.ts
- packages/roosterjs-editor-types/lib/interface/EditorCore.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
Add the `pasteAsImage` parameter to the editor paste, so if the content has image in base64 we can paste it as image.
> Paste as image feature

- packages/roosterjs-content-model/lib/publicApi/block/toggleBlockQuote.ts
- packages/roosterjs-content-model/test/publicApi/block/toggleBlockQuoteTest.ts
With the latest changes, `toggleBlockQuote` API should accept a union of Block format and Segment format, but I forgot to change the parameter type. So fix it in this change and add a test case to make sure it accepts correct format type.
> Content Model minor fix: Change parameter type

- packages/roosterjs-editor-dom/lib/utils/createElement.ts
This seems like a bug in Chrome, it doesn't repro in Firefox.
I found that when the width of temp DIV >=4px, it won't repro.
Let's use 600px for the temp DIV width instead. I don't have a good reason for this value, just pick whatever value that can work.
> Fix #1713 Copy paste bullet list item doesn't work, copies just empty span instead of content inside.

- packages/roosterjs-editor-dom/lib/blockElements/getBlockElementAtNode.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/inlineEntityFeatureTest.ts
There is an issue with delimiter when pressing Left or Right key. Seem to be related when the Entity is inserted right below the editor div and there are no more elements.
Repro 
1. Alt + A to select all text in editor
2. Delete
3. Add new Inline readonly entity
4. Press Left or Right next to the inline entity.
5. Error is thrown.
Snapshot
```
<span class="entityDelimiterBefore">​</span><span class="_Entity _EType_ _EReadonly_1" contenteditable="false" style="display: inline-block;"><span data-hydrated-html=""><a href="asas">asd</a></span></span><span class="entityDelimiterAfter">​</span>
```
To fix, do not create the Block Traverser if the result of getBlockElementAtNode::getStartNode returns an element that is not a block
> Fix Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')

- demo/scripts/controls/ribbonButtons/contentModel/ContentModelRibbon.tsx
- demo/scripts/controls/ribbonButtons/contentModel/imageBorderRemoveButton.ts
- packages/roosterjs-content-model/lib/modelApi/image/applyImageBorderFormat.ts
- packages/roosterjs-content-model/lib/publicApi/image/setImageBorder.ts
- packages/roosterjs-content-model/test/modelApi/image/applyImageBorderFormatTest.ts
- packages/roosterjs-content-model/test/publicApi/image/setImageBorderTest.ts
For `setImageBorder` content model API, allow the second parameter (`border`) to be `null`.
If this parameter is set to null, remove all border formats set, excluding border radius.
Additionally add testing and a demo ribbon button for it.
> Allow Content Model API to remove image border

- packages/roosterjs-content-model/lib/domToModel/processors/listProcessor.ts
- packages/roosterjs-content-model/test/domToModel/processors/listProcessorTest.ts
#1684 We need to respect direction style from parent container when process List.
To fix it, clone the block format for list level and use it as initial value of list level format.
There is a known issue after this fix: #1729 LTR/RTL command won't work for OL/UL element with direction specified. We need a separate fix for this issue.
> Content Model: Fix #1684

- packages/roosterjs-content-model/lib/editor/plugins/ContentModelEditPlugin.ts
- packages/roosterjs-content-model/lib/editor/utils/handleKeyboardEventCommon.ts
- packages/roosterjs-content-model/lib/publicApi/editing/handleBackspaceKey.ts
- packages/roosterjs-content-model/lib/publicApi/editing/handleDeleteKey.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatWithContentModel.ts
- packages/roosterjs-content-model/test/editor/plugins/ContentModelEditPluginTest.ts
- packages/roosterjs-content-model/test/editor/utils/handleKeyboardEventCommonTest.ts
- packages/roosterjs-content-model/test/publicApi/editing/editingTestCommon.ts
- packages/roosterjs-content-model/test/publicApi/editing/handleBackspaceKeyTest.ts
- packages/roosterjs-content-model/test/publicApi/editing/handleDeleteKeyTest.ts
- packages/roosterjs-content-model/test/publicApi/utils/formatWithContentModelTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/HyperLink/HyperLink.ts
This is a part of #1664.
At beginning, I was planning to replace all content edit features with content model (ContentModelEditPlugin). However, I found there will be too many things to work on. Given that the main goal of this plugin for now is to take over editing behavior from browser, but not replace existing edit features, and those features are working well, I changed the plan to be:
1. When there is a keydown event, let other plugins handle first
2. After other plugins, if the default behavior of the raw event is not prevented, it means we want to rely on browser's editing behavior. So the new ContentModelEditPlugin can handle this event (for now, only handle DELETE and BACKSPACE key)
3. Later we can start to port existing edit features to Content Model one by one.
With this plan, …
> Content Model: Improve edit plugin

- packages/roosterjs-content-model/lib/domToModel/processors/hrProcessor.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleDivider.ts
- packages/roosterjs-content-model/lib/publicTypes/block/ContentModelDivider.ts
- packages/roosterjs-content-model/test/domToModel/processors/hrProcessorTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleDividerTest.ts
I'll make a series changes to improve content model fidelity.
In this change I add size property to ContentModelDivider so that if "size" is specified in HR element, it can be preserved.
> Content Model fidelity improvement 2: Support size in divider

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-content-model/lib/domToModel/domToContentModel.ts
- packages/roosterjs-content-model/lib/editor/ContentModelEditor.ts
- packages/roosterjs-content-model/lib/editor/coreApi/createEditorContext.ts
- packages/roosterjs-content-model/lib/editor/createContentModelEditorCore.ts
- packages/roosterjs-content-model/lib/modelApi/common/retrieveModelFormatState.ts
- packages/roosterjs-content-model/lib/publicTypes/ContentModelEditorCore.ts
- packages/roosterjs-content-model/lib/publicTypes/context/EditorContext.ts
- packages/roosterjs-content-model/test/editor/ContentModelEditorTest.ts
- packages/roosterjs-content-model/test/editor/coreApi/createEditorContextTest.ts
- packages/roosterjs-content-model/test/editor/createContentModelEditorCoreTest.ts
- packages/roosterjs-content-model/test/modelApi/common/retrieveModelFormatStateTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
Today when we create content model, we always read font name and font size using "getComputedStyle" from root container as root level format. This causes two problems:
1. If we load content that doesn't have font info, Content Model will always add font from root container into the content. This is not right. Content should keep its style unless user changes it.
2. When clear content from current line, format state will show font from root container (in most cases, Segoe UI) which will confuse user because when keep typing, TypeInContainerPlugin will force the new content in default format.
To fix this, we are doing:
1. Remove the code that reads format from root container
2. When retrieve format, if there is no font info (as well as color), use the format from defaultFormat instead
3. …
> Content Model: Improve default format state

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- packages/roosterjs-content-model/lib/editor/plugins/ContentModelEditPlugin.ts
- packages/roosterjs-content-model/lib/editor/plugins/ContentModelFormatPlugin.ts
- packages/roosterjs-content-model/lib/modelApi/common/isWhiteSpacePreserved.ts
- packages/roosterjs-content-model/lib/modelApi/common/normalizeContentModel.ts
- packages/roosterjs-content-model/lib/modelApi/common/normalizeParagraph.ts
- packages/roosterjs-content-model/lib/modelApi/common/normalizeSegment.ts
- packages/roosterjs-content-model/lib/modelApi/selection/deleteSelections.ts
- packages/roosterjs-content-model/test/editor/plugins/ContentModelEditPluginTest.ts
- packages/roosterjs-content-model/test/modelApi/common/isWhiteSpacePreservedTest.ts
- packages/roosterjs-content-model/test/modelApi/common/normalizeParagraphTest.ts
- packages/roosterjs-content-model/test/modelApi/common/normalizeSegmentTest.ts
- packages/roosterjs-content-model/test/modelApi/selection/deleteSelectionTest.ts
This change addresses 3 issues:
1. For content such as "a b", and backspace after "b", we should not delete the space. This is done in deleteSelections.ts by changing the space after "a" to be `&nbsp;` when delete. Similar for DELETE key case
2. For content such as "a[SPACE][SPACE]b", when put cursor right before "b", browser will leave the second space after cursor so Content Model need to recognize this space and ignore it since it isn't rendering anything. This is done by creating a new model API `normalizeParagraph` and call it from `normalizeContentModel`. There are bunch of cases of spaces need to be handled there, see comments in code for more info
3. For `&nbsp;` at then end of a segment (not the last text segment), we need to replace it to be a normal space if the second last …
> Content Model: Fix #1738 delete space issue

- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-content-model/lib/editor/ContentModelEditor.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
This PR adds a Experimental Feature to be used in the ContentModelEditor class. When enabled will use content model to insert the content in the editor
> Add a experimental feature for paste with ContentModel

- demo/scripts/controls/contentModel/components/ContentModelView.tsx
In demo site with Content Model, if hover on a model that has cached element, show a highlight border of the element in editor to indidate the hovered model:
> Demo site: Show a visible border when hover on content model in demo site

- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/sidePane/eventViewer/EventViewPane.tsx
- packages/roosterjs-content-model/lib/editor/utils/handleKeyboardEventCommon.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatWithContentModel.ts
- packages/roosterjs-content-model/test/editor/utils/handleKeyboardEventCommonTest.ts
- packages/roosterjs-editor-core/lib/corePlugins/UndoPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/undoPluginTest.ts
- packages/roosterjs-editor-types/lib/enum/PluginEventType.ts
- packages/roosterjs-editor-types/lib/event/BeforeKeyboardEditingEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEvent.ts
- packages/roosterjs-editor-types/lib/event/index.ts
When press Delete/Backspace, we will add an undo snapshot before this change take effect, so that user can undo to the state before this change. However, with existing implementation there is no chance for UndoPlugin to get snapshot before change, so we need to introduce a new event `BeforeKeyboardEditingEvent`, and fire this event before we write content model back to DOM tree.
To test it:
1. Type some content
2. Press Delete or Backspace to delete some content
3. Undo, it should go back to the state before delete.
> Content Model Edit: Improve undo

- packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts
Fix an error in Picker Plugin by adding some null checks:
```
TypeError: Cannot read properties of null (reading 'getInlineElementBefore')
roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts getInlineElementBefore 483 
roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts tryRemoveNode 443 
roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts onKeyDownEvent 192
```
> Fix TypeError: Cannot read properties of null (reading 'getInlineElementBefore')

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
Bug: resize handles cursor is not pointing the right direction after rotation operation. 
Cause: When data-x or data-y is undefined, the rotate handle cursor direction was not being calculated. 
Fix: when data-x or data-y is undefined, calculate the direction using the data existing value. 
Before: 
After:
> Fix resize handles

- packages/roosterjs-content-model/lib/editor/utils/handleKeyboardEventCommon.ts
- packages/roosterjs-content-model/lib/modelApi/common/mergeModel.ts
- packages/roosterjs-content-model/lib/modelApi/edit/deleteSelections.ts
- packages/roosterjs-content-model/lib/modelApi/edit/deleteSingleChar.ts
- packages/roosterjs-content-model/lib/modelApi/selection/deleteSelections.ts
- packages/roosterjs-content-model/lib/publicApi/editing/handleBackspaceKey.ts
- packages/roosterjs-content-model/lib/publicApi/editing/handleDeleteKey.ts
- packages/roosterjs-content-model/lib/publicApi/table/insertTable.ts
- packages/roosterjs-content-model/test/modelApi/edit/deleteSelectionTest.ts
- packages/roosterjs-content-model/test/modelApi/edit/deleteSingleCharTest.ts
- packages/roosterjs-content-model/test/publicApi/editing/handleBackspaceKeyTest.ts
- packages/roosterjs-content-model/test/publicApi/editing/handleDeleteKeyTest.ts
- packages/tsconfig.build.json
- packages/tsconfig.json
- tools/buildTools/buildDemo.js
- tools/buildTools/pack.js
- tools/tsconfig.doc.json
- webpack.config.js
Emoji can be multiple-character. So we need to detect if we need to delete all of them.
The idea comes from here https://cestoliv.com/blog/how-to-count-emojis-with-javascript/
I'm not using the ultimate fix since it doesn't work for Firefox. The remaining issue is to delete emoji such as "🇫🇷". I think the current behavior is still acceptable, so just use it.
> Content Model: Fix #1797 Delete emoji using Content Model

- packages/roosterjs-content-model/lib/modelApi/table/splitTableCellHorizontally.ts
- packages/roosterjs-content-model/lib/modelApi/table/splitTableCellVertically.ts
- packages/roosterjs-content-model/test/modelApi/table/splitTableCellHorizontallyTest.ts
- packages/roosterjs-content-model/test/modelApi/table/splitTableCellVerticallyTest.ts
When splitting a table cell that has a background colour different that the default, the new cell will now inherit the colour too. Previously, when using content model split the new cell reverted to the default colour.
Added to the dataset of any new cells the property `editingInfo: '{"bgColorOverride":true}'` to make it maintain the inherited shading.
* Create a table in Rooster
* Shade all table as a new colour
* Select one or all cells and use Split from the content model ribbon
**Before:** After the split, all new cells would not inherit the shading from its parent cell.
**After:** After the split, all new cells will inherit the shading from its parent cell.
- After the split, the new cell will still not inherit other format properties from its parent, such as font size.
> Fix split cell shading for Content Model

- packages/roosterjs-editor-plugins/lib/plugins/Paste/Paste.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/officeOnlineConverter/convertPastedContentFromOfficeOnline.ts
I have no idea why, but the symptom is, if the image has style "border:none", then it will not show correctly when resize. The resize border actually shrink into 0*0.
So the fix is to remove "border: none" when paste.
> Fix VSO 207180 Inline image pasted from Word Online disappears when you try to edit it

- packages-ui/roosterjs-react/lib/ribbon/component/Ribbon.tsx
Make `overflowButtonProps` propagate.
> Make overflowButtonProps (of Ribbon props) propagate. 

- packages-ui/roosterjs-react/lib/ribbon/component/Ribbon.tsx
Rooterjs dialog is not getting closed through "Esc" key.
> Fix dialog can't be closed through pressing esc key

- packages/roosterjs-content-model/lib/modelApi/common/mergeModel.ts
- packages/roosterjs-content-model/lib/publicApi/image/insertImage.ts
- packages/roosterjs-content-model/lib/publicApi/link/insertLink.ts
- packages/roosterjs-content-model/lib/publicApi/table/insertTable.ts
- packages/roosterjs-content-model/test/modelApi/common/mergeModelTest.ts
- packages/roosterjs-content-model/test/publicApi/image/insertImageTest.ts
- packages/roosterjs-content-model/test/publicApi/link/insertLinkTest.ts
For Content Model API `mergeModel`, adding an option `mergeCurrentFormat`. When pass to true, it will merge a combination of default format and current format into the merged model.
For example:
```ts
defaultFormat = { fontFamily: 'Arial' };
currentFormat = { fontSize: '20px', textColor: 'red' }
mergedModelFormat = { textColor: 'blue' }
```
After merge, the format will be:
```ts
{
fontFamily: 'Arial',
fontSize: '20px',
textColor: 'blue'
}
```
This is because from the source model, it already has format `textColor: blue`, so it will not be overwritten, but other formats like fontFamily, fontSize will be merged into the model segment format.
With this change, when insert image or other content, we can merge the existing format to make sure the merged model always has a format. Later we can …
> Content Model: Merge format when merge model

- packages/roosterjs-editor-core/lib/corePlugins/utils/inlineEntityOnPluginEvent.ts
- packages/roosterjs-editor-core/test/corePlugins/inlineEntityOnPluginEventTest.ts
We were removing all the Delimiters when doing BeforeCopyPaste or ExtractContentWithDOM event, but we did not check if the delimiter was actually a delimiter (textContent === ZWS && (className == DelimiterBefore || className == DelimiterAfter)).
In this PR I add a check before removing the delimiter, if it is a valid delimiter (we do the check using getDelimiterFromNode function) remove it, else just remove the classname and the ZWS
> Fix Incorrect Content removal inside of delimiter.

- packages-ui/roosterjs-react/lib/contextMenu/menus/createImageEditMenuProvider.tsx
- packages-ui/roosterjs-react/lib/contextMenu/types/ContextMenuItemStringKeys.ts
- packages/roosterjs-editor-core/lib/corePlugins/ImageSelection.ts
- packages/roosterjs-editor-core/test/corePlugins/imageSelectionTest.ts
Instead of select the image when right click, use Context Menu event to select the image when right click a image. 
Add copy/cut options to the image context menu to test image selection. 
**Before:**
**After:**
> Support context menu in ImageSelection Plugin

- packages/roosterjs-content-model/lib/editor/coreApi/createPasteModel.ts
- packages/roosterjs-content-model/lib/editor/plugins/PastePlugin/WacComponents/handleWacComponentsPaste.ts
- packages/roosterjs-content-model/test/editor/coreApi/createPasteModelTest.ts
We need to disable the caching of elements on paste, otherwise in some scenarios, for example for table cells, we do not apply the correct format if the editor is in dark mode.
This PR adds the disableCacheElements to the domToContentModel when invoking createPasteModel
> Always disable cache element on paste

- demo/scripts/controls/sidePane/apiPlayground/insertEntity/InsertEntityPane.tsx
- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/entityPluginTest.ts
- packages/roosterjs-editor-core/test/editor/newEditorTest.ts
- packages/roosterjs-editor-types/lib/corePluginState/EntityPluginState.ts
- packages/roosterjs-editor-types/lib/enum/EntityOperation.ts
- packages/roosterjs-editor-types/lib/event/EntityOperationEvent.ts
Shadow DOM entity has never been really used, and it still has a lot of problem. So let's remove the support of Shadow DOM entity. In the future we can consider add this feature back using Content Model.
> Remove the support of ShadowDOM entity

- karma.conf.js
With the previous fix for nodejs 17+, I see the official build fails at running code coverage with the error:
This need a fix to the webpack config of karma test, so fix it here.
> Fix config for test:coverage

- demo/scripts/controls/ribbonButtons/contentModel/imageBoxShadowButton.ts
- packages/roosterjs-content-model/lib/publicApi/image/setImageBoxShadow.ts
- packages/roosterjs-content-model/test/publicApi/image/setImageBoxShadowTest.ts
Allows the addition of margins to image shadows in order for them to be shown as shadows are not taken into account for box container.
> Allow picture shadows to set a custom margin around image

- packages/roosterjs-content-model/lib/editor/createContentModelEditorCore.ts
- packages/roosterjs-content-model/lib/publicApi/utils/formatWithContentModel.ts
- packages/roosterjs-content-model/lib/publicApi/utils/paste.ts
- packages/roosterjs-content-model/test/publicApi/utils/pasteTest.ts
When using paste we need to return the clipboardData when invoking addUndoSnapshot. That way when other plugins handle the ContentChangeEvent. They can also use the data property. 
This is used for example in the PasteOption Plugin.
This PR adds this functionality to the new paste public API
+ Minor fix in promoteContentModelEditorCore since we were always adding the ContentModelCopyPastePlugin
> Add data to the ContentChange event when pasting

- packages/roosterjs-content-model/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts
- packages/roosterjs-content-model/lib/editor/createContentModelEditorCore.ts
Update ContentModelCopyPaste Core Plugin state initialization, so we receive the state object instead of creating it inside of the plugin.
> Update ContentModelCopyPaste Core Plugin state initialization.

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableInserter.ts
If some cells are merged vertically, the row inserter will not be accessible for any intersecting row except the first one. The issue is not present for horizontally merged cells and the column inserter.
Example table:
<div><table ><tbody><tr><td><br/></td><td><br/></td><td rowspan="3"><br/></td></tr><tr><td><br/></td><td><br/></td></tr><tr><td><br/></td><td><br/></td></tr></tbody></table>
A new condition was added to check if the cursor's position is more than the left margin of the cell, plus other minor optimisations. This was done because the previous two conditions (less than right and less than bottom) were being met by any vertically merged cell in the wrong row, so the inserter would not appear for the intersecting rows of that cell, except the first one.
Using the above table as …
> Fix table inserter for merged vertical cells

- package.json
- packages-ui/roosterjs-react/package.json
- packages/roosterjs-color-utils/package.json
- packages/roosterjs-content-model/package.json
- packages/roosterjs-editor-api/package.json
- packages/roosterjs-editor-core/package.json
- packages/roosterjs-editor-dom/package.json
- packages/roosterjs-editor-plugins/package.json
- packages/roosterjs/package.json
- packages/tsconfig.build.json
- packages/tsconfig.json
- tools/buildTools/buildDemo.js
- tools/buildTools/pack.js
- tools/tsconfig.doc.json
- webpack.config.js
- yarn.lock
Use typescript compile option `importHelpers` to avoid generating duplicated functions such as __assign.
This need to take tslib as dependency so that those common functions can be found by `require` when compile.
> use Import Helpers to reduce pack size

- packages/roosterjs-content-model/lib/editor/coreApi/setContentModel.ts
- packages/roosterjs-content-model/lib/editor/coreApi/switchShadowEdit.ts
- packages/roosterjs-content-model/test/editor/coreApi/switchShadowEditTest.ts
In #1814, I added an async call to set focus again if thte focus was not correctly set. 
Now I found that the original issue was actually caused by incorrectly switching shadow edit. If editor is not in shadow edit state, no need to turn it off again. So fix the shadow edit code and partially revert the original change
> Content Model: Fix focus issue again

- packages/roosterjs-content-model/lib/editor/plugins/ContentModelEditPlugin.ts
In #1870 I changed behavior to allow browser handle delete/backspace event when cursor is in middle of text node. 
But for Ctrl+Backspace/Delete, we'd better still let Content Model to handle it.
And if there is only 1 character before/after cursor when backspace/delete, we'd better also let content model handle it to keep the DOM structure.
> Content Model: Patch for #1870

- packages/roosterjs-editor-core/lib/coreApi/transformColor.ts
We removed the code about onExternalContentTransform from #1767 . However it is actually still used by some customer, so we need to add it back.
> Add back onExternalContentTransform

- packages/roosterjs-content-model/lib/publicApi/block/setHeaderLevel.ts
- packages/roosterjs-content-model/test/publicApi/block/setHeaderLevelTest.ts
Problem: Turn on Content Model toolbar, select some text, turn on header, then turn off. The text should return to the format before turn on header, but it keeps the header's format.
Root cause: In a previous change we changed the code of how paragraph decorator works. Now the segment does not need to copy the format of decorator. 
Fix: Remove the code to copy format to segment, and delete exiting font size and weight style from segment if any in order to match header's style.
> Content Model: Fix header level issue

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableInserter.ts
In dark mode the table inserter `+` sign is not visible, so fixing that in this PR:
before
after
> Fix Table Inserter Color in Dark Mode

- packages/roosterjs-content-model/lib/editor/ContentModelEditor.ts
- packages/roosterjs-content-model/lib/modelApi/common/mergeModel.ts
- packages/roosterjs-content-model/lib/publicApi/image/insertImage.ts
- packages/roosterjs-content-model/lib/publicApi/link/insertLink.ts
- packages/roosterjs-content-model/lib/publicApi/table/insertTable.ts
- packages/roosterjs-content-model/lib/publicApi/utils/paste.ts
- packages/roosterjs-content-model/test/modelApi/common/mergeModelTest.ts
When pasting and also using the Paste Option to merge the styles we need to apply the current format to the pasted content.
Following Word's behavior, if the pasted content contains text that is Bold/italic/Underline that format is going to be preserved.
Source: https://support.microsoft.com/en-us/office/control-the-formatting-when-you-paste-text-20156a41-520e-48a6-8680-fb9ce15bf3d6?ui=en-us&rs=en-us&ad=us
With this change we add a new option to mergeModel so we can set the format to the pasted model.
Also, modified the current ContentModelEditor so we can use the 'Merge Format' Option from RoosterUI
> Merge Format when pasting.

- packages/roosterjs-content-model/lib/editor/coreApi/switchShadowEdit.ts
- packages/roosterjs-content-model/test/editor/coreApi/switchShadowEditTest.ts
Fix https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/209223/?triage=true
This is caused by a conflict between original and content model switchShadowEdit() API. In original API, each time we apply a format during shadow edit, we will rebuild the content from the cloned fragment, then content model API will write the content again, which makes content be rewritten twice.
After this change, for ContentModelEditor we will only reformat once everytime and use the cached model so no need to reformat the whole doc.
The side effect of this change is that old format API won't work with ContentModelEditor now.
> Content Model: Fix #209223

- packages/roosterjs-content-model/lib/domToModel/processors/pProcessor.ts
- packages/roosterjs-content-model/test/domToModel/endToEndTest.ts
Content Model Fidelity: margin-left in P is not correctly processed #1887
I forget to wrap the parser code of P tag with block format handling, that causes the block format bleeding outside so margin left (or right) will be accumulated.
To fixed, add block format handler property when call stackFormat().
> Content Model: Fix #1887

- packages/roosterjs-content-model/lib/domToModel/processors/knownElementProcessor.ts
- packages/roosterjs-content-model/lib/domToModel/utils/stackFormat.ts
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelFormatMap.ts
- packages/roosterjs-content-model/test/domToModel/endToEndTest.ts
- packages/roosterjs-content-model/test/domToModel/utils/stackFormatTest.ts
Content Model Fidelity: SPAN style under A #1888
Today Content Model code does not distinguish the following two cases:
Case 1:
```html
<a href="#"><span style="color:red">test</span></a>
```
Case 2:
```html
<span style="color:red"><a href="#">test</a></span>
```
But actually the rendering results are different. Because text color won't go across `<A>` tag, in the second case the text will not render in red. However, our code treat both of them to be case 2.
To fix this, we need to apply the text color into format object of link decorator as well so that when we write back, the text color can be applied to `<A>` tag, so the text will be rendered in specified color.
Before rerender: 
After rerender, before fix:
After rerender, after fix:
Now the only problem is the underline color is …
> Content Model: Fix #1888

- demo/scripts/controls/sidePane/snapshot/SnapshotPane.tsx
- demo/scripts/controls/sidePane/snapshot/SnapshotPlugin.tsx
Previously in #1805, I added a change to demo site to always trigger ContentChangedEvent when restore an undo snapshot from site pane. This causes a side effect that all further undo snapshots are gone when double click a snapshot form Undo Snapshot pane.
To adjust it, I'm adding a parameter to `onRestoreSnapshot` callback of `SnapshotPlugin`, we now only trigger this event when we click "Restore snapshot" button. If double click from the existing snapshot list.
> Demo site minor improvement

- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
When an entity is gone, we should always trigger EntityOperationEvent, no matter what triggers the event. So remove the check for change source.
> Always trigger EntityOperation when entity is removed

- packages/roosterjs-content-model/lib/editor/plugins/PastePlugin/ContentModelPastePlugin.ts
- packages/roosterjs-content-model/lib/editor/plugins/PastePlugin/utils/deprecatedColorParser.ts
- packages/roosterjs-content-model/test/editor/plugins/ContentModelPastePluginTest.ts
Remove the parsers that removed the deprecated colors and instead use a chainSanitizerCallback to remove all these styles. Since not only format for segments can have these color values.
> Remove deprecated colors for all elements on paste

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/editInfoUtils/applyChange.ts
When we crop a resized image and then restore it to the full image (no cropping),  the image edit info object of the edited image will be the same  as original, except for the image size dimensions, then when apply changes happens, it cannot detect the image was cropped and the it will not restore the size before crop.  Therefore, to fix this issue, we changed the parameter `wasResized` to `wasResizedOrCropped`, then when `wasResizedOrCropped` is true, the image size dimensions are adjusted. 
**Bug:**
**Expected:**
> Always set new size dimensions when crop an image

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/editInfoUtils/applyChange.ts
Only set image width and height to the image in editing mode. After editing the image do set width and height style properties. This properties were removed, because it was causing an issue in Outlook after the image has been sent. 
**Bug:** 
**Expected:**
> Remove width and height after quit editing

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
Fix Uncaught TypeError: Cannot read properties of undefined (reading 'cells')
Callstack
webpack://.../roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts cells 117
webpack://.../roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts onMouseMove 125
webpack://.../roosterjs-editor-core/lib/coreApi/attachDomEvent.ts beforeDispatch 27
Do not create the TableEditor if the table do not have rows. to prevent the issue. Also add a null check on the line that cause the regression
> Uncaught TypeError: Cannot read properties of undefined (reading 'cells')

- demo/scripts/controls/sidePane/apiPlayground/vlist/VListPane.tsx
- demo/scripts/controls/sidePane/editorOptions/ContentModelExperimentalFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-api/lib/format/setOrderedListNumbering.ts
- packages/roosterjs-editor-api/lib/utils/commitListChains.ts
- packages/roosterjs-editor-api/lib/utils/toggleListType.ts
- packages/roosterjs-editor-dom/lib/list/VList.ts
- packages/roosterjs-editor-dom/lib/list/VListChain.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
Per Yammer team's requirement, we want to allow disabling list chain functionality. So add an experimental feature to support this.
When list chain is allowed (default):
When list chain is disabled:
> Add an experimental feature to allow disabling list chain functionality

- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/utils/color.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/utils/colorTest.ts
When no DarkColorHandler is passed in, we should still allow write back color with the original color value.
This will be used by initial rewrite with Content Model.
> Content Model: Allow set color without color handler

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/tableFeatures.ts
`defaultDisabled: !Browser.isChrome && !Browser.isSafari` is added to exclude FireFox, but it also disable this feature for other webkit-based iOS/macOS clients
> Remove disable controls to other webkit-based iOS/macOS clients

- packages-content-model/roosterjs-content-model-editor/test/publicApi/format/getFormatStateTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/test/imageEdit/imageEditTest.ts
- packages/roosterjs-editor-plugins/test/paste/e2e/pasteFromWordTest.ts
Add font-size in image wrapper, so it do not inherit font-size. 
To test:
1. Apply a big font-size to a image
2. The image rotate handler icon will move out the rotate button 
After fix:
> Add font-size in image wrapper.

- packages/roosterjs-editor-dom/lib/table/isWholeTableSelected.ts
- packages/roosterjs-editor-dom/test/table/isWholeTableSelectedTest.ts
This seems to repro when there is an empty table, without cells and rows `<table></table>`, 
webpack://.../packages/roosterjs-editor-dom/lib/table/isWholeTableSelected.ts 16
webpack://.../packages/roosterjs-editor-core/lib/coreApi/selectTable.ts 85
webpack://.../packages/roosterjs-editor-core/lib/coreApi/selectTable.ts 209
webpack://.../packages/roosterjs-editor-core/lib/coreApi/selectTable.ts 49
webpack://.../packages/roosterjs-editor-core/lib/coreApi/select.ts 73
webpack://.../packages/roosterjs-editor-core/lib/editor/EditorBase.ts 434
webpack://.../packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts 114
webpack://.../packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts 74
> Fix  COMPONENT ERROR: e.cells[o] is undefined

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/utils/paste.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/utils/pasteTest.ts
If we set the position when sanitizing the pasted content, some styles are removed in the HTMLSanitizer.
We do not need to continue using the HTMLSanitizer implementation to inherit the styles as Content model does the job of inheriting and merging the styles
Before
After
> Do not inherit styles in Sanitizer, and instead let Content Model Handle the style merge

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/edit/deleteSteps/deleteCollapsedSelection.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/edit/deleteSelectionTest.ts
When delete, we need to make sure we are under a non-implicit paragraph, so that after delete, we can call normalizeContentModel() which will make sure current paragraph has at least one segment to hold the segment format.
> Fix #1953 Content Model: Delete the only character loses format under implicit paragraph

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
Fix [Bug 216972](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/216972): [Table] Inserted row/column disappear after make changes for the table
We need to trigger a ContentChangedEvent after each time editing a table. Currently the API `addUndoSnapshot` won't trigger the event if the first parameter is null/undefined. This could be a bug, but to reduce the risk, I just pass in a valid function to make it work.
> Fix 216972

- packages-content-model/roosterjs-content-model-editor/lib/editor/plugins/ContentModelEditPlugin.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/plugins/ContentModelEditPluginTest.ts
Fix [Bug 216431](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/216431): [Table] Aligning whole table not working correctly
When do table selection, we need to handle SelectionChangedEvent so that content model knows we need to update the cached model.
> Fix 216431

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/list/setListType.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/list/setListTypeTest.ts
[Bug 215585](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/215585): [Format]Switching between bullets and numbering need to click the button twice
When switch list type, we check if all selected blocks are already in the expected list type, then turn the list off, otherwise we need to turn on list for those blocks that are not in expected type. However there is a code bug to check existing list type.
1. If a block is really in the expected list type, count it in
2. If a block is a non-empty paragraph, we should treat as not in that type
3. If a block is empty, but it is the only selected block, we should still treat it as not in that type, and will switch the list type on
4. If a block is empty and there are also other selected blocks, ignore this block.
After the fix, …
> Fix 215585

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/editInfoUtils/applyChange.ts
- packages/roosterjs-editor-plugins/test/imageEdit/imageEditTest.ts
- packages/roosterjs-editor-plugins/test/imageEdit/resizeByPercentageTest.ts
When an image is resized, the width/height width attributes are changed to set the new size. If the image already has width/height style properties, those properties must be removed, because they have high priority and it will prevent the image from resize.
> Remove style width/height

- karma.conf.js
After upgrade `karma-webpack` to 5.0.0, the source map is broken. Now the source code number is not correctly mapped.
Fix this by a workaround config from https://github.com/ryanclark/karma-webpack/issues/493#issuecomment-780411348
> Fix line number of test cases

- demo/scripts/controls/sidePane/editorOptions/ContentModelEditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ContentModelOptionsPane.tsx
- demo/scripts/controls/sidePane/editorOptions/ContentModelPlugins.tsx
- demo/scripts/controls/sidePane/editorOptions/codes/ContentModelButtonsCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/ContentModelEditorCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/PluginsCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/SimplePluginCode.ts
1. Enable experimental feature `ContentModelPaste` in demo site by default
2. Enable content model paste plugin in demo site by default
3. Provide a button in side pane to generate code for Content Model editor into CodePen
4. Remove CutPasteListChain from Content Model demo site since we don't need it for Content Model
> Demo site improvement for Content Model

- demo/scripts/controls/ContentModelEditorMainPane.tsx
- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/contentModel/plugins/ContentModelFormatPainterPlugin.ts
- demo/scripts/controls/ribbonButtons/contentModel/formatPainterButton.ts
In demo site:
1. Rename `FormatPainterPlugin` to `ContentModelFormatPainterPlugin` since it is only used by Content Model editor
2. Remove `FormatPainterPlugin` from original MainPane since it is not used.
> Demo site improvement: Rename FormatPainterPlugin

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/editInfoUtils/applyChange.ts
After resizing an image, we set width and height values, then to preserve the aspect ratio of the resize image, the max-width of the image is removed.
> Remove max-width

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/image/changeImage.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/image/changeImageTest.ts
Remove alternative image text of image when change image of an image element.
> Remove image alternative text when change picture

- package.json
- packages-content-model/roosterjs-content-model-dom/package.json
- packages-content-model/roosterjs-content-model-editor/package.json
- packages-content-model/roosterjs-content-model-types/package.json
- packages-content-model/roosterjs-content-model/package.json
- packages-ui/roosterjs-react/package.json
- packages/roosterjs-editor-api/package.json
- packages/roosterjs-editor-core/package.json
- packages/roosterjs-editor-dom/package.json
- packages/roosterjs-editor-plugins/package.json
- packages/roosterjs-editor-types-compatible/package.json
- packages/roosterjs-editor-types/package.json
- packages/roosterjs/package.json
- tools/buildTools/common.js
- tools/buildTools/dts.js
- tools/buildTools/normalize.js
- webpack.config.js
- yarn.lock
Yarn workspaces: https://classic.yarnpkg.com/lang/en/docs/workspaces/
With this change, we can now easily navigate code between files, and imported types from other package won't show error in code editor:
Before change
After change
When navigate code across packages:
Before change, cannot navigate if build is not performed. And after a build, it will navigate to .d.ts file;
After change, navigate works before and after build, and navigate to correct .ts file
> Engineering improve: Use Yarn workspace

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/image/insertImage.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/image/insertImageTest.ts
[Bug 139624](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/139624): [Mail] The inline picture will be also highlighted if text is highlighted
Fix by setting an empty background color for new image so after merge the existing background color will be removed
> Content Model Fix 139624

- packages-content-model/roosterjs-content-model-editor/lib/editor/ContentModelEditor.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/getSelectionRangeEx.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/setContentModel.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/switchShadowEdit.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/createContentModelEditorCore.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/segment/setBackgroundColor.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/utils/formatSegmentWithContentModel.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/ContentModelEditorCore.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/createContentModelEditorCoreTest.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/segment/setBackgroundColorTest.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/utils/formatSegmentWithContentModelTest.ts
[Bug 144958](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/144958): Highlighting text should remove selection
Add a callback to function `formatSegmentWithContentModel` to allow do some additional work after format, so that we can change the selection to be after the last selected segment.
In order to be able to restore selection before applying format, I added a new cachedRangeEx in `ContentModelEditorCore` to store selection range after model is restored, and if this cached range exists, `getSelectionRangeEx` will return this range directly. This solves the issue that after restore a content model we got incorrect range issue.
Before:
After:
> Content Model Fix 144958

- packages-content-model/roosterjs-content-model-dom/lib/domToModel/processors/delimiterProcessor.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/processors/delimiterProcessorTest.ts
- packages-content-model/roosterjs-content-model-types/lib/context/DomToModelSettings.ts
[Bug 214383](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/214383): [Mail]Cannot delete multiple beautiful links at once
The root cause is selection is not correctly generated in content model when start position is inside a entity delimiter. Because we didn't go into the delimiter SPAN to check selection. To fix it, we just need to recursively loop all child nodes of an entity delimiter to find selection position. Then all entities will be correctly selected.
> Content Model Fix 214383

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/collectSelections.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/table/editTable.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/table/formatTable.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/table/setTableCellShade.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/selection/collectSelectionsTest.ts
[Bug 189344](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/189344): [Table]The cursor goes to the end after delete table
After edit a table, we need to check if the table still has focus. If not, set a focus, or replace the table with an empty paragraph if table is already empty
> Content Model Fix 189344

- karma.conf.js
In an earlier change I enabled compile option `downlevelIteration` in order to use spread operator on string so that we can detect emoji in string. But the recent change to test code missed this option. So add it to test webpack config as well.
> Try fix test code build issue

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/CellResizer.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableInserter.ts
Implementation of #1984 for the Table Inserters and Cell resizers
The Table Inserter and cell resizers are currently inserted on the document, thus putting them on a different container to the table they belong to. This creates issues in some scenarios such as when a dialog is created above the document with a high z-index. They also have a fixed position which causes issues in some scrolling scenarios, where they stayed fixed in place instead of moving or disappearing.
Changed the insertion point of where the resizers and inserters are located, inserted to where the Plugin specifies, if no selector is given it will default to the previous behaviour. The intent is for the selector to contain the editor. Additionally fixed a scenario here cells next to merged vertical cells could not be …
> Fix Cell resizers and Table Inserters

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/constants/constants.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Cropper.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Resizer.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Rotator.ts
- packages/roosterjs-editor-plugins/test/imageEdit/rotatorTest.ts
Update visibility rotate handle and side resize handles according to image size. 
If image has width/height less than the sum of 3 resize handles diameters plus 2 resize margins, hide side resize handles and rotator handle.
> Fix rotator and side resize handles visibility

- demo/scripts/controls/sidePane/apiPlayground/ApiPlaygroundPane.tsx
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/utils/paste.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/utils/pasteTest.ts
- packages/roosterjs-editor-core/lib/coreApi/createPasteFragment.ts
- packages/roosterjs-editor-core/test/coreApi/createPasteFragmentTest.ts
When pasting as plain text, there is no need to let plugins handle the event.
So just skip trigger event function in this scenario.
> Skip Trigger plugin event on plain text paste

- packages/roosterjs-editor-core/lib/corePlugins/DOMEventPlugin.ts
- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/entityPluginTest.ts
[Bug 218869](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/218869): [Beautiful link]Dragging beautiful link will duplicate it
In my change #1898 I disabled dragging an entity.
But actually there are other cases that readonly content can exist without an entity. So we should disable dragging readonly element instead.
> Fix 218869: Do not allow dragging on readonly content

- packages-content-model/roosterjs-content-model-dom/lib/domToModel/context/defaultProcessors.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/segment/fontSizeFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/utils/parseValueWithUnit.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/segment/fontSizeFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/utils/parseValueWithUnitTest.ts
[Bug 194024](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/194024): [Format]The display of the font size for the pasted text from web doesn't correct
[Bug 220289](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/220289): Process "font-size:medium" in ContentModel
For `font-size` style, today we just read its value and pass to Content Model format. But some relative format such as ex, %, smaller and some predefined size like `small`, `medium`, `large` need to be translated to an absolute value so that the format state code can recognize it.
> Content Model: Fix 194024 and 220289

- demo/scripts/controls/contentModel/components/format/formatPart/FloatFormatRenderer.ts
- demo/scripts/controls/contentModel/components/model/ContentModelImageView.tsx
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/common/floatFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/defaultFormatHandlers.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/common/floatFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-types/lib/format/ContentModelImageFormat.ts
- packages-content-model/roosterjs-content-model-types/lib/format/FormatHandlerTypeMap.ts
- packages-content-model/roosterjs-content-model-types/lib/format/formatParts/FloatFormat.ts
- packages-content-model/roosterjs-content-model-types/lib/index.ts
[Bug 221290](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/221290): Re: Monarch Feedback 🎁 - My email signature is affected if I change formatting in my email body.
Need to support `float` in Content Model image
> Content Model: Fix 221290 Support float for image

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/common/mergeModel.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/common/mergeModelTest.ts
#2015
We should not add the table format when splitting the paragraph, as this can lead to border styles to be incorrectly applied to the splitted pagraph
Before
After
> MergeModel, do not inherit the styles of table when splitting the param

- demo/scripts/controls/ribbonButtons/contentModel/insertLinkButton.ts
- packages-ui/roosterjs-react/lib/index.ts
- packages-ui/roosterjs-react/lib/inputDialog/index.ts
- packages-ui/roosterjs-react/lib/inputDialog/type/DialogItem.ts
- packages-ui/roosterjs-react/lib/inputDialog/utils/showInputDialog.tsx
I found that all dialogs from Content Model demo site are broken, because we split roosterjs-react code out of demo site code, and the input dialog function is not exported, so during runtime the input dialog function can't be found.
Fix: export input dialog function and related types from roosterjs-react.
> Demo site: Fix insert link button in Content Model ribbon

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/constants/constants.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Cropper.ts
Fixing a regression introduce by https://github.com/microsoft/roosterjs/pull/2000. 
We have only four handles in crop, ne, nw, se, sw. Therefore, we need to remove ", so it do not create the middle handles. 
**Before:** 
**After:**
> Fix crop regression. 

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
When flip a cropped picture, the cloned image was not being cropped in the right position. Therefore, the wrapper should resized before flip the parent of cloned image cloned image, so the visible part of image match the part that was cropped. 
**Before:** 
**After:**
> Fix flipped image

- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/keyUtils/handleKeyDownEvent.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/keyUtils/handleKeyUpEvent.ts
Fix of #2023 
Writing on a selected cell, or group of cells, does not replace the content of the first cell as expected.
On the TableCellSelection plugin, the handle key down event used to end the cell selection when typing. Now it makes only the first cell selected and creates a new selection of all its children.
1. Create a table
2. Select one or more cells
3. Type something
**Before:** The place where the cursor was placed is where the typed text will be inserted.
**After:** The first cell in the selection, top left one, will be cleared and the typed text will be inserted.
- Keys like the function keys and Caps Lock will end cell selections. This behaviour exits before this change. However for the case of typing, after pressing said keys the full contents of the cell will still be …
> Replace first cell content if input while on cell selection

- packages-content-model/roosterjs-content-model-dom/lib/domToModel/processors/tableProcessor.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/processors/tableProcessorTest.ts
[Bug 219312](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/219312):  When deleting a column in a table, header of the table is also get deleted.
This is actually a content fidelity issue. Mini repro:
```html
<table style="box-sizing: border-box; width: 28.75px; height: 24.6667px;"><tbody style="background-color:red"><tr><td style="box-sizing: border-box; width: 24.75px; height: 20.6667px;">test</td></tr></tbody></table>
```
When rewrite with content model, the background color is gone.
Fix: Parse and respect the background color from THEAD/TBODY/TFOOT if any.
Related test case aded
> Content Model: Fix 219312

- packages-content-model/roosterjs-content-model-editor/lib/editor/plugins/PastePlugin/ContentModelPastePlugin.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/utils/paste.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/plugins/ContentModelPastePluginTest.ts
Instead of adding the additional parsers when we need to merge the current format in paste.ts do it in ContentModelPastePlugin.
> Simplify the domToModel call in `paste.ts`

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/entity/insertEntity.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/entity/insertEntityTest.ts
In the new `insertEntity` API, we should always respect `focusAfterEntity` setting, no matter it is inline or block entity
> Content Model: Improve insertEntity

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/test/imageEdit/imageEditTest.ts
When select a image that is editing mode, it will change the editor selection to the shadow root. Therefore, when mouse up, check if the image is editing mode, then reselect it.
> Keep image selection when editing

- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/handlers/handleEntity.ts
- packages-content-model/roosterjs-content-model-dom/test/modelToDom/handlers/handleEntityTest.ts
Repro:
Use snapshot 
```html
<div>aaa<span class="entityDelimiterBefore">​</span><span style="display: inline-block;" class="_Entity _EType_bbb _EId_bbb_4 _EReadonly_1" contenteditable="false"><span><b>bbb</b></span></span><span class="entityDelimiterAfter">​</span></div><div><br></div><div><br></div><div><span style="letter-spacing: normal; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); font-weight: 400;">a</span><span class="entityDelimiterBefore">​</span><span style="font-family:&quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, …
```
> Content Model: Fix selection of entity

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/common/retrieveModelFormatState.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/common/retrieveModelFormatStateTest.ts
Today when we call `getFormatState` from content model, it always returns whatever size we have in the code.
We'd better returns a consitent result in unit, e.g., always in pt.
So that UI layer can just directly parse the number and show current selected font size.
> Content Model: Always return size in pt when getFormatState

- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/switchShadowEdit.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/coreApi/switchShadowEditTest.ts
In new `switchShadowEdit` API for Content Model, we missed the call to trigger ShadowEdit related event. So add them back.
> Content Model: trigger ShadowEdit events

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/table/normalizeTable.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/normalizeTableTest.ts
When insert new table, currently we are adding an implicit paragraph in each table cell, it will be represented as a BR tag. So if user keep typing and press ENTER, it will keep using BR as line splitter. This causes some problem such as applying bullet list causes only one list item is created.
To fix this, we add a solid (not implicit) paragraph in each table cell.
> Content Model: Add solid paragraph in new table cell

- packages-content-model/roosterjs-content-model-dom/lib/index.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelApi/common/applySegmentFormatToElement.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/utils/paste.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/utils/pasteTest.ts
When copy some plain text and paste, since the copied text does not have any format, the paste result will totally rely on current DOM structure. Sometimes it will also paste without any format, especially when current format is specified on segment but not on paragraph.
In this change, I'm adding a format container SPAN and apply current format (font family, font size, text color, background color, letter spacing, line height) onto this SPAN and put all copied content under it. When merge, this format will take effect if it s not overwritten by other formats.
> Content Model: Paste plain text applies current format

- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/switchShadowEdit.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/coreApi/switchShadowEditTest.ts
From change https://github.com/microsoft/roosterjs/pull/2053, a EnteredShadowEdit event will be triggered when start shadow edit. However, table selection and image selection plugin will reselect current selection when receive this event, that causes cached content model to be cleared. So shadow edit format won't work since it can't get cached content model.
To fix it, we need to first get content model, then trigger event, and set cached model at last.
> Content Model: Fix a regression of shadow edit

- demo/scripts/controls/sidePane/editorOptions/ContentModelEditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ContentModelExperimentalFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-api/lib/utils/toggleListType.ts
- packages/roosterjs-editor-api/test/utils/toggleListTypeTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/listFeaturesTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
Deprecated the `AutoFormatList` experimental feature and always enable `AutoFormatList` feature. Also always the disable `AutoBullet` content edit feature.
> [FHL] Deprecate AutoFormatList experimental feature

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/segment/changeFontSize.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/segment/setFontSize.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/segment/changeFontSizeTest.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/segment/setFontSizeTest.ts
When reduce font size, if there is already font size specified on paragraph, the line space will keep no change.
To fix this, we can move the font size from paragraph down to each child segments.
Before:
After:
> Content Model: Fix line space when reduce font size

- packages-content-model/roosterjs-content-model-dom/lib/config/defaultContentModelFormatMap.ts
- packages-content-model/roosterjs-content-model-dom/lib/config/defaultHTMLStyleMap.ts
- packages-content-model/roosterjs-content-model-dom/lib/domToModel/context/createDomToModelContext.ts
- packages-content-model/roosterjs-content-model-dom/lib/domToModel/utils/getDefaultStyle.ts
- packages-content-model/roosterjs-content-model-dom/lib/index.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/context/createModelToDomContext.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/handlers/handleFormatContainer.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/utils/stackFormat.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/context/createDomToModelContextTest.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/utils/getDefaultStyleTest.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/utils/isBlockElementTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/segment/linkFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/segment/textColorFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/modelToDom/context/createModelToDomContextTest.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/block/setHeadingLevel.ts
- packages-content-model/roosterjs-content-model-types/lib/context/DomToModelOption.ts
- packages-content-model/roosterjs-content-model-types/lib/context/DomToModelSettings.ts
- packages-content-model/roosterjs-content-model-types/lib/context/ModelToDomOption.ts
- packages-content-model/roosterjs-content-model-types/lib/context/ModelToDomSettings.ts
Refactor existing Content Model Customization code
Step 0: Remove default styles from context since it is never really used.
> Content Model Customization refactor 0

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/imageEditors/Rotator.ts
- packages/roosterjs-editor-plugins/test/imageEdit/rotatorTest.ts
Consider the rotator handle center when calculate the rotator handle height. 
**Before:**
**After:**
> Fix image rotator handle height

- tools/buildTools/checkDependency.js
`checkDependency` is one of the build step. Sometimes we see build error from this step but the error message didn't provide enough info especially the source file that causes this error.
In this change I add the source file name into error message to help quickly identify the issue.
> Engineering Improvement: checkDependency

- packages-content-model/roosterjs-content-model-dom/lib/modelApi/creators/createText.ts
- packages-content-model/roosterjs-content-model-dom/test/modelApi/creators/creatorsTest.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/adjustWordSelection.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/selection/adjustWordSelectionTest.ts
The Content Model API `adjustWordSelection` can adjust the selection to a word around current cursor. However, if there is nothing to select, we should not modify the segments of paragraph.
In this change I let the function operation on some temp segments. And if finally we see word to select, update the temp segments to paragraph, otherwise just drop them.
Also improve `createText` to allow pass in decorators when create text model.
> Content Model: Improve adjustWordSelection

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableInserter.ts
When using the table inserter, the focus gets moved to before the table.
After a new insertion, the newly created row or column will be selected and the focus fill be on its first cell.
* Create a table
* Insert a new row or column using the table inserter
* Type any text
**Before:** Text will be typed before the whole table
**After:** Text will be typed on the first cell the cell selection.
> Select new row/column after insertion

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/setSelection.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/selection/setSelectionTest.ts
Content Model API `setSelection` handles selection udpate. If there is no selection parameter passed in, it should clear existing selection. There is a code bug when clear table selection. When nothing is selected, table selection should also be cleared.
> Content Model: Clear table selection fix

- demo/scripts/controls/sidePane/editorOptions/ContentModelEditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ContentModelExperimentalFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/createEditorContext.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/createContentModelEditorCore.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/ContentModelEditorCore.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/coreApi/createEditorContextTest.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/createContentModelEditorCoreTest.ts
- packages/roosterjs-editor-api/lib/format/insertEntity.ts
- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/entityPluginTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/inlineEntityFeatureTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
Graduate feature InlineEntityReadOnlyDelimiters, and remove `addDelimiterForEntity` from `EditorContext`
> Graduate feature InlineEntityReadOnlyDelimiters

- packages-content-model/roosterjs-content-model-dom/lib/domToModel/processors/childProcessor.ts
- packages-content-model/roosterjs-content-model-dom/lib/domUtils/isNodeOfType.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/list/listItemMetadataFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/contentModelToDom.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/handlers/handleGeneralModel.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/optimizers/mergeNode.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/optimizers/optimize.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/optimizers/removeUnnecessarySpan.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/utils/reuseCachedElement.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/plugins/PastePlugin/WordDesktop/processWordLists.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/utils/contentModelDomIndexer.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/editing/keyboardDelete.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/format/applyDefaultFormat.ts
In order to build a standalone editor, I'm removing dependency from Content Model to old packages.
In this change I'm removing `NodeType` from Content Model, and use a string literal type instead.
`NodeType` is only used in utility function `isNodeOfType`. Now I can use the built-in Node properties (TEXT_NODE, ...) as string literal type instead, so `NodeType` is not needed any more.
> Standalone editor: remove NodeType from Content Model

- packages/roosterjs-editor-core/lib/corePlugins/ImageSelection.ts
- packages/roosterjs-editor-core/test/corePlugins/imageSelectionTest.ts
Since shadow edit it is not changing the selection, remove the code related to reselect the image when leave and enter shadow edit.
> Image selection on shadow edit

- packages-content-model/roosterjs-content-model-editor/lib/editor/corePlugins/ContentModelCachePlugin.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/plugins/ContentModelCachePluginTest.ts
To repro, use the following snapshot in Content Model editor:
```html
<div>aaaaa</div><div>bbbbb</div>
```
Then type "1", and the press "B" button on ribbon.
Expect:
Actual:
This is because when there is an expanded selection that across paragraphs and we input to overwrite, the two paragraphs will be merged into one, but Content Model is not updated accordingly. For now we didn't handle this case in our cache update code, so the easiest fix is just clear the cache so that we can regenerate Content Model.
> Content Model: Clear cache when input in expanded selection

- demo/scripts/controls/BuildInPluginState.ts
- demo/scripts/controls/ContentModelEditorMainPane.tsx
- demo/scripts/controls/sidePane/editorOptions/ContentModelEditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ContentModelExperimentalFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/ContentModelOptionsPane.tsx
- packages-content-model/roosterjs-content-model-editor/lib/editor/ContentModelEditor.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/createContentModelEditorCore.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/setSelection.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/IContentModelEditor.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/createContentModelEditorCoreTest.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/plugins/ContentModelCopyPastePluginTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
In order to build a standalone editor, I'm removing dependency from Content Model to old packages.
In this change I'm removing the following dependencies:
- Remove experimental feature `ReusableContentModelV2` and use an editor option `cacheModel` instead standalone editor will not depend on original `ExperimentalFeatures`
- Remove dependency `ExperimentalFeatures` to `roosterjs-editor-types`
- Remove dependency `isFeatureEnabled` to `roosterjs-editor-core`
- Remove dependency `Coordinates` to `roosterjs-editor-types`
> Standalone editor: Remove dependencies ExperimentalFeatures, isFeatureEnabled, Coordinates

- packages/roosterjs-editor-core/lib/corePlugins/ImageSelection.ts
- packages/roosterjs-editor-core/test/corePlugins/imageSelectionTest.ts
When type on image selection, use the key down event trigger to insert the cursor before the image. 
Before: 
1. Select image
2. Type a
3. Type b 
4. The result is image + ba 
After: 
1. Select image
2. Type a
3. Type b 
4. The result is ab + image
> Fix type on image selection

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/editInfoUtils/applyChange.ts
- packages/roosterjs-editor-plugins/test/imageEdit/imageEditTest.ts
When editing image remove the max-height, so it the image can be resize according the wrapper size. 
Issues caused by max-height:
> Remove height max-height when editing 

- packages/roosterjs-editor-core/lib/corePlugins/ImageSelection.ts
- packages/roosterjs-editor-core/test/corePlugins/imageSelectionTest.ts
Do not handle keyboard events on image selection when `ctrlKey`, `altkey`, `shiftKey` or `metaKey` are pressed, since it can prevent the default behavior of shortcut, such as copy/ cut images.
> Fix copy/cut images

- packages-content-model/roosterjs-content-model-editor/lib/editor/utils/contentModelDomIndexer.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/utils/contentModelDomIndexerTest.ts
With advanced cache enabled in Content Model editor, when we start a table selection, table id can be modified. When that happens, we need to update cached model to reflect this change.
For now the easiest way is to clear cache and rebuild content model when new selection is table/image.
> Recreate Content Model for table and image selection

- packages/roosterjs-editor-core/lib/editor/EditorBase.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
- packages/roosterjs-editor-core/test/editor/EditorTest.ts
- packages/roosterjs-editor-types/lib/interface/EditorCore.ts
- packages/roosterjs-editor-types/lib/interface/EditorOptions.ts
When dispose editor, if any plugin throws exception from its dispose() method, we should catch it and keep going to make sure dispose is always success.
> Catch error and continue when dispose editor

- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/utils/color.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/utils/colorTest.ts
- packages-content-model/roosterjs-content-model-types/lib/context/ColorManager.ts
- packages-content-model/roosterjs-content-model-types/lib/context/EditorContext.ts
- packages-content-model/roosterjs-content-model-types/lib/index.ts
Remove the dependency to DarkColorHandler type by creating a reduced interface `ColorManager` in `roosterjs-content-model-types` package
> Standalone editor: Decouple DarkColorHandler

- packages/roosterjs-editor-core/lib/corePlugins/ImageSelection.ts
Instead of use `position.Begin` use `position.Before` to set cursor before the image when a key is pressed.
> Image Selection: Keyboard event

- demo/scripts/controls/ribbonButtons/contentModel/tableBorderApplyButton.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/table/applyTableBorderFormat.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/enum/BorderOperations.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/applyTableFormatTest.ts
- packages-content-model/roosterjs-content-model-editor/test/publicApi/table/applyTableBorderFormatTest.ts
Improve the ability to modify table borders with more operations.
* Add more Table border functions to modify and apply changes to table borders to selected cells.
Simplified the operations by having only one function to apply borders to cells. It receives an array of the borders to set, the border format, and the cell. In the case of no border, it is set to '', the attribute is eventually deleted. The functionality to modify the perimeter of the selection has also been implemented as its own function.
* Modified Demo site to Include Table Borders functionality: Left, Right, Top, Bottom, Inside, Outside, and No borders operations added.
* Added tests for Table Border related changes and new functionality.
- None
> Add Tests and more Table Borders operations

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/editing/keyboardDelete.ts
Today when user press Backspace/Delete key, we check if we should handle it using Content Model. One if the check is if there is charactor before/after the cursor, or there is other element before/after current element, we will let browser to handle it.
But there is one case, if there is an empty text node before current cursor and user press Backspace key, browser may not handle it well and may lose format. So in that case we should still let Content Model to handle the event.
e.g.
```html
<span>[] <Focus> text</span>
```
([] means an empty text node)
Here we should let Content Model to handle the backspace event since the empty text node should be ignored.
> Use Content Model to handle Delete/Backspace key in more cases

- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/setContentModel.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/switchShadowEdit.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/coreApi/switchShadowEditTest.ts
- packages-content-model/roosterjs-content-model-types/lib/context/ModelToDomOption.ts
- packages/roosterjs-editor-core/lib/coreApi/switchShadowEdit.ts
When exit shadow edit, we should not set focus into editor. This is because exiting shadow edit is most likely triggered from some UI control, and we should leave focus in the UI control, and let the UI code decide if we should set focus back to editor.
> Do not set focus when exit shadow edit

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/table/editTable.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/237735/?triage=true
After edit table, we already have code to normalize the table to make sure every cell has at least one paragraph. The problem is we need to pass in default segment format so that the segment under new paragraph can be properly formatted.
> Fix #237735

- packages-content-model/roosterjs-content-model-dom/lib/domToModel/processors/delimiterProcessor.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/processors/delimiterProcessorTest.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/236416/?triage=true
The root cause is delimiterProcessor didn't handle selection well if the start/endContainer is set to text under delimiter, then the offset won't match. And now emoji is wrapped with entity, so that if a selection range is ended right before an entity, it is not treated as end so everything after are still treated as selected.
For an entity delimiter, we actually don't need to care if selection offset matches, but just check if the selection container is contained by the delimiter element, then we can treat it as the right place, and do proper handling.
Fix by using Node.contains() to check if we should start/end the selection in a delimiter.
> Fix #236416

- packages-content-model/roosterjs-content-model-editor/lib/editor/coreApi/switchShadowEdit.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/corePlugins/ContentModelCopyPastePlugin.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/common/clearModelFormat.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/common/retrieveModelFormatState.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/edit/utils/deleteExpandedSelection.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/adjustWordSelection.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/collectSelections.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/iterateSelections.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/format/applyPendingFormat.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/common/retrieveModelFormatStateTest.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/selection/iterateSelectionsTest.ts
The Content Model API `iterateSelections` has 5 parameters today:
- path
- callback
- option
- table
- treatAllAsSelect
But actually the 4th and 5th parameters have never been really used, and the first parameter is always used as a single content model group. So do the following change to make this API simpler:
1. Change parameter path to a single `ContentModelGroup`
2. Remove the 4th parameter table
3. Remove the 5th paramter treatAllAsSelect
> Rearrange parameters of iterateSelections

- tools/buildTools/normalize.js
Adding a module entry to roosterjs' package.json files. Having a module entry helps bundlers such as esbuild know the package is an ES module and find the right entry to the package, while avoid breaking changes for other consumers.
Fixes: #2190
> Adding module entry to package.json

- packages-content-model/roosterjs-content-model-core/lib/coreApi/formatContentModel.ts
- packages-content-model/roosterjs-content-model-core/lib/coreApi/getVisibleViewport.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/createStandaloneEditorCorePlugins.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/DarkColorHandlerImpl.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/createStandaloneEditorCore.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/createStandaloneEditorDefaultSettings.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/standaloneCoreApiMap.ts
- packages-content-model/roosterjs-content-model-core/lib/index.ts
- packages-content-model/roosterjs-content-model-core/package.json
- packages-content-model/roosterjs-content-model-core/test/coreApi/formatContentModelTest.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/getVisibleViewportTest.ts
- packages-content-model/roosterjs-content-model-core/test/editor/DarkColorHandlerImplTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/common/backgroundColorFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/segment/textColorFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-editor/lib/coreApi/coreApiMap.ts
- packages-content-model/roosterjs-content-model-editor/lib/corePlugins/createCorePlugins.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/ContentModelEditor.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/createEditorCore.ts
- packages-content-model/roosterjs-content-model-editor/lib/index.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/ContentModelCorePlugins.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/IContentModelEditor.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/createEditorCoreTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/e2e/testUtils.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/StandaloneEditorCore.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/StandaloneEditorOptions.ts
- packages-content-model/roosterjs-content-model-types/lib/index.ts
- packages-content-model/roosterjs-content-model-types/lib/pluginState/StandaloneEditorPluginState.ts
Create a function too allow creating `StandaloneEditorCore`, then do the following movements:
1. Remove `getVisibleViewport` from `ContentModelEditorOptions`
2. Move `core.getVisibleViewport` to be a core API so we can override it using core API override
3. Move `DarkColorHandlerImpl` into `roosterjs-content-model-core` package so we can directly create it from `createStandaloneEditorCore`
4. Add dependency to `color` library from `roosterjs-content-model-core` package, and move the `getDarkColor` function into `DarkColorHandlerImpl`, and remove `getDarkColor` parameter from `ContentModelEditorOptions`. Now Standalone editor has built in support for dark color calculation
5. Add new parameter `baseDarkColor` in `StandaloneEditorOptions` so that we can change the default base dark color. …
> Standalone Editor: CreateStandaloneEditorCore

- tools/buildTools/normalize.js
- versions.json
This change allows us add a version override in versions.json to each package so when we do version bump, no need to bump up those packages that is not changed.
For example
```js
{
"packages": "8.59.0",
"packages-ui": "8.54.0",
"packages-content-model": "0.20.0",
"overrides": {
"roosterjs-editor-plugins": "8.59.1"
}
}
```
With this config, all other roosterjs packages are still in 8.59.0, only `roosterjs-editor-plugins` will be bumped to 8.59.1.
> Allow each package has its own version when publish

- packages-content-model/roosterjs-content-model-core/lib/publicApi/model/createModelFromHtml.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/model/paste.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/createEditorCore.ts
Repro:
1. copy something with format
2. open demo site
3. set a different default format
4. paste
5. keep typing
Expect: the typed text is in default format
Actual: the type text does not have format
This is because when editor is empty, we didn't get original format. To fix, we need to retrieve default format as default value then let "original format" (retrieved from current selection) overwrite it.
We also need to set default format to initial model since we will have a cached model at beginning.
> Content Model: keep default format when paste into empty editor

- demo/scripts/controls/ContentModelEditorMainPane.tsx
- packages-content-model/roosterjs-content-model-core/lib/editor/DarkColorHandlerImpl.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/createStandaloneEditorCore.ts
- packages-content-model/roosterjs-content-model-core/package.json
- packages-content-model/roosterjs-content-model-core/test/editor/DarkColorHandlerImplTest.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/StandaloneEditorOptions.ts
In my earlier change I removed `getDarkColor` from `StandaloneEditorOptions` and directly import `color` library to calculate dark color. It generally works well. But when I integrate the code into OWA I hit some issue.
So for now let's go back to use the `getDarkColor` parameter from options, and pass a callback function into editor to calculate dark color. Later we can revisit this part.
> Content Model: Go back to getDarkColor

- packages-content-model/roosterjs-content-model-dom/lib/domToModel/utils/addSelectionMarker.ts
- packages-content-model/roosterjs-content-model-dom/lib/index.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelApi/common/addSegment.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelApi/common/ensureParagraph.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/processors/childProcessorTest.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/utils/addSelectionMarkerTest.ts
- packages-content-model/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/keyboardInputTest.ts
Repro step:
1. Use Content Model editor
2. Set a default font
3. Insert a table
4. Type something in the table, it should be in the default font
5. Select the cell and another cell to make a table selection
6. Type something
Expect: The new typed text overwrites the first cell, and is in default format
Actual: The new typed text overwrites the first cell, but it loses font
This is because with a recent change, we now use Content Model to delete the selected text. However, in TableCellSelection plugin we will select the whole TD then in Content Model we will create two implicit paragraphs before and after the real paragraph. Those implicit paragraphs do not have font, that causes after delete the selection marker also does not have font.
To fix it, I'm adding a segment format object into …
> Content Model: Fix overwrite table cell bug

- packages-content-model/roosterjs-content-model-core/lib/corePlugin/EntityPlugin.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/EntityPluginTest.ts
This is a regression of porting `EntityPlugin`. We used to call `commitEntity` when handle new entity and it will set readonly to the entity wrapper if the entity is readonly. However in the new `EntityPlugin` we are not using commitEntity, but we still need to set readonly for entity wrapper.
> ContentModel: Set readonly for new entity

- packages-content-model/roosterjs-content-model-core/lib/corePlugin/EntityPlugin.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/EntityPluginTest.ts
- versions.json
Do another version bump to fix a regression in EntityPlugin that can cause entity is not set to readonly after undo.
> Bump Content Model version to 0.21.2

- packages-content-model/roosterjs-content-model-plugins/lib/entityDelimiter/EntityDelimiterPlugin.ts
After porting EntityPlugin, the logic to check if we need to add entity delimiter is modified. Now it is always called after content change. So we need to skip those editable entities when we add entity delimiters.
> Content Model: Do not add entity delimiter to editable entity

- packages-content-model/roosterjs-content-model-plugins/lib/entityDelimiter/EntityDelimiterPlugin.ts
- versions.json
See https://github.com/microsoft/roosterjs/pull/2252 for more details.
> Bump roosterjs-content-model-plugins to 0.21.3 to fix entity delimiter issue

- demo/scripts/controls/sidePane/snapshot/ContentModelSnapshotPlugin.tsx
- packages-content-model/roosterjs-content-model-core/lib/editor/SnapshotsManagerImpl.ts
- packages-content-model/roosterjs-content-model-core/lib/index.ts
Demo site is broken because we are directly importing function `createSnapshotsManager` which is not officially exported so its function name is changed when pack.
Fix by exporting this function.
> Fix demo site broken

- packages-content-model/roosterjs-content-model-core/lib/coreApi/setContentModel.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/setContentModelTest.ts
When use setContentModel to rewrite content, we must reset the selection if it is not a range. Otherwise, the editor will keep a selection of an element that is no longer part of the document, resulting in a loss of selection.
> Update selection 

- packages-content-model/roosterjs-content-model-api/lib/modelApi/selection/collapseTableSelection.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/alignTableCell.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/deleteTableColumn.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/deleteTableRow.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/insertTableColumn.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/insertTableRow.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/mergeTableCells.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/mergeTableColumn.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/mergeTableRow.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/splitTableCellHorizontally.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/table/splitTableCellVertically.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/table/applyTableBorderFormat.ts
- packages-content-model/roosterjs-content-model-api/test/modelApi/selection/collapseTableSelectionTest.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/ContentModelCopyPastePlugin.ts
- packages-content-model/roosterjs-content-model-core/lib/index.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/table/getSelectedCells.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/ContentModelCopyPastePluginTest.ts
- packages-content-model/roosterjs-content-model-core/test/publicApi/table/getSelectedCellsTest.ts
- packages-content-model/roosterjs-content-model-types/lib/format/ContentModelTableFormat.ts
- packages-content-model/roosterjs-content-model-types/lib/index.ts
- packages-content-model/roosterjs-content-model-types/lib/parameter/Snapshot.ts
- packages-content-model/roosterjs-content-model-types/lib/selection/DOMSelection.ts
- packages-content-model/roosterjs-content-model-types/lib/selection/TableSelectionCoordinates.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/237733/?triage=true
This is because when cut/copy, if the original table has width, we didn't remove it. The same for column widths.
To fix it, we can delete table width and width for unselected columns when copy.
There is an exisiting interface `TableSelectionCoordinates` for `getSelectedCells` API can be reused in selection types, so reuse it. Also move `getSelectedCells` to `roosterjs-content-model-core` package so we can reuse it in `ContentModelCopyPastePlugin`.
> Fix 237733: [Table] The size of the pasted table becomes larger

- packages-content-model/roosterjs-content-model-core/test/coreApi/pasteTest.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/block/paddingFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/block/whiteSpaceFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/common/backgroundColorFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/common/borderFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/segment/boldFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/segment/letterSpacingFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/utils/shouldSetValue.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/processors/knownElementProcessorTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/block/paddingFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/block/whiteSpaceFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/common/backgroundColorFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/common/borderFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/segment/boldFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/segment/letterSpacingFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/utils/shouldSetValueTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/e2e/cmPasteFromExcelOnlineTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/e2e/cmPasteFromExcelTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/e2e/cmPasteFromWacTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/e2e/cmPasteTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/processPastedContentFromWacTest.ts
Today the paste API is still using a bunch of old API from `roosterjs-editor-dom` package. Now I'm porting it to use Content Model API only. 
This is the first step.
We have a HtmlSanitizer class used for sanitizing pasted content. Actually, Content Model is also going through the tree and pick up supported elements and attributes, so Content Model itself can also be used as Html Sanitizer. There are two places that we still directly pull in DOM element without sanitizing:
- General element: It handles all unrecognized HTML tags and hold a reference of those element directly.
- Entity: We hold the whole entity DOM tree without any sanitization
For all others, we are using `ElementProcessor` and `FormatHandler` to parse and sanitize them.
This change is a preparation step to do …
> Standalone Editor: Port paste API step 1

- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/common/sizeFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/table/tableSpacingFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/common/sizeFormatHandlerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/table/tableSpacingFormatHandlerTest.ts
Couple of improvements for table fidelity.
1. If the Width & Height attribute of the table is set to 0, it is not needed update the format, as width = 0 does not change the styling of the table
2. If the element has CellPadding attribute set the bordercollpase style to true, CellPadding attribute is deprecated, but to have a similar treatment use `bordercollapse: collapse` according to this link: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#cellpadding
Before and After here:
https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/245219/
> Table Fidelity improvement: Width Attribute and Cellpadding attribute

- packages-content-model/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/keyboardInputTest.ts
**Problem:** Asians characters relay on enter key to the transformation on mac, so it selects the text range before to the conversion, it will make content model handle the enter input wrongly, removing the asians character. 
**Fix:** Do not handle not collapsed ranges in mac.
> [Mac] Do not handle enter input on mac

- packages-content-model/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/keyboardInputTest.ts
- versions.json
Bump rooster-content-model plugin to 8.59.3
Release fix [PR 2301- Fix IME input sequence for mac](https://github.com/microsoft/roosterjs/pull/2301).
> [Hot Fix]- Bump RoosterJS Plugins 8.59.3

- demo/scripts/controls/ribbonButtons/contentModel/ContentModelRibbon.tsx
- demo/scripts/controls/ribbonButtons/contentModel/alignJustifyButton.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/block/setModelAlignment.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/block/setAlignment.ts
- packages-content-model/roosterjs-content-model-api/test/modelApi/block/setModelAlignmentTest.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/block/setAlignmentTest.ts
Include a feature that allows users to align text as justified, as well as ensuring that when a list item is aligned, the text within the list item is also aligned.
> [Content Model] Add text align justify option 

- packages-content-model/roosterjs-content-model-core/lib/utils/paste/createPasteFragment.ts
- packages-content-model/roosterjs-content-model-core/test/utils/paste/createPasteFragmentTest.ts
In a previous change I removed the container SPAN element when paste html. When integrate into OWA I found this triggers a bug that pasted content is wrong. To unblock us, I add this SPAN back as a workaround. We will need to fix the real problem then remove this workaround later.
> Workaround a paste issue

- packages-content-model/roosterjs-content-model-core/lib/utils/paste/createPasteFragment.ts
- packages-content-model/roosterjs-content-model-core/test/utils/paste/createPasteFragmentTest.ts
- versions.json
Bump `roosterjs-content-model-core` to 0.23.1 to workaround a paste issue.
> Version bump: Workaround a paste issue

- packages-content-model/roosterjs-content-model-editor/lib/editor/utils/eventConverter.ts
- packages-content-model/roosterjs-content-model-editor/lib/index.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/ContentModelBeforePasteEvent.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/utils/eventConverterTest.ts
Given that there are still a lot of plugins that is still using old `EditorPlugin` interface and is still handling `BeforePasteEvent` with Content Model related properties (e.g. `domToModelOption`, `customizedMerge`), we need a temporary interface that can be used by old plugin and can carry Content Model related properties. So add back `ContentModelBeforePasteEvent` interface into `roosterjs-content-model-editor` package. Later after we finish porting all those plugins we can remove this interface.
> Content Model: Add back ContentModelBeforePasteEvent

- packages-content-model/roosterjs-content-model-editor/lib/editor/utils/eventConverter.ts
- packages-content-model/roosterjs-content-model-editor/lib/index.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/ContentModelBeforePasteEvent.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/utils/eventConverterTest.ts
- versions.json
> Cherry-pick #2347: Add back ContentModelBeforePasteEvent

- demo/scripts/controls/ContentModelEditorMainPane.tsx
- packages-content-model/roosterjs-content-model-api/lib/modelApi/link/matchLink.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/entity/insertEntity.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/link/insertLink.ts
- packages-content-model/roosterjs-content-model-api/package.json
- packages-content-model/roosterjs-content-model-api/test/modelApi/link/matchLinkTest.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/link/insertLinkTest.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/segment/segmentTestCommon.ts
- packages-content-model/roosterjs-content-model-editor/lib/corePlugins/BridgePlugin.ts
- packages-content-model/roosterjs-content-model-editor/lib/corePlugins/EntityDelimiterPlugin.ts
- packages-content-model/roosterjs-content-model-editor/test/corePlugins/BridgePluginTest.ts
- packages-content-model/roosterjs-content-model-plugins/lib/index.ts
- packages-content-model/roosterjs-content-model-plugins/package.json
- packages-content-model/roosterjs-content-model-plugins/test/paste/processPastedContentFromWordDesktopTest.ts
- packages-content-model/roosterjs-content-model/lib/createContentModelEditor.ts
Remove dependencies to the following packages:
- roosterjs-editor-types
- roosterjs-editor-dom
From the following packages:
- roosterjs-content-model-api
- roosterjs-content-model-plugins
This has impacts to the following areas:
- matchLink(): Copy the function to `roosterjs-content-model-api` package
- Entity type: Just simply remove the type declaration when return it in `insertEntity` API as a short term solution. For log term, we may need to remove this return value at all.
- HtmlSanitizer: We are using it in `insertLink` API just for detecting if the link has something like "script:". We can just copy the code into this file directly
- EntityDelimiterPlugin: We have planned to port this plugin to be compatible with `StandaloneEditor`. For now let's just move it into …
> Standalone Editor: Remove dependency to old code from api and plugins package

- tools/buildTools/buildDemo.js
- tools/buildTools/pack.js
Change #2351 breaks demo site Content Model page because `ContentModelEditor` class is not bundled into `rooster-content-model.js` any more.
In this change I let this class to be compiled into demo site js to make it work.
> Fix demo site

- packages-content-model/roosterjs-content-model-editor/lib/editor/ContentModelEditor.ts
There are several places calling `transformToDarkColor` API without dark mode checking, including `editTable`.
Originally there is a check to dark mode inside this API, and do nothing if current editor is in light mode. But with recent change this check is gone.
Fix: Add a check to dark mode in `ContentModelEditor.transformToDarkColor`.
> Content Model: Fix table text color

- packages-content-model/roosterjs-content-model-core/lib/coreApi/createContentModel.ts
- packages-content-model/roosterjs-content-model-core/lib/coreApi/formatContentModel.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/ContentModelCachePlugin.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/utils/textMutationObserver.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/createContentModelTest.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/formatContentModelTest.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/ContentModelCachePluginTest.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/utils/textMutationObserverTest.ts
Change #2344 breaks pending format. Because:
1. When cache is not enabled, we need to clear cached element whenever user made some change via keyDown event or input event. So we need to add back the event handlers in `ContentModelCachePlugin`
2. When cache is enabled, we need to make sure cache is up-to-date before we get Content Model. So we need to call `flushMutations` from `createContentModel` API and trigger `onMutation` call back if there is reasonable mutations then `ContentModelCachePlugin` will handle them.
> Fix pending format

- packages-content-model/roosterjs-content-model-core/lib/editor/DOMHelperImpl.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/StandaloneEditor.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/createStandaloneEditorCore.ts
- packages-content-model/roosterjs-content-model-core/test/editor/DOMHelperImplTest.ts
- packages-content-model/roosterjs-content-model-core/test/editor/StandaloneEditorTest.ts
- packages-content-model/roosterjs-content-model-core/test/editor/createStandaloneEditorCoreTest.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/IStandaloneEditor.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/StandaloneEditorCore.ts
- packages-content-model/roosterjs-content-model-types/lib/index.ts
- packages-content-model/roosterjs-content-model-types/lib/parameter/DOMHelper.ts
When port existing plugins to use `StandaloneEditor`, we found that we still need access to DOM tree in some cases. To avoid providing too much API to access DOM tree directly in `IStandaloneEditor`, I'm creating a `DOMHelper` type and put all DOM access related functions here.
In this change we provide the first DOM access API: `queryElements`. For example:
```ts
const editor: IStandaloneEditor = ... 
const tables = editor.getDOMHelper().queryElements('table');
// Now we have all tables inside editor
```
Note that DOM helper access DOM directly so that it will not skip elements under entity, so we need to be careful when use this object.
> Standalone Editor: Provide a DOMHelper to allow access DOM tree

- packages-content-model/roosterjs-content-model-core/lib/coreApi/getDOMSelection.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/getDOMSelectionTest.ts
Change #2332 breaks shadow edit, because when we get selection (in `getDOMSelection.ts`), we are checking if editor has focus.
- When editor has focus, we always get selection from window.getSelection(), this is correct
- When editor does not have focus, we always get selection from the saved one -- this is the problem. When we are clicking away from editor, onBlur event will be triggered and in that case editor does not have focus but we are still able to get selection from window. So we need to first see if saved selection object is available, then fallback to window.getSelection() when editor does not have focus.
> Fix shadow edit

- packages-content-model/roosterjs-content-model-core/lib/coreApi/setContentModel.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/setContentModelTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
1. Shadow edit with one drop down, then directly go to another drop down, shadow edit will not work: https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/247916/?triage=true
2. Shadow edit will be auto applied when editor is in table selection: https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/235389/?triage=true
Fix:
1. Always restore selection to editor core when turn off shadow edit, so when go to next shadow edit, selection can still be correctly retrieved
2. Remove the code handling table selection for shadow editor from `TableCellSelection` plugin. @BryanValverdeU please take a look here if it is ok.
> Fix 2 shadow edit issue

- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/utils/parseValueWithUnit.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/utils/parseValueWithUnitTest.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/239731/?triage=true
For a lot of times we got report that image send from roosterjs is not rendering well in Win32 Outlook. In most cases the image become very large.
The root cause is Win32 Outlook does not support image size specified by CSS, but it requires HTML attributes `width` and `height`. We already have code in `handleImage` to write these values, but the missing case is the original size is specified with "inch" in unit. So we need to support it in Content Model.
> Support unit "inch" when parse value

- packages-content-model/roosterjs-content-model-core/lib/coreApi/paste.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/ContentModelCopyPastePlugin.ts
- packages-content-model/roosterjs-content-model-core/lib/utils/paste/mergePasteContent.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/pasteTest.ts
- packages-content-model/roosterjs-content-model-core/test/utils/paste/mergePasteContentTest.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/isContentModelEditor.ts
When paste:
- Before change: Create Content Model, then trigger BeforePaste event, then merge
- After change: Trigger BeforePaste event, then create content model, then merge
With this refactor, now it is allowed to do any change to editor content model when handle BeforePaste event, so that merge will be on top of the changed model.
> Code clean up: small refactor to paste code

- demo/scripts/controls/sidePane/contentModel/buttons/exportButton.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/block/setAlignmentTest.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/LifecyclePlugin.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/StandaloneEditor.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/LifecyclePluginTest.ts
- packages-content-model/roosterjs-content-model-core/test/editor/StandaloneEditorTest.ts
- packages-content-model/roosterjs-content-model-dom/lib/index.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelApi/creators/createEmptyModel.ts
- packages-content-model/roosterjs-content-model-dom/test/modelApi/creators/createEmptyModelTest.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/ContentModelEditorTest.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/IStandaloneEditor.ts
I'm cleaning up the Content Model code by removing some public methods that is not widely used.
- IStandaloneEditor.setContentModel: This function is used for flushing existing content using a given Content Model. We don't need it since this functionality should be replaced by `IStandaloneEditor.formatContentModel`.
> Code clean up: Remove IStandaloneEditor.setContentModel

- packages-content-model/roosterjs-content-model-core/lib/coreApi/setContentModel.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/ContentModelCopyPastePlugin.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/setContentModelTest.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/ContentModelCopyPastePluginTest.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/contentModelToDom.ts
Remove parameter `onNodeCreated` from API `contentModelToDom`, because it already has parameter `context` which can contain this parameter.
> Code cleanup: Remove parameter onNodeCreated

- packages-content-model/roosterjs-content-model-api/lib/modelApi/block/setModelDirection.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/block/toggleModelBlockQuote.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/common/retrieveModelFormatState.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/common/wrapBlock.ts
- packages-content-model/roosterjs-content-model-api/lib/modelApi/list/setListType.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/block/toggleBlockQuote.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/segment/changeCapitalization.ts
- packages-content-model/roosterjs-content-model-api/test/modelApi/block/toggleModelBlockQuoteTest.ts
- packages-content-model/roosterjs-content-model-api/test/modelApi/common/wrapBlockTest.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/block/toggleBlockQuoteTest.ts
- packages-content-model/roosterjs-content-model-core/lib/coreApi/switchShadowEdit.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/ContentModelFormatPlugin.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/SelectionPlugin.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/domUtils/borderValues.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/selection/deleteSegment.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/selection/iterateSelections.ts
- packages-content-model/roosterjs-content-model-dom/lib/domToModel/processors/entityProcessor.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/utils/parseValueWithUnit.ts
- packages-content-model/roosterjs-content-model-plugins/lib/edit/ContentModelEditPlugin.ts
- packages-content-model/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages-content-model/roosterjs-content-model-plugins/lib/paste/ContentModelPastePlugin.ts
1. Remove all "TODO" comment in Content Model code since they are either solved or not needed any more
2. The only one we still need is to support RTL when toggle BlockQuote, so add support to it.
> Code cleanup: Remove TODO and support RTL when toggle blockquote

- .github/workflows/build-and-deploy.yml
According to https://docs.opensource.microsoft.com/github/apps/permission-changes/#what-steps-must-i-take-to-avoid-a-bad-time and https://github.com/JamesIves/github-pages-deploy-action/blob/dev/README.md, we need to add a write permission to our `build-and-deploy` github action since it is using GITHUB_TOKEN to deploy demo site and reference documents to github_pages.
> Add write permission to deploy action

- versions.json
I realized that I missed some file change to do version bump. Since there are already multiple old packages got changed, let's do a full version bump for all old packages.
> Bump roosterjs version to 8.60.0

- packages-content-model/roosterjs-content-model-dom/lib/config/defaultHTMLStyleMap.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/block/paddingFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/test/formatHandlers/block/paddingFormatHandlerTest.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/252481/?triage=true
When there is "padding: 0" specified to OL/UL, we need to respect it since it will override the default "padding-inline-start: 40px" value.
So add a default value in `defaultHTMLStyleMap`, and read it in paddingFormatHandler, use this value as default value for OL/UL. When current value is not the same with default value, specify the value in format object.
> Content Model: Fix 252481

- packages-content-model/roosterjs-content-model-api/lib/index.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/table/editTable.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/utils/formatSegmentWithContentModel.ts
- packages-content-model/roosterjs-content-model-api/lib/publicApi/utils/formatTableWithContentModel.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/table/editTableTest.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/utils/formatTableWithContentModelTest.ts
Split the existing `editTable` API, extract a new common function `formatTableWithContentModel`, so we can easily write new table format API with the common code.
This is a preparation step of TableEdit plugin porting.
> Add API formatTableWithContentModel

- demo/scripts/controls/sidePane/editorOptions/getDefaultContentEditFeatureSettings.ts
Disable the classic editor ContentEdit list features on ContentModel Editor, then we can test and debug only the new content model edit plugin features without have the impact of the classic editor code.
> Disable list features in Content Model Demo Site 

- packages-content-model/roosterjs-content-model-core/lib/coreApi/paste.ts
- packages-content-model/roosterjs-content-model-core/lib/override/pasteEntityProcessor.ts
- packages-content-model/roosterjs-content-model-core/lib/override/pasteGeneralProcessor.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/model/createModelFromHtml.ts
- packages-content-model/roosterjs-content-model-core/lib/utils/convertInlineCss.ts
- packages-content-model/roosterjs-content-model-core/lib/utils/createDomToModelContextForSanitizing.ts
- packages-content-model/roosterjs-content-model-core/lib/utils/paste/generatePasteOptionFromPlugins.ts
- packages-content-model/roosterjs-content-model-core/lib/utils/paste/mergePasteContent.ts
- packages-content-model/roosterjs-content-model-core/lib/utils/paste/retrieveHtmlInfo.ts
- packages-content-model/roosterjs-content-model-core/test/publicApi/model/createModelFromHtmlTest.ts
- packages-content-model/roosterjs-content-model-core/test/utils/convertInlineCssTest.ts
- packages-content-model/roosterjs-content-model-core/test/utils/createDomToModelContextForSanitizingTest.ts
- packages-content-model/roosterjs-content-model-core/test/utils/paste/mergePasteContentTest.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/ContentModelBeforePasteEvent.ts
- packages-content-model/roosterjs-content-model-types/lib/context/DomToModelOption.ts
- packages-content-model/roosterjs-content-model-types/lib/event/BeforePasteEvent.ts
- packages-content-model/roosterjs-content-model-types/lib/index.ts
Today we have an API `createModelFromHtml`. We use it in `ContentModelEditor` to build initialization options to convert HTML to initial Content Model.
In this change I'm adding the following functionalities into this function:
- Convert global CSS to inline CSS
- Do HTML sanitization on general model and entity
- Parse format on BODY element into context so that inner elements can apply those format
> Convert inline CSS when create init model

- packages-content-model/roosterjs-content-model-core/lib/corePlugin/SelectionPlugin.ts
Fixes a bug that would cause context menu event to clear image selection on Mac, using Content Model editor.
This is due to a Mac behavior of not firing the `mouseup` event after/before a `contextmenu` event is fired and default context menu is displayed.
Given that `SelectionPlugin` relies on `mouseUp` plugin event to reselect the image in such cases, this would cause a `contextMenu` plugin event to be fired with no image selection available. In the case of the demo, this would result in no image context menu displayed.
Fixed by reusing previous selection if `mouseDown` target is a span and the first child is the previously selected image.
Additionally, allow dragged selection on right click `mouseUp`, since it's impossible to drag a `<span>` on a right click.
> [Mac] Fix selection on context menu after image selection click

- packages-content-model/roosterjs-content-model-core/lib/corePlugin/SelectionPlugin.ts
- versions.json
Versions:
packages-content-model: 0.26.1
Adds a last minute fix for image selection on Mac
> [Bump RoosterJS] Content-Model: 0.26.1

- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
For API `insertNode`, if the parameter `updateCursor` is false, we don't need to reselect the selection after insert, so that we can avoid accidentally putting focus into editor.
> Fix insertNode: Do not reselect if updateCursor is false

- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
- versions.json
Integrate #2431 (Fix insertNode: Do not reselect if updateCursor is false) into release and publish 0.26.2
> Integrate #2431 (Fix insertNode: Do not reselect if updateCursor is false) into release and publish 0.26.2

- packages-content-model/roosterjs-content-model-plugins/lib/edit/deleteSteps/deleteCollapsedSelection.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/deleteSteps/deleteCollapsedSelectionTest.ts
If the paragraph was indented, when pressing backspace on the paragraph we are not reducing the indentation margins.
This PR adds the functionality when backspacing on a empty paragraph that have margins to outdent just like before in the original editor. By adding some code to the deleteCollapsedSelection and calling the setModelIndentation outdent to the currently selected model.
Gif:
https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/238611/
> Outdent indented empty paragraph when pressing Backspace.

- versions.json
Bump roosterjs-editor-adapter to 0.26.1 to include the latest focus fix
> Bump roosterjs-editor-adapter to 0.26.1

- packages-content-model/roosterjs-content-model-core/lib/publicApi/model/exportContent.ts
- packages-content-model/roosterjs-content-model-core/test/publicApi/model/exportContentTest.ts
- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
While testing the latest version bump, I found an issue that when we call `EditorAdapter.getContent()`, we didn't pass in the modelToDomOption so that the generated HTML removed a lot of attributes.
To fix this, add a parameter to `exportContent` function to allow pass in options so that those attributes can be preserved.
> Support adding options for exportContent

- packages-content-model/roosterjs-content-model-core/lib/utils/sanitizeElement.ts
- packages-content-model/roosterjs-content-model-core/test/utils/sanitizeElementTest.ts
When sanitize element and its child elements, we need to pass down attribute sanitizers together with other parameters.
> Fix #2435: AttributeSanitizers are not applied to the child elements

- packages-content-model/roosterjs-content-model-plugins/lib/edit/keyboardTab.ts
- packages-content-model/roosterjs-content-model-plugins/lib/edit/tabUtils/handleTabOnList.ts
- packages-content-model/roosterjs-content-model-plugins/lib/edit/tabUtils/handleTabOnParagraph.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/keyboardTabTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/tabUtils/handleTabOnListTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/tabUtils/handleTabOnParagraphTest.ts
Add the `handleTabOnParagraph` function in the `keyboardTab` file. Also split the `handleTabOnList` function in a separate file. 
The `handleTabOnParagraph` function will handle the tab key in following scenarios: 
1. When the selection is collapsed and the cursor is at the end of a paragraph, add 4 spaces.
2. When the selection is collapsed and the cursor is at the start of a paragraph, call `setModelIndention` function to indent the whole paragraph
3. When the selection is collapsed and the cursor is at the middle of a paragraph, add 4 spaces.
4. When the selection is not collapsed, replace the selected range with a single space.
5. When more that one paragraph is selected,  call `setModelIndention` function to indent the whole paragraph
The `handleTabOnParagraph` function will handle …
> Handle tab key for paragraph

- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
This is a recent regression in EditorAdapter.
When we dispose EditorAdapter, we should dispose its plugins first (via super.dispose()), then finally we dispose the core object. Otherwise if any plugin needs the core object during disposing, there will be exception.
> Fix dispose plugin issus in EditorAdapter

- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
- versions.json
Bump `roosterjs-editor-adapter` to 0.26.3 to patch #2452
> Bump roosterjs-editor-adapter to 0.26.3 to patch #2452

- packages-content-model/roosterjs-content-model-core/lib/publicApi/selection/deleteBlock.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/selection/deleteSegment.ts
- packages-content-model/roosterjs-content-model-dom/lib/domUtils/reuseCachedElement.ts
- packages-content-model/roosterjs-content-model-dom/test/domUtils/reuseCachedElementTest.ts
#2202: Delete first entity causes second entity to be reloaded in Content Model editor
I made a change (#2389) to fix #2202 before. The fix is to delete the entity element from DOM tree when press DELETE or BACKSPACE so when write back Content Model, the deleted entity element won't bother the reuse algorithm. 
However, this causes a problem. We deleted the entity element before adding undo snapshot from `formatContentModel`, so that when add undo snapshot before write back, the DOM tree is already changed, so an extra undo snapshot is added. When we want to undo the change to bring the entity back, we need to press Ctrl+Z twice.
In this change, I first revert the previous fix, then change the algorithm of reusing entity element. If the next element we are about to add into DOM tree is an …
> Fix #2202 again

- packages-content-model/roosterjs-content-model-api/lib/publicApi/entity/insertEntity.ts
- packages-content-model/roosterjs-content-model-api/test/publicApi/entity/insertEntityTest.ts
- packages-content-model/roosterjs-content-model-core/lib/corePlugin/EntityPlugin.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/Editor.ts
- packages-content-model/roosterjs-content-model-core/lib/utils/restoreSnapshotHTML.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/EntityPluginTest.ts
- packages-content-model/roosterjs-content-model-core/test/editor/EditorTest.ts
- packages-content-model/roosterjs-content-model-dom/lib/domUtils/entityUtils.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/entity/entityFormatHandler.ts
- packages-content-model/roosterjs-content-model-dom/lib/index.ts
- packages-content-model/roosterjs-content-model-dom/test/domUtils/entityUtilTest.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/IEditor.ts
- packages-content-model/roosterjs-content-model-types/lib/parameter/InsertEntityOptions.ts
The change does two things:
1. When insertEntity, we now allow passing in an initial entity state. So when user undo to the state right after insert entity, we can use this initial state to update entity.
2. The editor API `takeSnapshot` now accepts entity state. So if we just want to add an undo snapshot for entity state update, we can use editor.takeSnapshot() rather than `formatContentModel`.
Also add a util function `parseEntityFormat` to replace the original function `parseEntityClassName` to make it easier parsing entity information.
> Improve Entity State related API

- demo/scripts/controls/StandaloneEditorMainPane.tsx
- packages-content-model/roosterjs-content-model-core/lib/index.ts
- packages-content-model/roosterjs-content-model-core/lib/publicApi/domUtils/cacheGetEventData.ts
- packages-content-model/roosterjs-content-model-core/test/publicApi/domUtils/cacheGetEventDataTest.ts
- packages-content-model/roosterjs-content-model-plugins/lib/index.ts
- packages-content-model/roosterjs-content-model-plugins/lib/shortcut/ShortcutCommand.ts
- packages-content-model/roosterjs-content-model-plugins/lib/shortcut/ShortcutPlugin.ts
- packages-content-model/roosterjs-content-model-plugins/lib/shortcut/shortcuts.ts
- packages-content-model/roosterjs-content-model-plugins/test/shortcut/ShortcutPluginTest.ts
- packages/roosterjs-editor-adapter/lib/corePlugins/BridgePlugin.ts
- packages/roosterjs-editor-adapter/test/corePlugins/BridgePluginTest.ts
Port the `shortcutFeatures` of original `ContentEdit` plugin to be a separate plugin `ShortcutPlugin`. So that the standalone new editor can work with shortcut support.
> Port ShortcutPlugin

- packages-content-model/roosterjs-content-model-core/lib/corePlugin/CopyPastePlugin.ts
- packages-content-model/roosterjs-content-model-core/test/corePlugin/CopyPastePluginTest.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/EditorOptions.ts
- packages-content-model/roosterjs-content-model-types/lib/pluginState/CopyPastePluginState.ts
Add option in the Editor options to change the PasteType of the CopyPastePlugin.
> Add option to configure the default paste type

- packages-content-model/roosterjs-content-model-api/test/publicApi/image/insertImageTest.ts
- packages-content-model/roosterjs-content-model-core/test/publicApi/model/createModelFromHtmlTest.ts
- packages-content-model/roosterjs-content-model-core/test/publicApi/model/mergeModelTest.ts
- packages-content-model/roosterjs-content-model-dom/lib/domToModel/utils/addSelectionMarker.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelApi/common/normalizeParagraph.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/utils/addSelectionMarkerTest.ts
- packages-content-model/roosterjs-content-model-dom/test/endToEndTest.ts
- packages-content-model/roosterjs-content-model-dom/test/modelApi/common/normalizeParagraphTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/e2e/cmPasteFromExcelOnlineTest.ts
- packages-content-model/roosterjs-content-model-plugins/test/paste/processPastedContentFromWordDesktopTest.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/257626/?triage=true
When create selection marker, we didn't read format from existing block decorator, causes format specified on decorator is not shown in format state. To fix it, read format from decorator and use it.
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/258837/?triage=true
When paste plain text, the format will be applied to SPAN element. However, if existing content applies segment format on DIV, this will cause some layout difference even their formats are the same. To fix, we try to move fontFamily/fontSize/textColor from segment to paragraph if all its child segments have the same such format.
> Fix 258837 and 257626

- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableResizer.ts
Tests related to the new Table resizer plugin were failing randomly due to editor methods being accessed on a disposed editor.
Add a check for disposed editor befor all action on onDragEnd on TableResizer.
- Replicating the behaviour is not consistent.
> Fix #2474 - Expand isDisposed check

- packages/roosterjs-content-model-core/lib/coreApi/createContentModel.ts
- packages/roosterjs-content-model-core/lib/editor/Editor.ts
- packages/roosterjs-content-model-core/lib/publicApi/model/exportContent.ts
- packages/roosterjs-content-model-core/test/coreApi/createContentModelTest.ts
- packages/roosterjs-content-model-core/test/editor/EditorTest.ts
- packages/roosterjs-content-model-core/test/publicApi/model/exportContentTest.ts
- packages/roosterjs-content-model-types/lib/editor/EditorCore.ts
- packages/roosterjs-content-model-types/lib/editor/IEditor.ts
When export HTML content, selection should not be included when create Content Model.
This is to avoid generating unnecessary DOM element when export, for example, when TABLE is the last element of the document and user put focus after table, Content Model will create an implicit paragraph for the selection marker. When generate HTML, this implicit paragraph can be represented as a SPAN. We can avoid this by not including selection into the model.
> Export content without selection

- demo/scripts/controlsV2/demoButtons/darkModeButton.ts
The dark mode button in demo site is broken, so fix it.
It is calling old main pane to toggle dark mode, so it is not working
> Fix dark mode button in demo site

- demo/scripts/controlsV2/mainPane/MainPane.tsx
- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionState.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionsPane.tsx
- packages/roosterjs-content-model-core/lib/corePlugin/CachePlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/CachePluginTest.ts
- packages/roosterjs-content-model-plugins/test/paste/e2e/testUtils.ts
- packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts
- packages/roosterjs-content-model-types/lib/editor/EditorOptions.ts
- packages/roosterjs-editor-adapter/test/editor/EditorAdapterTest.ts
To prepare for next release, I'm changing Editor Option `cacheModel` to be `disableCache` so that by default cache will be allowed.
> Enable Content Model cache by default

- packages/roosterjs-content-model-api/lib/modelApi/block/toggleModelBlockQuote.ts
- packages/roosterjs-content-model-core/lib/index.ts
- packages/roosterjs-content-model-core/lib/modelApi/edit/deleteExpandedSelection.ts
- packages/roosterjs-content-model-core/lib/publicApi/model/getClosestAncestorBlockGroupIndex.ts
- packages/roosterjs-content-model-core/lib/publicApi/model/isBlockGroupOfType.ts
- packages/roosterjs-content-model-core/lib/publicApi/model/mergeModel.ts
- packages/roosterjs-content-model-core/lib/publicApi/selection/collectSelections.ts
- packages/roosterjs-content-model-core/lib/publicApi/selection/iterateSelections.ts
- packages/roosterjs-content-model-core/lib/utils/paste/mergePasteContent.ts
- packages/roosterjs-content-model-core/test/publicApi/selection/collectSelectionsTest.ts
- packages/roosterjs-content-model-core/test/publicApi/selection/iterateSelectionsTest.ts
- packages/roosterjs-content-model-dom/lib/domUtils/isNodeOfType.ts
- packages/roosterjs-content-model-dom/lib/index.ts
- packages/roosterjs-content-model-plugins/test/tableEdit/tableEditPluginTest.ts
- packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts
- packages/roosterjs-content-model-types/lib/index.ts
- packages/roosterjs-content-model-types/lib/parameter/IterateSelectionsOption.ts
- packages/roosterjs-content-model-types/lib/parameter/MergeModelOption.ts
- packages/roosterjs-content-model-types/lib/parameter/NodeTypeMap.ts
- packages/roosterjs-content-model-types/lib/parameter/OperationalBlocks.ts
- packages/roosterjs-content-model-types/lib/parameter/TypeOfBlockGroup.ts
Move public type definitions into roosterjs-content-model-type package
Move file only, no logic change
> Move public type definitions into roosterjs-content-model-type package

- packages/roosterjs-content-model-core/lib/publicApi/paste/paste.ts
- packages/roosterjs-content-model-core/lib/utils/paste/mergePasteContent.ts
To repro:
Copy some text, paste. Then from the "Paste Options" bar, choose an option to repaste.
Expect: pasted content is removed and replaced with new content with new option
Actual: Both old pasted content and new pasted content are existing together
Reason: When paste, we first get a content model and save into ClipboardData. When repaste, we first use this content model, clone it to overwrite existing content then paste again into the cloned content model. However, in https://github.com/microsoft/roosterjs/pull/2481, I removed the code to clone content model when first paste, so the saved model is the same one in editor so any change to editor will also impact this saved one, which causes when repaste we are pasting on top of current model, not the original one.
Fix: Clone the model …
> Patch: Fix paste issue for repaste

- packages/roosterjs-content-model-core/lib/publicApi/paste/paste.ts
- packages/roosterjs-content-model-core/lib/utils/paste/mergePasteContent.ts
- packages/roosterjs-content-model-plugins/lib/edit/tabUtils/handleTabOnParagraph.ts
- packages/roosterjs-content-model-plugins/test/edit/tabUtils/handleTabOnParagraphTest.ts
- versions.json
Add this patch fixes:
[Do not prevent Shift+ Tab behavior #2514](https://github.com/microsoft/roosterjs/pull/2514)
[Patch: Fix paste issue for repaste #2516](https://github.com/microsoft/roosterjs/pull/2516)
Versions: {
"legacy": "8.61.0",
"react": "8.55.0",
"main": "0.28.0",
"legacyAdapter": "0.28.0",
"overrides": {
"roosterjs-content-model-core": "0.28.1",
"roosterjs-content-model-plugins": "0.28.1"
}
}
> Patch Fixes for Content Model Core and Plugins 

- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
"UndoByBackspace" is a feature to allow user use Backspace key to undo the last change. We have this behavior in several old features, such as auto list. 
However, in new editor this is now broken. When call `formatContentModel`, we will add undo snapshot before and after write back. We need to set undoByBacksapce to true for the undo snapshot before write back to mark it as the snapshot to revert to, then the snapshot after write back should not have "undobyBackspace".
> Fix bug in "undoByBackspace"

- packages/roosterjs-content-model-core/lib/coreApi/createContentModel/createContentModel.ts
- packages/roosterjs-content-model-core/lib/coreApi/setContentModel/setContentModel.ts
- packages/roosterjs-content-model-core/lib/corePlugin/cache/CachePlugin.ts
- packages/roosterjs-content-model-core/lib/corePlugin/cache/areSameSelection.ts
- packages/roosterjs-content-model-core/lib/corePlugin/cache/domIndexerImpl.ts
- packages/roosterjs-content-model-core/lib/corePlugin/cache/updateCachedSelection.ts
- packages/roosterjs-content-model-core/test/coreApi/createContentModel/createContentModelTest.ts
- packages/roosterjs-content-model-core/test/coreApi/setContentModel/setContentModelTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/CachePluginTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/areSameSelectionTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/domIndexerImplTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/updateCachedSelectionTest.ts
- packages/roosterjs-content-model-types/lib/context/DomIndexer.ts
- packages/roosterjs-content-model-types/lib/index.ts
- packages/roosterjs-content-model-types/lib/pluginState/CachePluginState.ts
- packages/roosterjs-content-model-types/lib/selection/DOMSelection.ts
I realized that it is caused by the cached selection range got updated automatically when selection is changed, so when we try to update cache, it got a result that new selection and the cached one are the same, so we skip updating cache, then we always do format on a staled content model.
To fix it, we store start/end container and offset separately in CachePlugin rather than saving a range, so it will not get auto update.
> Fix #2525 Format button does not work in Safari when WatermarkPlugin is enabled

- demo/scripts/controlsV2/mainPane/MainPane.tsx
- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
Let auto format feature disable by the default, because it can cause conflicts while we do not turn off the legacy ones. Enable them only for Demo site.
> Disable auto format features

- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/lib/corePlugin/format/FormatPlugin.ts
- packages/roosterjs-content-model-core/lib/corePlugin/undo/UndoPlugin.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/undo/UndoPluginTest.ts
- packages/roosterjs-content-model-dom/lib/domToModel/utils/addSelectionMarker.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/childProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/textProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/utils/addSelectionMarkerTest.ts
- packages/roosterjs-content-model-plugins/test/paste/processPastedContentFromExcelTest.ts
- packages/roosterjs-content-model-types/lib/pluginState/FormatPluginState.ts
- packages/roosterjs-content-model-types/lib/pluginState/UndoPluginState.ts
- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
In old editor we have a `NodePosition` interface which stores a node-offset pair. In new editor I removed it since we should focus on using Content Model to represent selection.
However, now I realized that in some places it is still continent to have such an interface, so I added an interface `DOMInsertPoint` in an earlier change. Now we can leverage this interface in several places, such as
- UndoPluginState for the auto complete insert point
- FormatPluginState for the pending format insert point
This is a refactor only, no logic change
> Leverage DOMInsertPoint, remove posContainer/offset

- packages/roosterjs-content-model-api/lib/publicApi/format/getFormatState.ts
- packages/roosterjs-content-model-api/lib/publicApi/utils/formatInsertPointWithContentModel.ts
- packages/roosterjs-content-model-api/test/publicApi/utils/formatInsertPointWithContentModelTest.ts
- packages/roosterjs-content-model-core/lib/coreApi/createContentModel/createContentModel.ts
- packages/roosterjs-content-model-core/lib/coreApi/createEditorContext/createEditorContext.ts
- packages/roosterjs-content-model-core/lib/editor/Editor.ts
- packages/roosterjs-content-model-core/test/coreApi/createContentModel/createContentModelTest.ts
- packages/roosterjs-content-model-core/test/coreApi/createEditorContext/createEditorContextTest.ts
- packages/roosterjs-content-model-core/test/editor/EditorTest.ts
- packages/roosterjs-content-model-types/lib/context/DomToModelOption.ts
- packages/roosterjs-content-model-types/lib/editor/EditorCore.ts
- packages/roosterjs-content-model-types/lib/editor/IEditor.ts
- packages/roosterjs-content-model-types/lib/index.ts
To repro:
1. Open demo site, turn on side pane
2. Type "abc"
3. Type ENTER
4. Type BACKSPACE, keep doing it until everything is gone
5. Keep typing BACKSPACE
Expect: nothing happens
Actual, "ab" reappears
The root cause is demo site will always update content model by calling getContentModelCopy() which will update model cache before our formatContentModel() API write cache back, it is triggered when backspace. So the result is cached model in DOM tree is updated by demo site, but cached model in editor is updated by formatContentModel(), so the two models don't match. Later when we keep editing, it will edit on a staled cache.
To fix it, we should not update cache when create model from demo site. Furthermore, we should not update cache at all from API `getContentModelCopy`. It should be …
> Fix cache issue

- packages/roosterjs-content-model-plugins/lib/edit/deleteSteps/deleteList.ts
- packages/roosterjs-content-model-plugins/lib/edit/inputSteps/handleEnterOnList.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/test/edit/deleteSteps/deleteListTest.ts
- packages/roosterjs-content-model-plugins/test/edit/inputSteps/handleEnterOnListTest.ts
- packages/roosterjs-content-model-plugins/test/edit/keyboardDeleteTest.ts
When cursor is at beginning of a paragraph under a list, press Backspace, we first change current list item to be a dummy list item (no list number or bullet). Press Backspace again, it will outdent to upper level, or become a regular paragraph if there is only one list level. Press Backspace again, go back to previous list item if exists.
When press ENTER on a dummy list item, create a new list item.
This is to keep the same behavior with Word.
> Improve backspace on list

- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/selection/SelectionPluginTest.ts
Use  browser's  `selectionChange` event to fix the image selection, when the range is changed by a shortcut, such as CTRL+A.
> Fix selection with ctrl+a

- demo/scripts/controlsV2/sidePane/editorOptions/DefaultFormatPane.tsx
- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
Set the following default format in demo site, so that we can better test default format behavior.
- font family: Calibri
- font size: 11pt
- text color: black
> Set default format in demo site

- demo/scripts/controlsV2/mainPane/MainPane.tsx
- demo/scripts/controlsV2/plugins/createLegacyPlugins.ts
- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionState.ts
- demo/scripts/controlsV2/sidePane/editorOptions/Plugins.tsx
- demo/scripts/controlsV2/sidePane/editorOptions/codes/HyperLinkCode.ts
- demo/scripts/controlsV2/sidePane/editorOptions/codes/PluginsCode.ts
- packages/roosterjs-content-model-plugins/lib/hyperlink/HyperlinkPlugin.ts
- packages/roosterjs-content-model-plugins/lib/hyperlink/HyperlinkToolTip.ts
- packages/roosterjs-content-model-plugins/lib/index.ts
- packages/roosterjs-content-model-plugins/test/hyperlink/HyperlinkPluginTest.ts
Port Hyperlink plugin
add test cases.
This has 3 functionalities:
1. Hover on link, show a tooltip
2. Ctrl+Click, open link in a new window
3. Edit on a link whose text matches its link url, update the link url
> Port Hyperlink plugin

- packages/roosterjs-content-model-dom/lib/config/defaultContentModelFormatMap.ts
- packages/roosterjs-content-model-dom/test/endToEndTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/utils/stackFormatTest.ts
To repro, restore the snapshot below, then rewrite with Content Model:
```html
<div style="font-family: Calibri; font-size: 11pt; color: rgb(0, 0, 0);"><span style="color: rgb(245, 212, 39);"><a href="http://www.bing.com" style="color: rgb(245, 212, 39);">www.bing.com</a></span></div><div style="font-family: Calibri; font-size: 11pt; color: rgb(0, 0, 0);"><br></div>
```
Root cause: we have an optimization when all child segments of a paragraph have the same styles, we will move the styles from segments to paragraph when rewrite. However, for hyperlink we still need to keep its color if it has since browser will always use its own color to render link unless we directly assign color to the A tag.
Fix: Add a default color "undefined" on A tag as default style so that this will override the …
> Fix #2500 Hyperlink misses color

- packages/roosterjs-content-model-plugins/lib/shortcut/shortcuts.ts
- packages/roosterjs-content-model-plugins/test/shortcut/ShortcutPluginTest.ts
Disable the following shortcuts in Mac, since their native behavior is very useful to the user. 
|Shortcut | Functionality |
| ---------| ---------------|
| Option + Shift+ Arrow Left | Select whole words   |
| Option + Shift+ Arrow Right | Select whole words |
| Meta + space | Open MacOS emoji keyboard |
> Disable shortcuts in Mac 

- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
Previously we fixed an issue where the Entity element can't be deleted on Android (https://github.com/microsoft/roosterjs/pull/2402). However, a new cursor issue appeared: the cursor jumps to the last line after removing the entity. 
After some invetigation, we found the cursor position was modified by browser, so we reported it to Chromium: https://issues.chromium.org/issues/330596261. In this PR we are going to restore the correct cursor position in next animation frame as a workaround.
> Content model: Fix the cursor jump issue after deleting an Entity on Android

- packages/roosterjs-content-model-core/lib/corePlugin/copyPaste/CopyPastePlugin.ts
selection in focus() become null after this call
https://github.com/microsoft/roosterjs/blob/a4457db8c9806400b27a1567c206b2bc5bf40290/packages/roosterjs-content-model-core/lib/corePlugin/copyPaste/CopyPastePlugin.ts#L236C9-L236C21
and focus with null selection make the window scroll to the top
Oddly enough I wasn't able to reproduce the problem in the web demo
> fix: on webkit-based applications, the selection will become empty after copy, and focus will cause the window to scroll to the top

- demo/scripts/controlsV2/sidePane/contentModel/components/model/ContentModelDocumentView.tsx
- packages/roosterjs-content-model-core/lib/corePlugin/cache/domIndexerImpl.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/domIndexerImplTest.ts
- packages/roosterjs-content-model-dom/lib/domToModel/domToContentModel.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/contentModelToDom.ts
- packages/roosterjs-content-model-dom/test/domToModel/domToContentModelTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/contentModelToDomTest.ts
- packages/roosterjs-content-model-types/lib/group/ContentModelDocument.ts
To repro:
1. Type some text
2. Put cursor in middle of text
3. Shift+Left several times to select some text
4. Ctrl+B to format
5. keep Shift+Left
Expect: Keep expanding selection to the left
Actual: shrink selection from left
Reason: In content model we didn't preserve the "isReverted" information. So after rewrite, this info is lost.
Fix: Add a property `hasRevertedRangeSelection` is `ContentModelDocument`, and maintain it when selection is changed. When create content model, read this info from the selection we passed in, then return it when rewrite.
> Preserve reverted selection info in Content Model

- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
- packages/roosterjs-content-model-plugins/test/edit/EditPluginTest.ts
Browser has native support for Cut when press Shift+Delete, we should not intercept this behavior.
> Allow Shift+Delete to Cut

- packages/roosterjs-content-model-api/lib/publicApi/table/editTable.ts
- packages/roosterjs-content-model-api/test/publicApi/table/editTableTest.ts
In Safari, when selection is under a table, and user opens context menu, browser will expand the selection to next cell, which should be a browser bug. And that causes our content model treats both cells are selected.
To workaround it, collapse the selection when edit table in Safari.
For more info about the bug, see #2584
> Fix #2584: Safari context menu event causes selection to be expanded

- packages/roosterjs-content-model-core/lib/override/listMetadataApplier.ts
- packages/roosterjs-content-model-dom/lib/index.ts
- packages/roosterjs-content-model-dom/lib/modelApi/list/getAutoListStyleType.ts
- packages/roosterjs-content-model-dom/lib/modelApi/list/getOrderedListNumberStr.ts
- packages/roosterjs-content-model-dom/test/modelApi/list/getAutoListStyleTypeTest.ts
- packages/roosterjs-content-model-dom/test/modelApi/list/getOrderedListNumberStrTest.ts
Move out the code for calculating list style type and number string, so that they can be easily reused.
> Port AnnouncePlugin step 1: refactor list number code

- packages/roosterjs-content-model-plugins/lib/watermark/WatermarkPlugin.ts
When input with IME, we need to hide watermark text since the input will finally trigger compositionEnd event rather than keydown or input event.
> Hide watermark when input with IME

- packages/roosterjs-content-model-plugins/lib/watermark/WatermarkPlugin.ts
Updated watermark property access modifier to make it available for classes that extends WatermarkPlugin.
Fix for https://github.com/microsoft/roosterjs/issues/2612
> Updated watermark property access modifier to protected

- packages/roosterjs-content-model-core/lib/command/paste/mergePasteContent.ts
- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages/roosterjs-content-model-types/lib/parameter/FormatContentModelOptions.ts
Add a parameter `scrollCaretIntoView` to `FormatContentModelOptions`, when pass it to true, after format with content model we will scroll caret into view so that user can keep seeing latest changed content.
And set this option to true for the following scenarios:
- paste
- keyboard input
- keyboard delete
> Scroll caret into view when call formatContentModel

- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/selection/SelectionPluginTest.ts
Check whether the table is editable before applying table selection.
If the table is not editable the table is most likely inside of a readonly entity.
> Do not apply Table selection if table is not editable

- packages/roosterjs-content-model-core/lib/command/paste/mergePasteContent.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
This is a temp fix to #2633, just disable this scrolling behavior. We will need a full fix later.
> Fix #2633 `scrollCaretIntoView` causes unexpected scroll

- packages/roosterjs-content-model-core/lib/coreApi/setDOMSelection/setDOMSelection.ts
- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/coreApi/setDOMSelection/setDOMSelectionTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/selection/SelectionPluginTest.ts
- packages/roosterjs-content-model-types/lib/editor/EditorOptions.ts
- packages/roosterjs-content-model-types/lib/pluginState/SelectionPluginState.ts
Added `tableCellSelectionBackgroundColor` option to `EditorOptions` to update cell selection color
> Added tableCellSelectionBackgroundColor option

- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
When applying a Gboard suggestion (such as auto-correction or the double-tap-space-for-period), the cursor will jump backwards. The root cause is https://github.com/microsoft/roosterjs/pull/2577 restored the selection in next animation frame. 
To fix this regression, we need to restore the selection on next `keyup` event, because IME can trigger other input events and change the cursor position before next frame.
> Fix cursor jump issue when applying Gboard suggestions

- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/link/createLink.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/link/createLinkTest.ts
When the paste segment already has a link, trigger the auto link event. Also add the anchor element to the event data object.
> Auto link for link preview

- packages/roosterjs-content-model-dom/lib/modelApi/selection/setSelection.ts
- packages/roosterjs-content-model-dom/test/modelApi/selection/setSelectionTest.ts
#2578 Cannot cut tables
Root cause: When call `setSelection`, even whole table is selected, we didn't set `isSelected` to true to table cell.
Fix: set cell.isSelected=true if context.isSelected == true before and after a table cell in `setSelection`.
> Fix #2578:  Cannot cut tables

- .vscode/settings.json
- demo/scripts/controlsV2/plugins/SamplePickerPlugin.tsx
- demo/scripts/controlsV2/roosterjsReact/pasteOptions/component/showPasteOptionPane.tsx
- demo/scripts/controlsV2/sidePane/formatState/FormatStatePlugin.ts
- packages/roosterjs-content-model-core/lib/command/paste/mergePasteContent.ts
- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/scrollCaretIntoView.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/scrollCaretIntoViewTest.ts
- packages/roosterjs-content-model-dom/lib/domUtils/selection/getDOMInsertPointRect.ts
- packages/roosterjs-content-model-dom/lib/index.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages/roosterjs-content-model-plugins/lib/index.ts
Previously I added a feature in `formatContentModel` to allow scroll caret into view after write back with Content Model. It was using browser's `scrollIntoView` implementation which has some problem especially when caret is already visible. And we also need to handle the case when visible viewport is not the actual size of editor (`getVisibleViewport()` will give us the expected value). So in this change I created our own implementation of `scrollCreateIntoView`, and call it from existing format API
> Provide our own implementation of `scrollCaretIntoView`

- packages/roosterjs-content-model-plugins/lib/autoFormat/list/getListTypeStyle.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/numbers/transformFraction.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/list/getListTypeStyleTest.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/numbers/transformFractionTest.ts
To repro:
1. type "constructor"
2. type SPACE
Expect: nothing special happens
Actual: it converts "constructor" into a list with text "function Object() { [native code] } "
This is because we have code like this:
```ts
const map = {
key: value
};
const value =map[input];
```
If input is some predefined property name such as "constructor", "valueOf", "toString", it will return a function object which is treated as a valid result, which should not.
Fix: use Map instead of Record here.
Future work: Check all other places where Record is used. Possibly find a eslint rule to disable it at all.
> Word "constructor" should not trigger auto list

- packages/roosterjs-content-model-api/lib/modelApi/entity/insertEntityModel.ts
- packages/roosterjs-content-model-api/test/modelApi/entity/insertEntityModelTest.ts
This is a little bit hard to explain.
Suppose we have the DOM structure:
```html
<div><span id=entity>...</span>[CURSOR]<div>
```
Then we call `insertEntity` to insert an entity and put the existing SPAN into the new entity, we set position to be right before this SPAN so the new entity should be inserted to replace the SPAN, and cursor is not moved.
However, inside `insertEntity` we will move the SPAN into entity wrapper, then call `formatContentModel` to insert entity. Since the SPAN is removed from the DOM tree, we need to recreate a content model, and in that case the real cursor and override cursor will be at the same place. Then our code will put the real selection marker before the override selection marker, which causes the entity is inserted after focus.
To fix this, we can check …
> Fix insert entity issue

- packages/roosterjs-content-model-plugins/lib/watermark/WatermarkPlugin.ts
- packages/roosterjs-content-model-plugins/test/watermark/WatermarkPluginTest.ts
- Added a check for dark mode before applying the styles and update a placeholder text color when theme is changed.
- Added a test
> Support dark mode for WatermarkPlugin placeholder styles

- packages/roosterjs-content-model-plugins/lib/watermark/WatermarkPlugin.ts
- packages/roosterjs-content-model-plugins/test/watermark/WatermarkPluginTest.ts
- versions.json
This is an ask from ACS Web UI team. They fixed a dark mode issue in WatermarkPlugin so we can do version bump for the plugin package now. See #2702 for more information.
> Bump roosterjs-content-model-plugins to 9.6.1 to integrate #2702

- versions.json
Bump `roosterjs-editor-adapter` to 8.62.1 since we changed it in PR https://github.com/microsoft/roosterjs/pull/2651
> Bump editor-adapter to 8.62.1

- packages/roosterjs-content-model-plugins/test/tableEdit/tableMoverTest.ts
Some test cases in tableMoverTest.ts are unstable since they share the same test data. To fix them, create test data everytime a test is running.
> Fix unstable test in tableMoverTest

- packages/roosterjs-content-model-plugins/test/tableEdit/tableEditorTest.ts
Disable unstable test cases, for example: (This is just one of them, I saw this happens in different places)
```
Firefox 127.0 (Linux x86_64) TableEditor disableFeatures Disable Table Mover FAILED
Expected true to be false.
<Jasmine>
./packages/roosterjs-content-model-plugins/test/tableEdit/tableEditorTest.ts/</</<@webpack://roosterjs/packages/roosterjs-content-model-plugins/test/tableEdit/tableEditorTest.ts:103:31 <- karma.test.all.2302904290.js:176083:31
<Jasmine>
Firefox 127.0 (Linux x86_64): Executed 246 of 4263 (1 FAILED) (0 secs / 0.177 secs)
```
Example: https://github.com/microsoft/roosterjs/actions/runs/9553286758/job/26331765889?pr=2706
Opened #2709 for tracking the fix to root cause.
> Temporarily disable unstable test cases

- packages/roosterjs-content-model-dom/lib/domUtils/selection/getDOMInsertPointRect.ts
In order to get rect of the cursor, we have a function `getDOMInsertPointRect()`, it uses several different ways to get current rect.
However, one of them is to insert a temp SPAN then call getBoundingClientRect() of this SPAN. This causes a DOM tree change and can causes our content model cache to be cleared. 
This change is to remove this way, and use a normalized range instead. It shows that for a range inside text node, it can return the rect successfully.
> Improve getDOMInsertPointRect

- packages/roosterjs-content-model-core/lib/editor/core/createEditorCore.ts
- packages/roosterjs-content-model-core/lib/editor/core/createEditorDefaultSettings.ts
- packages/roosterjs-content-model-core/test/editor/core/createEditorCoreTest.ts
- packages/roosterjs-content-model-core/test/editor/core/createEditorDefaultSettingsTest.ts
- packages/roosterjs-content-model-types/lib/editor/EditorPlugin.ts
- packages/roosterjs-content-model-types/lib/index.ts
This change adds the `getContentModelConfig` function to `EditorPlugin`, this function returns the domToModel/ModelToDom options. After this change plugin will be able to add additional format parses/applier to content model. The function `createDomToModelSettings` and `createModelToDomSettings` were modified to accept the `additionalOptions` parameter
> Add config for plugin

- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/selection/SelectionPluginTest.ts
Using the Tab key (or Shift+Tab) moves the selection marker to an adjacent cell, or the previous/next row. The position is always at the start of the cell.
Modify the behaviour of using the Tab key in a table so that instead of collapsing the selection at the start, it selects the whole contents of the cell.
1. Create a Table and populate it with content
2. Use the tab key to move across cells
**Before:** After movement, the selection is always at the start of the cell
**After:** After movement, the selection encompasses all the contents of the cell
> Using Tab key on table selects the whole next cell

- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/selection/SelectionPluginTest.ts
When selectionChange event happens, ensure the focus exist before setting the selection in the new position, otherwise
getRangeSelection(0) will return an error, since nothing is selected.
> Ensure focusNode exists when selectionChanges

- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/TableEditor.ts
- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableMover.ts
- packages/roosterjs-content-model-plugins/test/tableEdit/tableMoverTest.ts
The Table Mover feature is incorrectly dismissed when only clicking it. To fix do not dismiss the table mover if the target on drag end target is not the div containing the Table mover.
Before (Notice that on click the mouse cursor is set to arrow because the table mover element got detached.)
After
> Only dismiss the Table Mover if the end of the drag is not in the Table Mover div

- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/index.ts
- packages/roosterjs-content-model-plugins/test/edit/EditPluginTest.ts
EditPlugin overrides the default behavior of Tab key by increasing the margin-left value of current line. As a result, user can't navigate to next focusable element by pressing Tab key, so we need an option for disabling this behavior.
> Add option for Tab Key handling in EditPlugin

- packages/roosterjs-content-model-core/lib/corePlugin/format/FormatPlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/format/FormatPluginTest.ts
On Android, the default format can't be applied to the new content because the `isCharacterValue()` check in `FormatPlugin` always fails when using Android IME. To workaround this issue, we need to disable this check on Android.
> Fix default format on Android

- packages/roosterjs-content-model-plugins/lib/autoFormat/numbers/transformOrdinals.ts
- packages/roosterjs-content-model-plugins/lib/markdown/utils/setFormat.ts
- packages/roosterjs-content-model-plugins/test/markdown/utils/setFormatTest.ts
The markdown should not be trigger inside a word, so we check if exist a space before the trigger character
* Should trigger markdown example: _one two_
* Should not trigger markdown example: one_two_
Before:
After:
> Do not trigger markdown inside a word. 

- packages/roosterjs-content-model-dom/lib/formatHandlers/list/listLevelThreadFormatHandler.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/childProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/listProcessorTest.ts
- packages/roosterjs-content-model-dom/test/endToEndTest.ts
- packages/roosterjs-content-model-dom/test/formatHandlers/list/listLevelThreadFormatHandlerTest.ts
To repro, having a numbered list start from 1, then type something before it. Now at the beginning of the doc, type "1." and space.
Expect: Converting "1." to be a list, and the existing list is not impacted
Actual: Converting "1." to be a list, but the existing list is now starting from 2.
This is because we incorrectly connected these two list together, because we didn't set "startNumberOverride" for the existing one so it would connect to previous list if exist.
Fix: Allow setting startNumberOverride in ListLevel.format when it is 1, so it can never be auto connected.
> Do not increase list number that starts from 1

- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/selection/SelectionPluginTest.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
Fix 1: when select image for copy/cut, the image range selection must appear. 
Fix 2: on firefox delete the image using delete/backspace to remove the image.
Warning: this fix for image range selection does not work on Safari, selecting image range on safari is breaking the cut behavior.
> Fix Image range selection

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/findEditingImage.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/findEditingImageTest.ts
The images in tables was not working properly, because the findImageEditing functions was not looking for images in the Table blockgroup. To fix the issue, adjust findImageEditing to search for images inside tables.
> Fix image selection in tables

- packages/roosterjs-editor-plugins/lib/plugins/Picker/PickerPlugin.ts
- versions.json
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/285727/?triage=true
This is a special fix for roosterjs v8. We got customer complain that they cannot use @ mention after "+". So make this fix specially for that case.
> Fix picker issue, allow + for mentions

- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/findEditingImage.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/findEditingImageTest.ts
When image does not have id and the imageId parameter does not exist the `findEditingImage` was return the image as editing image, what is not correct. To avoid that issue, only compare the imageId and the image id, if imageId parameter exists. 
**To repro the bug**: 
1. Paste  two images
2. Click at the second one
3. Press a key
4. The first image will be replaced by the second. 
**Before:** 
**After:**
> Fix findEditingImage

- packages/roosterjs-content-model-plugins/lib/edit/keyboardEnter.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardTab.ts
For `formatContentModel` triggered from keyboard event (ENTER, TAB, DELETE, ...), we should use a different change source than the default `ChangeSource.Format`. We already have such a change source `Keyboard` so we should use it.
Then from plugins we can know if the ContentChanged event is from keyboard editing.
> Use a different change source for keyboard formatting event

- packages/roosterjs-content-model-api/lib/modelApi/common/clearModelFormat.ts
- packages/roosterjs-content-model-api/lib/publicApi/format/clearFormat.ts
- packages/roosterjs-content-model-api/test/modelApi/common/clearModelFormatTest.ts
- packages/roosterjs-content-model-api/test/publicApi/format/clearFormatTest.ts
Today when we do clear format, we will unwrap list item, but if there is still other things to unwrap, we skipped.
To fix it, we can run `clearModelFormat` multiple times when last time unwrap happened, so we can keep checking if there more things need to be unwrapped.
#2699
> Fix #2699 If there is a list in a quote, clearFormat can't clear the quote

- packages/roosterjs-content-model-core/lib/editor/core/DOMHelperImpl.ts
- packages/roosterjs-content-model-core/test/editor/core/DOMHelperImplTest.ts
- packages/roosterjs-content-model-types/lib/parameter/DOMHelper.ts
Add a new function `getClonedRoot` to `DOMHelper`, so we can use it to get a cloned copy of root element of editor.
This can be used to create a customized exportContent API, for example:
```ts
export function exportContent2(editor: IEditor): string {
const clonedRoot = editor.getDOMHelper().getClonedRoot();
if (editor.isDarkMode()) {
transformColor(clonedRoot, false /*includeSelf*/, 'darkToLight', editor.getColorManager());
}
editor.triggerEvent(
'extractContentWithDom',
{
clonedRoot,
},
true /*broadcast*/
);
return clonedRoot.innerHTML;
}
```
> Let DOM Helper return a cloned root

- packages/roosterjs-content-model-dom/lib/domToModel/processors/brProcessor.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/brProcessorTest.ts
It is possible to set selection into BR element, so we also need to handle the selection in a BR.
BR should not have child nodes, so we don't need to care its offset, just always treat the BR element as selected when it has selection.
> Fix #2807 Handle selection in BR

- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
- packages/roosterjs-content-model-plugins/test/edit/EditPluginTest.ts
- packages/roosterjs-content-model-types/lib/editor/ExperimentalFeature.ts
Previously I'm using the same experimental feature "PersistCache" for new cache and ENTER key for content model.
In this change I split them into two separate features so we can enable them separately.
> Use a separate experimental feature for Enter key

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
When the image is in edit mode, the text caret is visible and blinking near the image, therefore when the image is in editing mode, add CSS style to hide the caret.
> [Image Edit] When the image is in edit mode, hide the text caret

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
Make the image edit info protected in the `ImageEditPlugin` class, so the if class is extended, the `imageEditInfo` property can be accessed by the subclass and changed.
> Make the imageEditInfo protected

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
When deleting an editing image, clean the image information and remove the styles added, otherwise the style to hide cursor will 
stay on the editor.
> Clean info when delete image

- packages/roosterjs-content-model-core/lib/corePlugin/cache/domIndexerImpl.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/domIndexerImplTest.ts
#2804 
This is because when cache is enabled, the updated selection marker does not copy link info from text segment, so `adjustLinkSelection` failed to match the text segment around the selection marker.
Fix: Include link and code info in reconciled selection marker.
> Fix #2804 adjustLinkSelection does not select whole link

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
If expanded range selection happens while image is in editing mode and the range selection contains the image, when mouse up ensure the image is selected, but not as image selection.
> Fix image selection in range expanded selection 

- packages/roosterjs-content-model-dom/lib/modelApi/common/isEmpty.ts
When image has no src, we should not treat it as empty, so return false from isEmpty() function.
This is to avoid image without src to be removed from Content Model when calling `normalizeContentModel`
> Do not treat image without src as empty image

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/getDropAndDragHelpers.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/getDropAndDragHelpersTest.ts
Enable resize/rotate/crop images using touch events.
> Make image edit features work with touch

- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/list/keyboardListTrigger.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
Use TAB key to auto format list. [269932]( https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/269932)
> Auto format list on TAB

- packages/roosterjs-content-model-plugins/lib/autoFormat/numbers/transformOrdinals.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/numbers/transformOrdinalsTest.ts
If st, nd, rd and th are typed after a link with a number, trigger superscript. [Bug 278807](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/278807)
> Trigger ordinals after link

- packages/roosterjs-content-model-dom/lib/formatHandlers/block/htmlAlignFormatHandler.ts
- packages/roosterjs-content-model-dom/test/endToEndTest.ts
- packages/roosterjs-content-model-dom/test/formatHandlers/block/htmlAlignFormatHandlerTest.ts
See #2835 if there is CSS text-align on the same element, it should override HTML align. So `htmlAlignFormatHandler` should skip the attribute.
> Fix #2835 Ignore HTML align when there is CSS text-align

- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
- packages/roosterjs-content-model-plugins/test/edit/EditPluginTest.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/313638/?triage=true
When handle ENTER key, if CTRL (or META) is also pressed, we should leave it to browser.
> Do not handle ENTER key when CTRL is pressed

- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
Right now, when the Zoom Changes. The Editor is not triggering the ZoomChanged event. This is because the function DOMHelper().calculateZoomScale() is always returning the value as the new zoomScale. Causing that the event is never triggered to the legacy plugins.
To fix remove the check in EditorAdapter::setZoomScale, since it is always falsy.
> Fix ZoomScaleChangedEvent no longer being triggered in EditorAdapter

- packages/roosterjs-content-model-core/lib/corePlugin/cache/domIndexerImpl.ts
- packages/roosterjs-content-model-core/test/command/paste/mergePasteContentTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/domIndexerImplTest.ts
- packages/roosterjs-content-model-dom/lib/modelApi/common/normalizeParagraph.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/contentModelToDom.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/handlers/handleParagraph.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/optimizers/optimize.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/brProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/entityProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/generalProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/imageProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/tableProcessorTest.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/textProcessorTest.ts
- packages/roosterjs-content-model-dom/test/modelApi/common/normalizeContentModelTest.ts
- packages/roosterjs-content-model-dom/test/modelApi/common/normalizeParagraphTest.ts
- packages/roosterjs-content-model-dom/test/modelApi/editing/mergeModelTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/contentModelToDomTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/handlers/handleParagraphTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/handlers/handleTableTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/optimizers/optimizeTest.ts
- packages/roosterjs-content-model-plugins/test/paste/processPastedContentFromWacTest.ts
- packages/roosterjs-content-model-plugins/test/paste/processPastedContentFromWordDesktopTest.ts
- packages/roosterjs-content-model-types/lib/context/DomIndexer.ts
- packages/roosterjs-content-model-types/lib/context/ModelToDomSelectionContext.ts
This change fixes two issues.
1. When two or more continuous text segments have the same format, we can merge them into one when `normalizeContentModel` and `normalizeParagraph`
2. When selection marker is located between two text segments that have same format, when create DOM  tree, we can just create a single text node for them and remember the selection offset in context, and fixup their cached segments info.
This can solve the following problems:
1. Make the result content model predictable after changing selections
2. Correct the cached segments after Node.normalize() is called (https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/309633/?triage=true)
> Merge text node and segments

- packages/roosterjs-content-model-plugins/lib/edit/keyboardEnter.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardTab.ts
- packages/roosterjs-content-model-plugins/test/edit/inputSteps/handleEnterOnListTest.ts
In order to allow knowing which key is pressed when handling ContentChangedEvent with ChangeSource=Keyboard, we add apiName and change data into the event object. Then plugin can check event.data or event.formatApiName to know the key:
> Add change data and apiName to ContentChangedEvent when handle keyboard input

- packages/roosterjs-content-model-plugins/lib/shortcut/ShortcutPlugin.ts
- packages/roosterjs-content-model-plugins/lib/shortcut/shortcuts.ts
- packages/roosterjs-content-model-plugins/test/shortcut/ShortcutPluginTest.ts
This shortcut is the same as the default global spotlight shortcut, so it is invalid if the user keeps spotlight‘s. Some users prefer to keep it the same as Windows by disable spotlight
> Revert Shortcut command for Clear Format on mac

- packages/roosterjs-content-model-core/lib/corePlugin/copyPaste/CopyPastePlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/copyPaste/CopyPastePluginTest.ts
Android users are unable to paste content from Word to Outlook after recent Chromium update. The root cause is that the clipboard data from Word contains only a File object, without any HTML or plain text. And we can't use `FileReader` to extract paste content from it.
To workaround this issue, we are adding a check to `CopyPastePlugin`: if the clipboard data can't be processed by roosterjs (e.g., it doesn't have any plain text, HTML and image), preventDefault() shouldn't be called, allowing the browser to handle the paste event instead.
> Allow browser's default paste behavior when pasting from Office Android

- packages/roosterjs-content-model-plugins/lib/edit/inputSteps/handleEnterOnList.ts
- packages/roosterjs-content-model-plugins/test/edit/inputSteps/handleEnterOnListTest.ts
When press enter between two sub list items, preserve the list sequence.
> Fix sub list spacing 

- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/createImageWrapper.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/createImageWrapperTest.ts
Instead of adding the vertical align to the image span, add to the image wrapper. 
Before: 
After:
> Add a vertical alignment to the image wrapper

- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/lib/corePlugin/format/FormatPlugin.ts
- packages/roosterjs-content-model-core/lib/corePlugin/format/applyPendingFormat.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/format/FormatPluginTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/format/applyPendingFormatTest.ts
- packages/roosterjs-content-model-types/lib/parameter/FormatContentModelContext.ts
- packages/roosterjs-content-model-types/lib/pluginState/FormatPluginState.ts
In addition to pending segment format, we now support specify pending format for paragraph. To do that, assign a pending format object to context.newPendingParagraphFormat within callback of `formatContentModel`:
```ts
this.editor.formatContentModel((_, context) => {
context.newPendingParagraphFormat = {...};
return false;
});
```
> #2861 Allow specify pending format for paragraph

- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-types/lib/parameter/FormatContentModelContext.ts
Now we can let editor (EntityPlugin) to auto detect changed entity (added, removed) during `formatContentModel`.
To do this, set `context.autoDetectChangedEntities` to be true:
```ts
editor.formatContentModel((model, context)=>{
... // add or remove entities
context.autoDetectChangedEntities = true;
return true;
});
```
Then there will be code to search all changed entities and trigger `entityOperation` event for each of them.
But if possible, you can still use `context.newEntities` and `context.deletedEntities` to manually specify changed entities since they have better performance. Once `autoDetectChangedEntities` is set to true, `context.newEntities` and `context.deletedEntities` will be ignored.
> #2855 Add a parameter for formatContentModel to allow auto detection of new/removed entities

- packages/roosterjs-content-model-api/lib/publicApi/utils/formatTextSegmentBeforeSelectionMarker.ts
- packages/roosterjs-content-model-api/test/publicApi/utils/formatTextSegmentBeforeSelectionMarkerTest.ts
- packages/roosterjs-content-model-core/lib/corePlugin/cache/domIndexerImpl.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/domIndexerImplTest.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/handlers/handleSegmentDecorator.ts
- packages/roosterjs-content-model-dom/test/modelToDom/handlers/handleBrTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/handlers/handleSegmentDecoratorTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/utils/handleSegmentCommonTest.ts
The problem is, when create DOM tree, content model index is added to not only leaf nodes (#text, image, br, ...) but also their wrapper if any (e.g. `<A>`). And `optimize()` can merge some elements without updating their index info. When reconcile content model from user's input, we may see an incorrect index to be updated.
To repro:
1. use the snapshot below
2. type something
3. press enter
After enter, the text order is wrong. This is because the cached model is incorrectly updated.
```html
<a href="#"><img src="null">test</a>
```
To fix it:
1. No need to add model index to wrapper element (A, CODE, ...)
2. When reconcile, find index from leaf node only.
> Fix #2880  optimize() causes segment cache to be wrong when merging <A>

- packages/roosterjs-content-model-core/lib/coreApi/setContentModel/setContentModel.ts
- packages/roosterjs-content-model-core/lib/editor/core/createEditorCore.ts
- packages/roosterjs-content-model-core/test/coreApi/setContentModel/setContentModelTest.ts
- packages/roosterjs-content-model-core/test/editor/core/createEditorCoreTest.ts
- packages/roosterjs-content-model-types/lib/editor/EditorCore.ts
- packages/roosterjs-content-model-types/lib/editor/EditorOptions.ts
Some feature has requirement that content model should satisfy some format, such as there must be an entity before / after something. We now provide a callback to allow them do those fix up work before write back to editor. To use it:
```ts
const editor = new Editor(div, {
...
onFixUpModel: model => {
... // fix up model, for example
model.blocks.push({ ... });
}
});
```
> #2878 Provide a callback function to allow fixup model before write back

- packages/roosterjs-content-model-core/lib/corePlugin/format/applyDefaultFormat.ts
- packages/roosterjs-content-model-core/test/corePlugin/format/FormatPluginTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/format/applyDefaultFormatTest.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages/roosterjs-content-model-plugins/test/edit/keyboardInputTest.ts
#2862 
When select text and type to replace, we first delete it, keep its format, then let browser to handle the input. However, if there is text with different format right before it, browser will apply the format from existing text.
To fix this, we set a SPAN with ZeroWidthSpace in it and make it selected so browser will replace this selection instead of applying format from text before.
> Fix #2862 Keep format when replace a selection

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
When the image is dragged, the suffix dragging is added to the image id. If the image is never dropped, this suffix remains at the image id. Therefore, when dragend event happens, remove the suffix from the image id. This change ensures that the image id is adjusted after the dragend event.
> Remove dragging suffix

- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/createImageWrapper.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/createImageWrapperTest.ts
Following the changes in https://github.com/microsoft/roosterjs/pull/2868, images added via drag and drop became uneditable. This issue arises because the attribute in the span of the shadow root was removed, causing the `optimize` function to remove this span in the `removeUnnecessarySpan` function. To resolve this, an ID was added to the ImageEdit shadow span to prevent its removal during content model optimization.
> Do not remove image shadow root

- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
When pressing shift + tab key combination, do not check if we should start a list. Also, if a list should not be triggered, do not call `preventDefault` function.
> Do not prevent shift tab

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
When extract content with DOM event is triggered, the `ImageEditPlugin` now removes the `isEditing` and `editingInfo` dataset attributes from any images in the cloned root.
> Remove Image dataset

- demo/scripts/controlsV2/demoButtons/tableTitleButton.ts
- demo/scripts/controlsV2/tabs/ribbonButtons.ts
- packages/roosterjs-content-model-dom/lib/formatHandlers/common/ariaFormatHandler.ts
- packages/roosterjs-content-model-dom/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model-dom/test/formatHandlers/common/ariaFormatHandlerTest.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/ContentModelTableFormat.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/FormatHandlerTypeMap.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/formatParts/AriaFormat.ts
- packages/roosterjs-content-model-types/lib/index.ts
Add `title` and `aria-describedby` attributes to table model. Also add title control to demo site.
> Add accessibility attributes

- packages/roosterjs-editor-adapter/lib/corePlugins/BridgePlugin.ts
- packages/roosterjs-editor-adapter/lib/index.ts
- packages/roosterjs-editor-adapter/lib/publicTypes/MixedPlugin.ts
- packages/roosterjs-editor-adapter/test/corePlugins/BridgePluginTest.ts
To help porting old plugin to new plugin, with some mixed state, we want to support "MixedPlugin", which can accept both v8 and v9 types. For v9 types, the function names will have a postfix "V9", including:
- initializeV9
- onPluginEventV9
- willHandleEventExclusivelyV9
So that a plugin can implement the new interface `MixedPlugin` and add these methods, so it will receive new editor and events via the methods above.
> Support MixedPlugin

- demo/index.html
- demo/scripts/utils/cssMonitor.ts
- index.html
- package.json
- packages/roosterjs-react/lib/emoji/components/EmojiIcon.tsx
- packages/roosterjs-react/lib/emoji/components/EmojiNavBar.tsx
- packages/roosterjs-react/lib/emoji/components/EmojiPane.tsx
- packages/roosterjs-react/lib/emoji/components/EmojiStatusBar.tsx
- packages/roosterjs-react/lib/emoji/type/EmojiPaneStyles.ts
- packages/roosterjs-react/lib/ribbon/component/Ribbon.tsx
- tools/buildTools/checkDependency.js
- yarn.lock
The old fluent ui font files for icons were removed, so we upgraded the fluent ui react version to 8.122.3 to fix the demo site icons.
> Fix demo site icons

- packages/roosterjs-content-model-api/lib/publicApi/segment/changeFontSize.ts
We'd like to have this parameter to allow consumers to customize the font size list just like what we have in the legacy editor.
> Add parameter `fontSizes` back to `changeFontSize`

- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/test/edit/EditPluginTest.ts
- packages/roosterjs-content-model-plugins/test/edit/keyboardDeleteTest.ts
Some Android IMEs automatically select the character before the cursor when pressing Backspace. As a result, `shouldDeleteWithContentModel` always returns true, which triggers the model-DOM conversion. If the user presses Backspace multiple times in a long content, the editor will enter continuous model-DOM conversions, causing memory usage to consistently increase.
To mitigate this issue, this PR is adding an option in `EditPlugin` to skip CM handling for the expanded selection within the same text node. After enabling it, the memory usage is reduced:
> Skip CM handling when deleting expanded selection within text node

- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/Plugins.tsx
- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/interface/AutoFormatOptions.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/list/keyboardListTrigger.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/list/keyboardListTriggerTest.ts
To make the list format consistent between list triggered by characters and list triggered by ribbon control, add the option to remove the list margins when starting a new list using AutoFormat Plugin.
> Remove margins of auto formatted list. 

- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-types/lib/parameter/FormatContentModelContext.ts
We have a parameter `skipUndoSnapshot` in `formatContentModel` context object to allow skipping adding undo snapshot. When it is set to true, `formatContentModel` will not add undo snapshot but it will mark `hasNewContent` to be true so next time undo is performed, we will first add an undo snapshot then undo.
But in some scenario we don't even want to mark `hasNewContent` as well, so in this PR I modified this parameter to let it allow 3 different values in addition to existing true | false value:
* When set to 'DoNotSkip', it will add undo snapshot (default behavior)
* When set to 'MarkNewContent', it will skip adding undo snapshot but mark "hasNewContent" so that next undo snapshot will be added
* When set to 'SkipAll', it will skip adding undo snapshot and not mark "hasNewContent", as …
> Allow skipping marking hasNewContent in `formatContentModel`

- packages/roosterjs-editor-adapter/lib/corePlugins/BridgePlugin.ts
- packages/roosterjs-editor-adapter/test/corePlugins/BridgePluginTest.ts
BridgePlugin should be able to dispatch event that only exists in v9 into mixed plugins.
Add code to allow this to happen.
> Fix bridge plugin to be able to handle new event

- demo/scripts/controlsV2/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-types/lib/editor/ExperimentalFeature.ts
Clean the code to make the Legacy Image Edit to be compatible with the Content Model Image Edit, since it is Image Edit is fully ported.
> Remove LegacyImageSelection

- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
After a text is automatically transformed into a link by typing and pressing space, send the anchor element when the ContentChanged event is triggered. Also add more unit tests.
> Send anchor event in Auto Link

- packages/roosterjs-content-model-dom/lib/config/defaultContentModelFormatMap.ts
- packages/roosterjs-content-model-dom/lib/config/defaultHTMLStyleMap.ts
- packages/roosterjs-content-model-dom/lib/modelApi/editing/applyTableFormat.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/handlers/handleTable.ts
- packages/roosterjs-content-model-dom/test/endToEndTest.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/ContentModelTableCellFormat.ts
Original bug: https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/334221/?triage=truehttps://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/334221/?triage=true
Minimum repro:
```html
<table><tr><th style="font-weight:400">test</th></tr></table>
```
Since font-weight:400 is the default value for most elements, it is ignored here. However TH has a default style: font-weight: bold, so we need to recognize its default font weight and respect this value.
> Respect font weight in TH element

- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/CellResizer.ts
- packages/roosterjs-content-model-plugins/test/tableEdit/cellResizerTest.ts
Original bug: https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/331303/?triage=true
If table has style "width", resize may not work since its whole width is not changed. Fix it by setting the table width if it exists.
> Fix resize table with width

- packages/roosterjs-content-model-dom/lib/domUtils/event/extractClipboardItems.ts
- packages/roosterjs-content-model-dom/test/domUtils/event/extractClipboardItemsTest.ts
Lont press safari's address bar to copy will get the web link in the type text/uri-list. Handling it in roosterjs to support pasting it.
To solve the issue #2942
> Support text/uri-list when pasting

- packages/roosterjs-content-model-api/lib/publicApi/segment/toggleUnderline.ts
- packages/roosterjs-content-model-api/test/publicApi/segment/toggleUnderlineTest.ts
Bug link: https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/317607/?triage=true
This is caused by https://github.com/microsoft/roosterjs/pull/2288, it was fixing an issue that trailing space is also included into link. However I feel underline should not be excluded, since it will cause the underline button to be unchecked.
> Fix #317607

- packages/roosterjs-react/lib/ribbon/plugin/createRibbonPlugin.ts
There is a code bug in RibbonPlugin in roosterjs-react that causes the format state change check to fail when some property does not exist in the new format state.
Fix it by checking key count as well.
> Fix #2927 Fix the check of format state change

- packages/roosterjs-content-model-dom/lib/modelToText/contentModelToText.ts
- packages/roosterjs-content-model-types/lib/parameter/ModelToTextCallbacks.ts
This change is to allow calling `contentModelToText` using readonly content model types.
> Let contentModelToText accepts readonly types

- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/selection/SelectionPluginTest.ts
If there were no image selected, and the selection changed to a single image, select the image as image selection.
> Select image with keyboard

- packages/roosterjs-content-model-api/lib/modelApi/block/setModelAlignment.ts
- packages/roosterjs-content-model-api/lib/modelApi/block/setModelDirection.ts
- packages/roosterjs-content-model-api/lib/modelApi/block/setModelIndentation.ts
- packages/roosterjs-content-model-api/lib/modelApi/block/splitSelectedParagraphByBr.ts
- packages/roosterjs-content-model-api/lib/modelApi/block/toggleModelBlockQuote.ts
- packages/roosterjs-content-model-api/lib/modelApi/list/setListType.ts
- packages/roosterjs-content-model-api/lib/publicApi/utils/formatParagraphWithContentModel.ts
- packages/roosterjs-content-model-api/test/modelApi/block/setModelAlignmentTest.ts
- packages/roosterjs-content-model-api/test/modelApi/block/setModelDirectionTest.ts
- packages/roosterjs-content-model-api/test/modelApi/block/setModelIndentationTest.ts
- packages/roosterjs-content-model-api/test/modelApi/block/splitSelectedParagraphByBrTest.ts
- packages/roosterjs-content-model-api/test/modelApi/block/toggleModelBlockQuoteTest.ts
- packages/roosterjs-content-model-api/test/modelApi/list/setListTypeTest.ts
- packages/roosterjs-content-model-api/test/publicApi/utils/formatParagraphWithContentModelTest.ts
When current paragraph has BR and do any paragraph format such as set indentation or bullet list, we need to split the paragraph by BR into multiple paragraphs then only format selected paragraphs.
For example:
```html
<div>aaaa</div>
bbb<br>ccc<br>ddd<br>eee
<div>ffff</div>
<div>gggg</div>
hhh<br>iii<br>jjj
<div>kkk</div>
```
Before:
After:
Original bug: https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/335899/?triage=true
> Fix 335899: Split paragraph by BR before doing block format

- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/hyphen/transformHyphen.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/hyphen/transformHyphenTest.ts
Refactor the `AutoFormatPlugin` class to trigger only one auto format at a time to avoid conflict between the formatting.  
Before: 
After:
> Trigger only one auto format at time

- packages/roosterjs-content-model-core/lib/corePlugin/format/applyPendingFormat.ts
Repro Steps:
1. Add Korean IME and set Korean as the default input language
2. open OWA/new outlook
3. New-mail
4. Typing gksrmf(한글)
This is because we are always applying pending format if it exists which will interrupt current IME behavior.
Fix: Add a check to the format and do not apply if it is already applied
> Fix Korean input issue

- packages/roosterjs-content-model-api/lib/modelApi/list/getListAnnounceData.ts
- packages/roosterjs-content-model-api/test/modelApi/list/getListAnnounceDataTest.ts
Add a null check in getListAnnounceData
Error callstack:
at webpack://owa/packages/roosterjs-content-model-api/lib/modelApi/list/getListAnnounceData.ts:27
at webpack://owa/packages/roosterjs-content-model-plugins/lib/edit/inputSteps/handleEnterOnList.ts:46
at webpack://owa/packages/roosterjs-content-model-dom/lib/modelApi/editing/runEditSteps.ts:16
at Native Browser Function(Array.forEach)
at webpack://owa/packages/roosterjs-content-model-dom/lib/modelApi/editing/runEditSteps.ts:14
at webpack://owa/packages/roosterjs-content-model-plugins/lib/edit/keyboardEnter.ts:42
at webpack://owa/packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts:40
at webpack://owa/packages/roosterjs-content-model-core/lib/editor/Editor.ts:181
at …
> Add a null check in getListAnnounceData

- packages/roosterjs-content-model-core/lib/corePlugin/cache/CachePlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/CachePluginTest.ts
- packages/roosterjs-content-model-types/lib/editor/EditorOptions.ts
In a previous change (#2975 ) I added paragraph map feature. However I found that this has some side effect to test code that causes paragraph has a marker value which is order-sensitive. So in this change I'm adding an option for this feature and by default it is off.
> Do not enable paragraph map by default

- packages/roosterjs-content-model-dom/lib/domToModel/processors/linkProcessor.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/linkProcessorTest.ts
In my previous pr (#2972 ) I added support to empty anchor. However a scenario is missed: if the empty anchor is in selection, we should also mark it as selected. So fix it in this PR.
> Check selection for empty anchor

- packages/roosterjs-content-model-dom/lib/modelApi/editing/retrieveModelFormatState.ts
Fixes the suffix check in cases where to avoid situations where `px.indexOf('px')` might return -1 making the test pass in a wrong scenario.
> Fix suffix check

- packages/roosterjs-content-model-dom/lib/domToModel/processors/tableProcessor.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/tableProcessorTest.ts
- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/CellResizer.ts
- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableMover.ts
- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableResizer.ts
- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/utils/getTableFromContentModel.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
- packages/roosterjs-content-model-plugins/test/tableEdit/tableResizerTest.ts
- packages/roosterjs-content-model-types/lib/context/EditorContext.ts
About #2985 , if there is padding in table cell, when rewrite with content model, table size will grow.
This is because when we recalculate table size, padding is not included. This can be solved by adding style `box-sizing: border-box`.
But actually, in most cases we don't need to recalculate table, and keep it not changed. We only need to recalculate table size when table is being resized.
So add a new property `recalculateTableSize` to EditorContext, and only set it to true when start to resize table
> Fix #2985: Do not recalculate table size unless required

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
When onBlur event happens, check if the editor is disposed and if the image is in editing state, before applying format to image
> Check editor disposed before executing function when on blur

- packages/roosterjs-content-model-core/lib/coreApi/setDOMSelection/setDOMSelection.ts
- packages/roosterjs-content-model-core/lib/coreApi/setDOMSelection/toggleCaret.ts
- packages/roosterjs-content-model-core/lib/coreApi/switchShadowEdit/switchShadowEdit.ts
- packages/roosterjs-content-model-core/test/coreApi/switchShadowEdit/switchShadowEditTest.ts
#2984, Safari will show a ghost caret when doing shadow edit, so let's hide it.
> Fix #2984 Hide caret for shadow edit

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
When cropping an image do not handle mouse down event, since the user can click at the overlay of the cropped image making image be edited twice and lose the correct selection. Also verify if there is an image being edited before applying the format when the editor loses focus. 
Before: 
After:
> Crop image in context menu

- packages/roosterjs-content-model-core/lib/corePlugin/entity/entityDelimiterUtils.ts
- packages/roosterjs-content-model-core/test/corePlugin/entity/entityDelimiterUtilsTest.ts
Repro:
```html
<ol start="1"><li><div style="margin: 0px;">test <span class="entityDelimiterBefore" style="font-family: Calibri; font-size: 11pt; color: rgb(0, 0, 0);">​</span><span class="_Entity _EType_OWALink _EId_OWALink _EReadonly_1" contenteditable="false"><span>ENTITY</span></span><span class="entityDelimiterAfter" style="font-family: Calibri; font-size: 11pt; color: rgb(0, 0, 0);">​</span></div></li></ol>
```
Press ENTER.
Expect: Go to next line and generate list item "2."
Actual: Nothing happens
This is in entityDelimiter code, it incorrectly retrieve the parent block using a wrong index.
Actually, when parent block group type is ListItem, we should not handle it since it will be handled by common enter handler code
> Fix 341291: Enter key does not work after an inline entity under a list

- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableMover.ts
[Bug 338766](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/338766): [Mail] Font/Font size should not be displayed blank after dragging a table or picture
This change fix the table part. For dragging a picture, it need to be covered by the whole drag-and-drop design, which is not in plan yet.
For table, after drop, we already put a selection marker in the first cell, so we just need to correctly select it.
> Fix 338766

- packages/roosterjs-content-model-api/lib/publicApi/format/getFormatState.ts
- packages/roosterjs-content-model-api/test/publicApi/format/getFormatStateTest.ts
- packages/roosterjs-content-model-core/lib/editor/core/DOMHelperImpl.ts
- packages/roosterjs-content-model-core/test/editor/core/DOMHelperImplTest.ts
- packages/roosterjs-content-model-dom/lib/modelApi/editing/retrieveModelFormatState.ts
- packages/roosterjs-content-model-dom/test/modelApi/editing/retrieveModelFormatStateTest.ts
- packages/roosterjs-content-model-types/lib/parameter/DOMHelper.ts
[Bug 315302](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/315302): Re: Monarch Feedback 🐞 When trying to use the Format Painter, the actions that it takes are the opposite of the expected behavior.   Expected: when ...
This is because some content (e.g. copilot generated content) does not have any format in it. Today when we see this kind of content we will fallback to the default format. So the font picker will show a wrong font and size.
To fix this, we will fallback to computed style of editor container instead. So add a new API in DOMHelper to get computed style of an element. Then pass domHelper into `retrieveModelFormatState` and use it to get computed style of editor container.
> Fix 315302

- packages/roosterjs-content-model-api/test/publicApi/format/getFormatStateTest.ts
- packages/roosterjs-content-model-dom/lib/domToModel/processors/knownElementProcessor.ts
- packages/roosterjs-content-model-dom/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/formatContainerProcessorTest.ts
- packages/roosterjs-content-model-dom/test/endToEndTest.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/ContentModelBlockFormat.ts
When DIV has id, use `FormatContainer` instead of `Paragraph` to represent it in Content Model.
- If there is only one sub paragraph under format container, it will fallback to paragraph with id
- If there are multiple child blocks under format container, keep format container with id so id won't lose or duplicated.
> Use FormatContainer to represent DIV with id

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
When setContent event happens and the selection is an image, clean the image edit state. Therefore, when the undo action happens the styles for hide the cursor will be removed. 
Fix in OWA:
> Clean image edit when undo

- demo/scripts/controlsV2/options/demoUndeletableAnchorParser.ts
- demo/scripts/controlsV2/sidePane/presets/PresetPane.tsx
- demo/scripts/controlsV2/sidePane/presets/allPresets/Preset.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/allPresets.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/imagePresets.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/listPresets.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/paragraphPresets.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/tablePresets.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/textPresets.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/undeleteablePresets.ts
Add a preset for undeleteable content to help testing.
Also do minor refactor to reorganize some type in demo site.
> Demo site: Add preset content for undeleteable anchor

- packages/roosterjs-content-model-api/lib/index.ts
- packages/roosterjs-content-model-api/lib/modelApi/common/queryContentModelBlocks.ts
- packages/roosterjs-content-model-api/lib/publicApi/utils/createEditorContextForEntity.ts
- packages/roosterjs-content-model-api/lib/publicApi/utils/formatSegmentWithContentModel.ts
- packages/roosterjs-content-model-api/test/modelApi/common/queryContentModelBlocksTest.ts
- packages/roosterjs-content-model-api/test/publicApi/utils/createEditorContextForEntityTest.ts
- versions.json
Bump `roosterjs-content-model-api` to 9.28.0 to add https://github.com/microsoft/roosterjs/pull/3032
> [Hot fix] Bump RoosterJS Content Model Api

- packages/roosterjs-content-model-plugins/lib/edit/tabUtils/handleTabOnParagraph.ts
- packages/roosterjs-content-model-plugins/test/edit/keyboardTabTest.ts
- packages/roosterjs-content-model-plugins/test/edit/tabUtils/handleTabOnParagraphTest.ts
When the selection is collapsed and the cursor is at the start of a paragraph, the `handleTabOnParagraph` function will add 4 spaces instead of calling the `setModelIndention` function.
> Do not indent on TAB

- packages/roosterjs-content-model-dom/lib/domUtils/style/normalizeFontFamily.ts
- packages/roosterjs-content-model-dom/test/domUtils/style/normalizeFontFamilyTest.ts
In #3038, I'm add quotes to font names if need. However, it only check double quote for existing quote in font family, and missed single quotes. Here is a fix to check single quote as well. It can fix the case if font is like
```
'Corbel','Skia',sans-serif
```
> Fix regression: If font family already has single quote, keep it

- packages/roosterjs-content-model-core/lib/override/listMetadataApplier.ts
- packages/roosterjs-content-model-core/test/overrides/listMetadataApplierTest.ts
If the thread items count does not count the list depth, parse the list number as 1, so it does not return negative number as listNumber. 
[369096](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/369096)
> Do not parse negative number in ListStyles

- demo/scripts/controlsV2/demoButtons/exportContentButton.ts
- demo/scripts/controlsV2/mainPane/MainPane.scss
- demo/scripts/controlsV2/mainPane/MainPane.tsx
- demo/scripts/controlsV2/options/defaultModelToDomOption.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/allPresets.ts
- demo/scripts/controlsV2/sidePane/presets/allPresets/paragraphPresets.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/context/createModelToDomContext.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/utils/stackFormat.ts
- packages/roosterjs-content-model-dom/test/modelToDom/context/createModelToDomContextTest.ts
- packages/roosterjs-content-model-types/lib/context/ModelToDomOption.ts
- packages/roosterjs-content-model-types/lib/context/ModelToDomSettings.ts
[Bug 309357](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/309357): HTML emails have inconsistent paragraph spacing when forwarded
It is possible we add some global CSS style after generating HTML from editor. It can cause the HTML style changed by the global CSS. So we need to let editor be aware of such global CSS, so it can generate HTML accordingly.
For example, we can add such CSS to HTML:
```html
<style>
p { margin-top:0; margin-bottom:0}
</style>
```
And inside editor, if we have a `<P>` with the same style, there is no problem. However if there is `<P>` without any style, we expect it to show margins, but the margins will be removed by the CSS above. So in that case we need to explicitly add inline CSS to P to maintain its margins, like:
```html
<p …
```
> Fix 309357

- demo/scripts/controlsV2/demoButtons/formatPainterButton.ts
The original issue (#3063) can happen to any button that does not focus into editor in Firefox. So add a focus call in the button handler in demo site code.
> Fix #3063: focus to editor when click format painter button

- packages/roosterjs-content-model-plugins/lib/edit/deleteSteps/deleteParagraphStyle.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/test/edit/deleteSteps/deleteParagraphStyleTest.ts
- packages/roosterjs-content-model-plugins/test/edit/keyboardDeleteTest.ts
Sometimes when paste some content that has styles on paragraph, it is hard to remove those styles. This change handles delete operation, and at the last, check if nothing is deleted, try to delete styles on current paragraph if any, so that those styles can be deleted.
> Fix #3087 Delete paragraph styles when there is nothing else to be deleted

- packages/roosterjs-content-model-dom/lib/formatHandlers/block/directionFormatHandler.ts
- packages/roosterjs-content-model-dom/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model-dom/test/formatHandlers/block/directionFormatHandlerTest.ts
- packages/roosterjs-content-model-dom/test/modelToDom/handlers/handleTableTest.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/ContentModelTableFormat.ts
The style `direction: RTL` does move the table to the right, so use `justifySelf:flex-end`.
> Fix 366527- Support RTL on Table 

- packages/roosterjs-content-model-plugins/lib/autoFormat/numbers/transformOrdinals.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/numbers/transformOrdinalsTest.ts
In English the suffix for ordinal numbers -st, -nd, -rd, and -th are applied based on the last digit of the number, except for 11,12,13. 
- Numbers ending in 1 → -st (except 11 → 11th)
- Numbers ending in 2 → -nd (except 12 → 12th)
- Numbers ending in 3 → -rd (except 13 → 13th)
- All others →-th
> Fix superscript rule 

- packages/roosterjs-content-model-api/lib/modelApi/list/setListType.ts
- packages/roosterjs-content-model-api/test/modelApi/list/setListTypeTest.ts
[Bug 380860](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/380860): Re: Monarch Feedback 🐞 - Mail - In mail editor, list buttons behave unexpectedly. If my IP is in a bulleted list and I press the numbering button, it removes...
When switch list type, we should let the list use the list type according to its list level. So let's set the property `applyListStyleFromLevel` onto list level metadata then further code will update format from metadata and change list style.
> Fix 380860

- demo/scripts/controlsV2/demoButtons/exportContentButton.ts
- packages/roosterjs-content-model-core/lib/command/exportContent/exportContent.ts
- packages/roosterjs-content-model-core/test/command/exportContent/exportContentTest.ts
- packages/roosterjs-content-model-types/lib/enum/ExportContentMode.ts
Today in `exportContent` API, we support 3 modes:
- `HTML`
- `PlainText`
- `PlainTextFast`
For `HTML`, we need to clone a content model and then convert it to DOM, then get HTML. When content is long enough, this will be slow.
In this PR I'm adding a new mode `HTMLFast`, it directly clone the existing DOM tree from editor then pass it to plugins, and do dark mode transform if need. This is the same process with roosterjs v8. In theory this can replace the default `HTML` mode unless there is special output options. So add this one to be coexisting with `HTML` mode so we can test it and run it with a flight.
> Support 'HTMLFast' mode when get HTML

- packages/roosterjs-content-model-dom/lib/modelApi/editing/mergeModel.ts
- packages/roosterjs-content-model-dom/test/modelApi/editing/mergeModelTest.ts
[Bug 276282](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/276282): [Format]Unable to paste text into table when both text and table are set numbering/bullets
When paste list and try to merge with existing list, do not search beyond table.
> Fix 276282

- packages/roosterjs-content-model-api/test/publicApi/link/insertLinkTest.ts
- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/lib/corePlugin/undo/UndoPlugin.ts
- packages/roosterjs-content-model-core/lib/editor/Editor.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/undo/UndoPluginTest.ts
- packages/roosterjs-content-model-core/test/editor/EditorTest.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/applyChange.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/checkEditInfoState.ts
- packages/roosterjs-content-model-types/lib/event/ContentChangedEvent.ts
1. Add a new property `skipUndo` in `ContentChangedEvent`
2. When this property is true, UndoPlugin will not add undo snapshot / set has new content for this event
3. When ContentChangedEvent is triggered due to the following reasons, set this property to true
- Switch color mode
- Keyboard input (to follow the existing behavior)
4. When add image editing border, set this property to true, so no need to add undo snapshot for image editing border
5. When remove image editing border, check if image is edited since current border is added. If not, do not add undo snapshot
> Do not add undo snapshot from ImageEdit plugin if image is not changed

- demo/scripts/controlsV2/sidePane/MarkdownPane/MarkdownPane.tsx
- packages/roosterjs-content-model-markdown/lib/index.ts
- packages/roosterjs-content-model-markdown/lib/markdownToModel/convertMarkdownToContentModel.ts
- packages/roosterjs-content-model-markdown/lib/markdownToModel/processor/markdownProcessor.ts
- packages/roosterjs-content-model-markdown/lib/markdownToModel/types/MarkdownOptions.ts
- packages/roosterjs-content-model-markdown/lib/markdownToModel/types/MarkdownToModelOptions.ts
- packages/roosterjs-content-model-markdown/test/markdownToModel/convertMarkdownToContentModelTest.ts
- packages/roosterjs-content-model-markdown/test/markdownToModel/processor/markdownProcessorTest.ts
Current markdown parser will always ignore empty lines. But actually if there are multiple empty lines, we should keep one.
This change introduces 3 empty line modes:
- preserve: Preserve empty lines, unless it is right next to list, quote, table
- remove: Remove all empty lines (current behavior)
- merge: If there are multiple empty lines, keep one (default)
> Support different options for empty line mode in mark down

- packages/roosterjs-content-model-core/lib/coreApi/setContentModel/setContentModel.ts
- packages/roosterjs-content-model-core/test/coreApi/setContentModel/setContentModelTest.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/handlers/handleParagraph.ts
1. When convert model to DOM, use independent document to create element. We are expecting this can reduce some cost of operating DOM elements before it is appended into the main DOM tree body
2. When handle paragraph, first prepare the whole paragraph element and make it is ready, and finally insert into DOM tree. This can reduce the count of DOM mutation
> Improve handleParagraph function

- packages/roosterjs-content-model-api/lib/modelApi/block/toggleModelBlockQuote.ts
- packages/roosterjs-content-model-api/test/modelApi/block/toggleModelBlockQuoteTest.ts
- packages/roosterjs-content-model-dom/lib/modelApi/editing/getClosestAncestorBlockGroupIndex.ts
- packages/roosterjs-content-model-dom/lib/modelApi/selection/collectSelections.ts
FormatContainer can be used to other elements other than blockquotes. When toggling blockquote in format containers that are not blockquotes, search for the selected elements inside the container and only apply blockquote to theses selected elements. 
Before: 
After:
> Toggle blockquote in Format Container

- packages/roosterjs-content-model-core/lib/editor/core/createEditorCore.ts
- packages/roosterjs-content-model-core/test/editor/core/createEditorCoreTest.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/test/edit/keyboardDeleteTest.ts
- packages/roosterjs-content-model-types/lib/parameter/EditorEnvironment.ts
Fix auto-capitalization for iOS by allowing browser to handle first character deletion
The Content Model intercepts delete detection when deleting the first character, which prevents the system browser from applying keyboard auto-capitalization.
When deleting the first character (i.e., offset = 1) on iOS, allow the browser to handle the deletion.
When offset = 0, delete detection is still handled by the Content Model. In my testing, other styles can still be cleared correctly by the Content Model at that point.
#3111 #3081
> Fix auto-capitalization for iOS 

- packages/roosterjs-content-model-core/lib/coreApi/setContentModel/setContentModel.ts
- packages/roosterjs-content-model-core/test/coreApi/setContentModel/setContentModelTest.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/handlers/handleParagraph.ts
Reverts microsoft/roosterjs#3130
This change causes the following issues:
1. For implicit paragraph, the parent block is not correctly assigned into context.regularSelection when convert model to dom
2. Because we delay appending paragraph container after handling all segments, in onNodeCreated for segment, if it wants to read computed styles, it will not work correctly
Given the above issues, I decide to revert this change.
> Revert "Improve handleParagraph function"

- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/test/edit/EditPluginTest.ts
We’ve observed that iOS maintains internal text-input state (e.g., keyboard auto-capitalization). When we intercept Backspace with preventDefault(), that state can incorrectly. 
1. Adding a callback to delegate Backspace to the browser.
Our previous PR already fixed the issue where the system didn’t handle backspace when 'offset == 1'. However, since 'offset == 0' is still handled by the Content Model, the system’s internal state becomes inconsistent, which leads to auto-capitalization being triggered incorrectly.
> Restore iOS auto-capitalization by delegating Backspace to the browser

- .vscode/extensions.json
- demo/scripts/controlsV2/mainPane/MainPane.tsx
- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionState.ts
- demo/scripts/controlsV2/sidePane/editorOptions/Plugins.tsx
- packages/roosterjs-content-model-core/lib/corePlugin/domEvent/DOMEventPlugin.ts
- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/types/ImageEditOptions.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/imageEditUtils.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/updateWrapper.ts
- packages/roosterjs-content-model-plugins/lib/index.ts
- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/TableMover.ts
- packages/roosterjs-content-model-plugins/lib/touch/TouchPlugin.ts
- packages/roosterjs-content-model-plugins/lib/utils/getNodePositionFromEvent.ts
- packages/roosterjs-content-model-plugins/test/edit/EditPluginTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/imageEditUtilsTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/updateWrapperTest.ts
- packages/roosterjs-content-model-types/lib/event/MouseEvent.ts
- packages/roosterjs-content-model-types/lib/event/PluginEvent.ts
- packages/roosterjs-content-model-types/lib/event/PluginEventType.ts
- packages/roosterjs-content-model-types/lib/event/PointerEvent.ts
- packages/roosterjs-content-model-types/lib/index.ts
- versions.json
> Bump version to 9.37.0

- packages/roosterjs-content-model-plugins/lib/autoFormat/horizontalLine/checkAndInsertHorizontalLine.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/horizontalLine/insertHorizontalLineIntoModelTest.ts
Do not trigger horizontal lines on lists. 
Before:
After:
> [Horizontal line] Do not trigger on list

- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-content-model-core/lib/editor/core/DOMHelperImpl.ts
- packages/roosterjs-content-model-core/lib/editor/core/createEditorCore.ts
- packages/roosterjs-content-model-core/test/editor/core/DOMHelperImplTest.ts
- packages/roosterjs-content-model-types/lib/editor/ExperimentalFeature.ts
Today when we extract HTML from editor using ExportHTMLFast feature, we first clone a DOM tree, then pass it to plugins to do clean up. However, if plugin wants to set src of image, it will trigger an image downloading service call. This is a browser behavior.
In this change, I create a new experimental feature `CloneIndependentRoot`, when set, we will create an independent HTML document using `document.implementation.createHTMLDocument()`, then call `importNode()` to clone the DOM tree, this makes the cloned tree to be under this independent document context, so setting src of IMG won't really download it.
> Support CloneIndependentRoot feature

- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-plugins/lib/edit/EditPlugin.ts
1. In table, when press TAB key to move focus to the next cell, if the cell is empty, collapse the selection
2. In last table cell, when press TAB key, no matter if there is text selected, always create a new table row
Before:
After:
> Improve table selection
