- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
If it's firefox do not open new window as firefox already handles it.
> Add check to current browser before opening new window. 

- packages/roosterjs-editor-plugins/lib/PasteManager/PasteManager.ts
RegEx with "global" option will remember last match result and impact next matching.
Here I need to remove this option since each time I expect it match the whole string.
> Fix a global regex issue

- packages/roosterjs-editor-api/lib/format/cacheGetListElement.ts
- packages/roosterjs-editor-api/lib/format/toggleBlockQuote.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/index.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/utils/applyFormat.ts
- packages/roosterjs-editor-plugins/lib/PasteManager/PasteManager.ts
- packages/roosterjs-editor-plugins/lib/TabIndent/TabIndent.ts
- packages/roosterjs-editor-types/lib/editor/PluginEventType.ts
- packages/roosterjs-plugin-watermark/LICENSE
- packages/roosterjs-plugin-watermark/README.md
- packages/roosterjs-plugin-watermark/lib/Watermark.ts
- packages/roosterjs-plugin-watermark/lib/index.ts
- packages/roosterjs-plugin-watermark/package.json
- packages/roosterjs-plugin-watermark/tsconfig.json
- sample/sample.htm
- sample/scripts/initOptions.ts
Implement a watermark plugin
Other changes:
1. Fix bug "Editor.updateSelection()" always returns false
2. export two utils for undo snapshot: buildSnapshot, restoreSnapshot
3. optimize format
> Watermark plugin

- packages/roosterjs-editor-api/lib/cursor/queryNodesWithSelection.ts
- packages/roosterjs-editor-api/lib/format/cacheGetListElement.ts
- packages/roosterjs-editor-api/lib/format/cacheGetListState.ts
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-api/lib/format/removeLink.ts
- packages/roosterjs-editor-api/lib/format/setImageAltText.ts
- packages/roosterjs-editor-api/lib/format/toggleBlockQuote.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/utils/isDocumentPosition.ts
- packages/roosterjs-editor-dom/lib/utils/splitParentNode.ts
- packages/roosterjs-editor-dom/lib/utils/wrapAll.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/ContentEdit.ts
- packages/roosterjs-editor-plugins/lib/PasteManager/PasteManager.ts
- packages/roosterjs-editor-types/lib/format/ListState.ts
1. Fix a javascript error when toggle blockquote in wrapAll()
2. Redesign the strategy for togggleBockQuote for bullets/numbering
3. Redesign the strategy for keyboard event in blockquote
> Fix blockQuote functionality

- package.json
- packages/roosterjs-editor-api/lib/format/createLink.ts
- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
- packages/roosterjs-editor-plugins/lib/PasteManager/PasteManager.ts
- packages/roosterjs-editor-types/lib/editor/ContentChangedEvent.ts
Also fix other places where ContentChangedEvent is triggered but source is not set.
> Trigger event when create link

- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-types/lib/editor/PluginEventType.ts
- packages/roosterjs-plugin-image-resize/LICENSE
- packages/roosterjs-plugin-image-resize/README.md
- packages/roosterjs-plugin-image-resize/lib/ImageResizePlugin.ts
- packages/roosterjs-plugin-image-resize/lib/index.ts
- packages/roosterjs-plugin-image-resize/package.json
- packages/roosterjs-plugin-image-resize/tsconfig.json
- packages/roosterjs/lib/index.ts
- packages/roosterjs/package.json
- sample/sample.htm
- sample/scripts/initOptions.ts
- sample/scripts/plugins/ShowFormatState.ts
- sample/scripts/sample.ts
This is a new plugin to support resizing inline image.
It will put into a new package "roosterjs-plugin-image-resize".
> Add ImageResizePlugin

- packages/roosterjs-editor-api/lib/format/cacheGetHeaderLevel.ts
- packages/roosterjs-editor-api/lib/format/execFormatWithUndo.ts
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-api/lib/format/toggleBlockQuote.ts
- packages/roosterjs-editor-api/lib/format/toggleHeader.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-types/lib/format/FormatState.ts
- sample/sample.htm
- sample/scripts/initFormatBar.ts
- sample/scripts/plugins/ShowFormatState.ts
Support toggleHeader() API.
Refactor some existing code (execFormatWithUndo, toggleBlockQuote) for better code reusing.
> New API toggleHeader

- packages/roosterjs-editor-api/lib/cursor/CursorData.ts
- packages/roosterjs-editor-api/lib/cursor/cacheGetCursorEventData.ts
- packages/roosterjs-editor-api/lib/cursor/getNodeAtCursor.ts
- packages/roosterjs-editor-api/lib/cursor/isSelectionCollapsed.ts
- packages/roosterjs-editor-api/lib/cursor/queryNodesWithSelection.ts
- packages/roosterjs-editor-api/lib/cursor/replaceRangeWithNode.ts
- packages/roosterjs-editor-api/lib/cursor/replaceTextBeforeCursorWithNode.ts
- packages/roosterjs/lib/createEditor.ts
Abandon the original PR and separate the documentation into multiple checkins.
> Add comments for exported functions in roosterjs-editor-api/lib/cursor and roosterjs/

- packages/roosterjs-editor-api/lib/cursor/CursorData.ts
- packages/roosterjs-editor-api/lib/cursor/replaceTextBeforeCursorWithNode.ts
- packages/roosterjs-editor-api/lib/index.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/ContentEdit.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/ContentEditFeatures.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/autoBullet.ts
> Implement auto bullet.

- package.json
- packages/roosterjs-plugin-image-resize/lib/ImageResize.ts
> Fixed ImageResize plugin's ExtractContent/getContent handler

- package.json
- packages/roosterjs-plugin-image-resize/lib/ImageResize.ts
Added option to allow image to be bypass ImageResize plugin. Also fixed extra bottom spacing between the image and resize box.
> A few improvements for ImageResize plugin

- package.json
- packages/roosterjs-editor-dom/lib/blockElements/BlockElement.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/ContentTraverser.ts
#91 
function getNextPreviousInlineElement() needs to respect the isNext param when inlineElement is PartialInlineElement.
Also fix a null-check issue in ContentTraverser.
> Fix issue 91

- packages/roosterjs-editor-dom/lib/selection/Position.ts
1. Add support for iOS/Android user agent
2. Improve getRect performance. Adding a span in the DOM should be used as a last resort since it's really not efficient to change the dom for a rect computation.
Tested on Mobile Safari on iOS 11.4 and Chrome for Android on versions 4 and 8
> Improve get cursor performance for mobile safari

- README.md
- package.json
> Update to 6.15.1

- package.json
- packages/roosterjs-editor-plugins/lib/HyperLink/HyperLink.ts
- packages/roosterjs-editor-plugins/lib/index.ts
> Added onLinkClick option to HyperLink plugin

- publish/samplesite/scripts/controls/MainPane.tsx
- publish/samplesite/scripts/controls/MainPaneBase.tsx
- publish/samplesite/scripts/controls/ribbon/RibbonButton.tsx
- publish/samplesite/scripts/controls/sidePane/formatState/FormatStatePlugin.ts
> Fix typo in sample site code

- package.json
We'll release dark mode under this tag temporarily, and once we're done we'll merge the changes back in.
> Update package.json to have a tagged version number

- package.json
Version will now match roosters public version, but, we'll cut a darkmode version of the same package + dark mode changes.
> Update version with latest darkmode changes

- packages/roosterjs-editor-core/lib/coreAPI/insertNode.ts
@Adjective-Object raised some concerns in #225, but that was literally right after I closed the PR. The actual changes went in with #223. I opened this PR to address those concerns.
> Address comments raised in #225 but not addressed

- packages/roosterjs-editor-core/lib/coreAPI/insertNode.ts
In previous check in there is a potential javascript error in insertNode() function when the "option" parameter. This change fix the error.
> Fix a js error in insertNode

- package.json
Fix a js error in insertNode (#229)
Address comments raised in #225 but not addressed (#227)
Refactor ReplaceWithNode to use the editor core API (#223)
Track content changed events and report up to PickerPluginDataProvider (#222)
> Version bump to 7.2.0

- .npmrc
- .vscode/extensions.json
- package.json
- packages/roosterjs-editor-core/lib/coreAPI/select.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/BodyScoper.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/ContentTraverser.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/ContentEdit.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/ContentEditFeatures.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/insertLineBeforeStructuredNodeFeature.ts
- packages/roosterjs-editor-types/package.json
- publish/samplesite/scripts/controls/ribbon/RibbonButton.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/Plugins.tsx
- tools/build.js
Merge from master + version bump
> 7.2.1-darkmode.0

- package.json
Includes latest defautlt format bugfix
> 7.2.5-darkmode.2

- .npmrc
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-api/lib/utils/processList.ts
- packages/roosterjs-editor-core/lib/coreAPI/attachDomEvent.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
These changes consist of 2 parts:
1) Merge in the current state of master into darkmode-alpha
2) Fix issues with color normalization by more properly checking and resetting attribute related data, and making our check for set/unset data attributes more robust. Those changes are the only ones in Editor.ts.
> Merge master changes + Improve color normalization

- packages/roosterjs-plugin-picker/lib/PickerDataProvider.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
Deploy Link: https://outlook-sdf.office.com/mail/?branch=TISHAPC-u-titrongt-testRoosterNarratePickerSuggestions
> [PickerPlugin] Set ariaOwns and ariaActiveDescendant attributes

- package.json
- packages/roosterjs-editor-core/lib/coreAPI/attachDomEvent.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/eventApi/isCharacterValue.ts
- packages/roosterjs-editor-core/lib/index.ts
- packages/roosterjs-editor-dom/lib/selection/createRange.ts
- packages/roosterjs-editor-dom/lib/test/selections/createRangeTest.ts
- packages/roosterjs-plugin-picker/lib/PickerDataProvider.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
Merge latest state of master and bump version.
> Roosterjs darkmode 7.3.0-darkmode.0

- publish/samplesite/scripts/controls/BuildInPluginState.ts
- publish/samplesite/scripts/controls/MainPane.tsx
- publish/samplesite/scripts/controls/MainPaneBase.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/Code.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/ButtonsCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/CodeElement.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/ContentEditCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/DefaultFormatCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/EditorCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/HyperLinkCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/Import.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/PickerPluginCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/PluginsCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/SimplePluginCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/WatermarkCode.ts
Add a button "export to codepen" in demo site, so user can change options and use this button to easily try the code in codepen.
> Support export code to codepen from demo site

- package.json
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
This is a temp fix. I'll make a full fix later.
> Revert #298 since it breaks IE

- package.json
- packages/roosterjs-editor-core/lib/coreAPI/attachDomEvent.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
> 7.4.1-darkmode.0

- packages/roosterjs-editor-core/lib/corePlugins/CopyPlugin.ts
- packages/roosterjs-editor-core/lib/darkMode/getColorNormalizedContent.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
- packages/roosterjs-editor-core/lib/index.ts
- packages/roosterjs-editor-core/lib/interfaces/EditorCore.ts
I created a new plugin that intercepts the copy process so when copying from dark editors, you get the normalized content.
> Fix for copying from dark mode

- package.json
Includes some changes to copy/paste and to undo to better the behavior.
> bump to include new dark mode stuff

- packages/roosterjs-editor-api/lib/format/clearBlockFormat.ts
API clearBlockFormat will preserve data-* attribute
> Fix #328 Preserve data- attribute when clear format

- packages/roosterjs-editor-core/lib/corePlugins/DOMEventPlugin.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/lib/editor/createEditorCore.ts
- packages/roosterjs-editor-core/lib/interfaces/EditorCore.ts
- packages/roosterjs-editor-core/lib/interfaces/EditorOptions.ts
- packages/roosterjs-editor-types/lib/event/PluginDomEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEventType.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-plugin-picker/lib/PickerDataProvider.ts
- packages/roosterjs-plugin-picker/lib/PickerPlugin.ts
- publish/samplesite/scripts/controls/MainPane.scss
- publish/samplesite/scripts/controls/editor/Editor.scss
- publish/samplesite/scripts/controls/editor/Editor.tsx
- publish/samplesite/scripts/controls/sidePane/eventViewer/EventViewPane.tsx
Add a scroll event, trigger from DOMEventPlugin.
This can help simplify OWA scroll handling logic and get rid of "ScrollAdapter"
> Add Scroll event

- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-types/lib/event/DarkModeChangedEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEventType.ts
- packages/roosterjs-editor-types/lib/index.ts
- publish/samplesite/scripts/controls/sidePane/eventViewer/EventViewPane.tsx
Add a new event DarkModeChangedEvent
> add DarkModeChangedEvent

- package.json
- packages/roosterjs-editor-dom/lib/utils/adjustNodeInsertPosition.ts
Fix null reference exception in adjustInsertPosition.
> Fix null reference exception in adjustInsertPosition.

- packages/roosterjs-editor-plugins/lib/Paste/fragmentHandler.ts
- packages/roosterjs-editor-plugins/lib/Paste/officeOnlineConverter/constants.ts
- packages/roosterjs-editor-plugins/lib/Paste/officeOnlineConverter/convertPastedContentFromWordOnline.ts
- packages/roosterjs-editor-plugins/lib/test/fragmentHandlerTest.ts
> One note bullet paste

- packages/roosterjs-editor-api/lib/format/insertImage.ts
Insert an image with URL is a common use case too.
> New API: insertImage (for url).

- packages/roosterjs-editor-api/lib/format/clearBlockFormat.ts
- packages/roosterjs-editor-api/lib/utils/processList.ts
- packages/roosterjs-editor-api/lib/utils/toggleTagCore.ts
- packages/roosterjs-editor-core/lib/darkMode/getColorNormalizedContent.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/table/VTable.ts
- packages/roosterjs-editor-dom/lib/utils/adjustNodeInsertPosition.ts
- packages/roosterjs-editor-dom/lib/utils/collapseNodes.ts
- packages/roosterjs-editor-dom/lib/utils/extractClipboardEvent.ts
- packages/roosterjs-editor-dom/lib/utils/fromHtml.ts
- packages/roosterjs-editor-dom/lib/utils/queryElements.ts
- packages/roosterjs-editor-dom/lib/utils/toArray.ts
- packages/roosterjs-editor-plugins/lib/ContentEdit/features/quoteFeatures.ts
- packages/roosterjs-plugin-image-resize/lib/ImageResize.ts
Add a toArray() method so that we can easily convert NodeCollection or other collection-like object to array.
> Wrap "[].slice.call" to toArray

- publish/samplesite/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
After my last change, the path for rooster.js file is no longer available. So we need to update it.
> Fix export to code pen not work issue

- package.json
- packages/roosterjs-cross-window/package.json
- packages/roosterjs-editor-plugins/lib/plugins/Entity/insertEntity.ts
- packages/roosterjs-html-sanitizer/package.json
- publish/samplesite/scripts/controls/BuildInPluginState.ts
- publish/samplesite/scripts/controls/editor/Editor.tsx
- publish/samplesite/scripts/controls/editor/EditorInstanceToggleablePlugins.ts
- publish/samplesite/scripts/controls/sidePane/apiPlayground/apiEntries.ts
- publish/samplesite/scripts/controls/sidePane/apiPlayground/insertEntity/InsertEntityPane.scss
- publish/samplesite/scripts/controls/sidePane/apiPlayground/insertEntity/InsertEntityPane.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/Plugins.tsx
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/PluginsCode.ts
- publish/samplesite/scripts/controls/sidePane/editorOptions/codes/SimplePluginCode.ts
- tools/build.js
1. Add Entity API page for demo site
2. Add a catch block in build script to ignore publish failure
3. Set the final version number for deprecated packages
> 7.13.0 Entity API and demo site change

- package.json
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-core/lib/corePlugins/CopyPlugin.ts
- packages/roosterjs-editor-core/lib/darkMode/normalizeContentColor.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-dom/lib/blockElements/NodeBlockElement.ts
- packages/roosterjs-editor-dom/lib/blockElements/StartEndBlockElement.ts
1. Fix #448 by partially revert the change.
2. Fix the dark mode transform logic for undo.
3. Add null checks for BlockElement.getTetxtContent()
> Fix darkmode regression

- .travis.yml
- karma.conf.js
- package.json
- packages/roosterjs-editor-api/lib/test/TestHelper.ts
- packages/roosterjs-editor-api/lib/test/format/clearFormatTest.ts
- packages/roosterjs-editor-api/lib/test/format/toggleBoldTest.ts
- packages/roosterjs-editor-api/lib/test/format/toggleItalicTest.ts
- packages/roosterjs-editor-api/lib/test/format/toggleUnderlineTest.ts
- packages/roosterjs-editor-api/lib/test/utils/processListTest.ts
- packages/roosterjs-editor-core/lib/test/coreApi/hasFocusTest.ts
- packages/roosterjs-editor-core/lib/test/editor/EditorTest.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/test/htmlSanitizer/getInheritableStylesTest.ts
- packages/roosterjs-editor-dom/lib/test/list/VListItemTest.ts
- packages/roosterjs-editor-dom/lib/test/list/VListTest.ts
- packages/roosterjs-editor-dom/lib/test/selections/getPositionRectTest.ts
- packages/roosterjs-editor-dom/lib/test/table/VTableTest.ts
- packages/roosterjs-editor-dom/lib/test/utils/getComputedStylesTest.ts
- yarn.lock
Recently Chrome often crashes when running test. So let's switch to use Firefox instead.
> Switch using Firefox for test

- package.json
Includes the new markdown features.
> 7.15.0 release

- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/corePlugins/copyPastePluginTest.ts
- packages/roosterjs-editor-dom/lib/index.ts
- packages/roosterjs-editor-dom/lib/selection/deleteSelectedContent.ts
- packages/roosterjs-editor-dom/test/selections/deleteSelectedContentTest.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
User reported that after cut, some extra content might be deleted.
This happens in this case ([ ] means the selection)
```
Li[ne 1
]Line 2
Line3
```
Expected result should be:
```
liLine2
Line3
```
But actually it becomes:
```
Li
Line3
```
In this change I rewrote the whole logic of deleting selected content so that all cases can be handled.
> Fix cut issue

- demo/scripts/controls/BuildInPluginState.ts
- demo/scripts/controls/editor/Editor.tsx
- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
- demo/scripts/controls/sidePane/editorOptions/codes/EditorCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/ExperimentalFeaturesCode.ts
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-api/lib/format/toggleBullet.ts
- packages/roosterjs-editor-api/lib/format/toggleNumbering.ts
- packages/roosterjs-editor-api/lib/utils/blockFormat.ts
- packages/roosterjs-editor-core/lib/corePlugins/LifecyclePlugin.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/corePlugins/lifecyclePluginTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-plugins/lib/plugins/CutPasteListChain/CutPasteListChain.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/Paste.ts
- packages/roosterjs-editor-types/lib/corePluginState/LifecyclePluginState.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/EditorOptions.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
Change existing useExperimentFeatures boolean flag to be a string array, so we can toggle each feature on/off
Add UI to toggle features in demo site.
> Provide a way to switch each experimental feature on/off for roosterjs

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- demo/scripts/controls/sidePane/eventViewer/EventViewPane.tsx
- package.json
- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/copyPastePluginTest.ts
- packages/roosterjs-editor-dom/lib/utils/extractClipboardEvent.ts
- packages/roosterjs-editor-plugins/lib/plugins/ImageResize/ImageResize.ts
- packages/roosterjs-editor-types/lib/browser/EdgeLinkPreview.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
- packages/roosterjs-editor-types/lib/index.ts
- packages/roosterjs-editor-types/lib/interface/ClipboardData.ts
- packages/roosterjs-editor-types/lib/interface/ExtractClipboardEventOption.ts
1. Support Edge Link Preview when paste
2. Put Edge Link Preview under a feature flag PasteWithLinkPreview
3. Put single direction image resize under a feature flag SingleDirectionResize
> 8.0.0-beta.16: support edge link preview

- packages/roosterjs-editor-core/lib/corePlugins/DOMEventPlugin.ts
> Fix image context menu

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
Fix inserter color in dark mode
> Fix inserter color in dark mode

- packages/roosterjs-editor-core/lib/coreApi/createPasteFragment.ts
- packages/roosterjs-editor-core/test/coreApi/createPasteFragmentTest.ts
The code for pasting didn't handle the two lines of plain text scenario. So rewrite the part to make sure it works correctly for all cases. Also update test case.
> Fix paste two lines plain text bug

- CODE_OF_CONDUCT.md
Match this template:
https://github.com/microsoft/repo-templates/blob/main/shared/CODE_OF_CONDUCT.md
> Add CODE_OF_CONDUCT to match template

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
> Fix table inserter for culture in RTL 

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
Today we set css width of the cell (td.style.width) when we resize table, but style.width only set the "**inner**" width of the cell which do not include the border and padding size. To solve this, we manually calculate these values by parsing the css style to get an offset value and do something like below to adjust the width:
`td.style.width = "${newWidth - offset}px"`
but this approach is bug prone in c/p scenario since the styles could in various format and in different unit such as pt instead of px (It is even possible to set border for only one cell making the border size not the same across all cells). Good thing is that we have the box-sizing property which can handle all of these logic automatically and set the cell width properly for us.
> Introduce box-sizing to resolve c/p table issues

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
A behavior in parity with Word
> Do not show inserter while left mouse button is pressed

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-core/lib/corePlugins/TypeInContainerPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/typeInContainerPluginTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
restore default style in a div after typed a semantic element
> bugfix(restore-default-style): fix restore default style

- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/ribbon/ribbonButtons.ts
Fix some javascript failure in demo site after CSP is enabled.
> Support TrustedType: Fix demo site

- package.json
- Shadow DOM Entity
- List Item bug fix
- Image resize bug fix
> Roosterjs 8.10.0

- packages/roosterjs-editor-plugins/test/TableResize/tableResizeTest.ts
Due to some unknown reasons, some tableResize test cases are failing
> Remove pixel comparison tests

- demo/scripts/controls/titleBar/TitleBar.tsx
Forget to update one url to github actions from my previous check in
> Update action url

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/autoLinkFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/autoLinkFeatureTest.ts
Add Tests to AutoLink Features.
> AutolinkFeature Tests

- package.json
> bump RoosterJS version to 8.11.4

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
This PR fixes an issue with Safari and Auto Bullet List Feature.
Refer to linked issue
> Fix listFeature Issue with Safari

- packages/roosterjs-editor-core/lib/corePlugins/TableSelection.ts
Fix issue when selecting text inside of a cell. Selection range was being modified which should not happen.
> Fix Selection Issue when selecting text inside of a Cell

- .github/workflows/build-and-deploy.yml
- packages/roosterjs-editor-core/test/coreApi/getPendableFormatStateTest.ts
- packages/roosterjs-editor-core/test/editor/newEditorTest.ts
- packages/roosterjs-editor-plugins/lib/plugins/CustomReplace/CustomReplace.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/autoLinkFeatureTest.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/cursorFeaturesTest.ts
Fix a bunch of test case issues
> Fix a bunch of test case issues

- package.json
Pull Requests:
#724
#725 
#728 
#729 
#730 
#732 
#733 
#735 
#736 
#737  
#738 
#743 
Modified Interfaces
packages/roosterjs-editor-types/lib/interface/IEditor.ts Updated
packages/roosterjs-editor-types/lib/interface/EditorCore.ts Updated
packages/roosterjs-editor-types/lib/interface/SelectionRangeEx.ts +
packages/roosterjs-editor-types/lib/interface/TableSelection.ts +
packages/roosterjs-editor-types/lib/interface/Coordinates.ts + 
packages/roosterjs-editor-types/lib/interface/VCell.ts Updated
packages/roosterjs-editor-types/lib/interface/TableFormat.ts Updated
> Bump RoosterJs to 8.14.0

- demo/scripts/tsconfig.json
- packages-ui/roosterjs-react/lib/index.ts
- packages-ui/roosterjs-react/package.json
- packages-ui/tsconfig.json
- tools/build.js
- tools/buildTools/buildAmd.js
- tools/buildTools/buildCommonJs.js
- tools/buildTools/buildDemo.js
- tools/buildTools/checkDependency.js
- tools/buildTools/common.js
- tools/buildTools/dts.js
- tools/buildTools/normalize.js
- tools/buildTools/pack.js
- tools/buildTools/publish.js
- tools/tsconfig.tslint.json
- webpack.config.js
- yarn.lock
- Add empty code file for roosterjs-react
- Fix build script to allow build/pack/publish roosterjs-react code
> RoosterJs-React step 1: fix build script

- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
- packages/roosterjs-editor-plugins/test/TableCellSelection/tableCellSelectionTest.ts
- packages/roosterjs-editor-plugins/test/TableSelection/tableSelectionTest.ts
Also changed the test file from TableSelectionTest to TableCellSelectionTest
> Add key event unit tests to TableCellSelection

- package.json
**Bug fixes:** 
- [Fix bug in shadowEditTableSelection](https://github.com/microsoft/roosterjs/pull/767)
- [Fix possible null when disposing the editor and table cell selecting](https://github.com/microsoft/roosterjs/pull/770)
- [Fix onFocus Event for TableSelection](https://github.com/microsoft/roosterjs/pull/771)
- [Fix table selection issue when leaving Shadow Edit](https://github.com/microsoft/roosterjs/pull/789)
**Features:**
- [Table Alignment](https://github.com/microsoft/roosterjs/pull/772)
- [Add a react wrapper for roosterjs](https://github.com/microsoft/roosterjs/pull/777)
- [RoosterJs-React step 1: fix build script](https://github.com/microsoft/roosterjs/pull/775)
- [Add a ribbon component to roosterjs-react](https://github.com/microsoft/roosterjs/pull/783)
- [Add more buttons …
> Bump RoosterJS version to 8.17

- packages-ui/roosterjs-react/lib/index.ts
- packages-ui/roosterjs-react/lib/utils/LocalizedStrings.ts
- packages-ui/roosterjs-react/lib/utils/getLocalizedString.ts
- packages-ui/roosterjs-react/lib/utils/index.ts
- packages-ui/roosterjs-react/package.json
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
- packages/roosterjs-editor-types/lib/interface/FormatState.ts
- tools/buildTools/dts.js
1. Fix dts tool to support export types from 3rd part library (fluent ui)
2. Add types and utils for localized strings
3. Add zoom scale and dark mode in FormatState
> Ribbon step 3: Get ready for more buttons

- demo/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
- demo/scripts/controls/sidePane/editorOptions/codes/PluginsCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/ReactEditorCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/RibbonButtonCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/RibbonCode.ts
- packages/roosterjs-editor-core/lib/coreApi/addUndoSnapshot.ts
Support send code to codepen to generate sample code for roostejs-react
> Roosterjs React step 8: Support generate demo code for roosterjs-react

- demo/index.html
avoiding 302 redirect for umd modules
> React & Fabric umd update for avoiding 302

- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/MainPaneBase.tsx
- demo/scripts/controls/sidePane/apiPlayground/vtable/VTablePane.tsx
#820 Demo site: content is not correctly persisted
Do not use React state to save content, use a regular member variable instead since state is working in async mode
#821 Demo site: Popout window can't pop back in when close popout window in safari
Use beforeunload event instead of unload event since Safari doesn't handle unload event well for child window
#822 Demo site: Warning shows when use VTable API 
Add keys, and add TBody when render
> Fix demo site bugs #820 #821 #822

- README.md
- tools/buildTools/buildCommonJs.js
- tools/reference.md
- add readme.md and license to roosterjs-react
- Remove "(Under development)" from readme file
> Add readme for roosterjs-react (#844)

- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableCellSelection/TableCellSelection.ts
Cut Copy was not working when we select the table with the table selector control and the performed a copy. This PR fixes this issue
> Fix Issue when selecting all table and trying to Copy

- demo/scripts/controls/ribbonButtons/tableEditOperations.ts
- packages/roosterjs-editor-dom/lib/table/VTable.ts
- packages/roosterjs-editor-dom/test/table/VTableTest.ts
- Select multiple columns 
- Click insert left or right
- The same amount of selected columns is inserted 
- Same behavior for rows
> Step 2 [Table Improvements]: Improve insert above, below, left and right

- packages/roosterjs-editor-dom/lib/blockElements/getBlockElementAtNode.ts
- packages/roosterjs-editor-dom/lib/inlineElements/NodeInlineElement.ts
- packages/roosterjs-editor-dom/lib/inlineElements/PartialInlineElement.ts
- packages/roosterjs-editor-dom/lib/inlineElements/applyTextStyle.ts
- packages/roosterjs-editor-dom/lib/inlineElements/getFirstLastInlineElement.ts
- packages/roosterjs-editor-dom/lib/inlineElements/getInlineElementAtNode.ts
- packages/roosterjs-editor-dom/lib/inlineElements/getInlineElementBeforeAfter.ts
- packages/roosterjs-editor-dom/lib/inlineElements/tsconfig.child.json
Enable strict mode for inlineElements
> Enable strict mode for inlineElements

- packages/roosterjs-editor-dom/lib/contentTraverser/BodyScoper.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/ContentTraverser.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/PositionContentSearcher.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/SelectionBlockScoper.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/SelectionScoper.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/TraversingScoper.ts
- packages/roosterjs-editor-dom/lib/contentTraverser/tsconfig.child.json
- packages/roosterjs-editor-dom/lib/utils/contains.ts
- packages/roosterjs-editor-types/lib/interface/IContentTraverser.ts
- packages/roosterjs-editor-types/lib/interface/IPositionContentSearcher.ts
Enable strict mode for ContentTraverser
> Enable strict mode for ContentTraverser

- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/ribbonButtons/tableAlignmentOperations.ts
- packages/roosterjs-editor-dom/lib/table/VTable.ts
- packages/roosterjs-editor-dom/test/table/VTableTest.ts
Select and align multiple cells. 
WIP: Unit tests
> [Table Improvements] Step 3 : Align multiple cells 

- package.json
- Improvements: 
[Dark Mode and UndoSnapshot: Improve color transformation](https://github.com/microsoft/roosterjs/pull/839)
[Dark Mode and UndoSnapshot: Prepare for content snapshot](https://github.com/microsoft/roosterjs/pull/840)
[Dark Mode and UndoSnapshot: Support content metadata in core API](https://github.com/microsoft/roosterjs/pull/841)
[Dark Mode and UndoSnapshot: Switch UndoPlugin to use Snapshot and ContentMetadata](https://github.com/microsoft/roosterjs/pull/842)
[Dark Mode and UndoSnapshot:  Switch UndoPlugin to use Snapshot and ContentMetadata](https://github.com/microsoft/roosterjs/pull/842)
[Dark Mode and UndoSnapshot: Hook new undo snapshot service in demo site](https://github.com/microsoft/roosterjs/pull/843)
[Add readme for …
> Bump RoosterJS  to v18.19.

- demo/scripts/controls/ribbonButtons/tableEditOperations.ts
- demo/scripts/controls/sidePane/apiPlayground/vtable/VTablePane.tsx
- packages/roosterjs-editor-core/lib/coreApi/selectTable.ts
- packages/roosterjs-editor-dom/lib/selection/Position.ts
- packages/roosterjs-editor-dom/lib/table/VTable.ts
- packages/roosterjs-editor-dom/test/table/VTableTest.ts
- packages/roosterjs-editor-types/lib/enum/TableOperation.ts
Add support to merge multiple cells with cell selection.
> [Table Improvements] Step 4 - Merge multiple cells 

- packages/roosterjs-editor-dom/lib/list/VList.ts
- packages/roosterjs-editor-dom/lib/list/VListChain.ts
- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/createVListFromRegion.ts
- packages/roosterjs-editor-dom/lib/list/getListTypeFromNode.ts
- packages/roosterjs-editor-dom/lib/list/getRootListNode.ts
- packages/roosterjs-editor-dom/lib/list/setListItemStyle.ts
- packages/roosterjs-editor-dom/lib/list/tsconfig.child.json
- packages/roosterjs-editor-dom/test/list/VListTest.ts
Enable strict mode for roosterjs-editor-dom/list
> Enable strict mode for roosterjs-editor-dom/list

- packages/roosterjs-editor-core/lib/coreApi/createPasteFragment.ts
> Copypaste is broken in IE

- packages/roosterjs-editor-core/lib/coreApi/tsconfig.child.json
- packages/roosterjs-editor-core/lib/corePlugins/tsconfig.child.json
- packages/roosterjs-editor-core/lib/editor/tsconfig.child.json
- packages/roosterjs-editor-core/tsconfig.child.json
> Prepare strict mode for core package

- demo/scripts/controls/sidePane/SidePane.tsx
> Fix memory leak in demo site

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-core/lib/corePlugins/TypeInContainerPlugin.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
Remove AlwaysApplyDefaultFormat experimental feature and mark it as deprecated.
> Remove experimental feature: AlwaysApplyDefaultFormat

- packages/roosterjs-editor-dom/lib/table/applyTableFormat.ts
The adaptiveFontColor was not being called in applyFormatTable, because the setColor function was being called with the wrong parameters.
> Add isDarkMode parameter

- package.json
- packages/roosterjs-editor-plugins/package.json
Fix a copy/paste error of export name
> 8.21.1 Fix an export name in package.json

- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-api/lib/format/setAlignment.ts
- packages/roosterjs-editor-api/test/format/setAlignmentTest.ts
- packages/roosterjs-editor-dom/lib/list/VList.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
Adapt setAlignment to support align list items
> Align list items left, center and right

- packages/roosterjs-editor-api/lib/format/insertImage.ts
Reverts microsoft/roosterjs#968 since it breaks the build
> Revert "Add optional image element attributes."

- packages/roosterjs-editor-dom/lib/contentTraverser/SelectionBlockScoper.ts
We got a lot of error report from SelectionBlockScoper, but we don't know why. So this is to add some more information to the exception to let us understand more about the bug.
> Log more info for exception from SelectionBlockScoper

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/textFeatures.ts
TRANSLATED ERROR:
undefinedat webpack:// /packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/textFeatures.ts:132
at webpack:// /packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/textFeatures.ts:66
at webpack:// /packages/roosterjs-editor-core/lib/coreApi/addUndoSnapshot.ts:42
at webpack:// /packages/roosterjs-editor-core/lib/editor/Editor.ts:608
at webpack:// /packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/textFeatures.ts:60
at webpack:// /packages/roosterjs-editor-core/lib/corePlugins/EditPlugin.ts:87
at webpack:// /packages/mail/packages/mail/view/owa-mail-compose-
> Uncaught TypeError: Cannot read properties of null (reading 'equals')

- demo/scripts/controls/sidePane/editorOptions/ContentEditFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/textFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/textFeaturesTest.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
- packages/roosterjs-editor-types/lib/interface/ContentEditFeatureSettings.ts
Automatically transform -- into hyphen, if typed between two words.
.
> Add auto hyphen textFeature

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableSelector.ts
> Table Selector is displaying incorrectly above the editors Div #1004

- README.md
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-types/lib/event/BasePluginEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginDomEvent.ts
- packages/roosterjs-editor-types/lib/event/PluginEventData.ts
- packages/roosterjs-editor-types/lib/interface/IEditor.ts
- packages/roosterjs-editor-types/lib/type/domEventHandler.ts
#1002  Add parameters for compatible PluginEventType when it is used
#1008  Fix the readme link
> Fix #1002 and #1008

- packages/roosterjs-editor-api/lib/format/toggleBullet.ts
- packages/roosterjs-editor-api/lib/format/toggleNumbering.ts
Change import to import type for toggleBullet and toggleNumbering.
>  Add type to compatible types

- demo/scripts/controls/BuildInPluginState.ts
- demo/scripts/controls/getToggleablePlugins.ts
- demo/scripts/controls/sidePane/editorOptions/ContentEditFeatures.tsx
- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/ExperimentalFeatures.tsx
- packages/roosterjs-editor-plugins/lib/AutoFormat.ts
- packages/roosterjs-editor-plugins/lib/index.ts
- packages/roosterjs-editor-plugins/lib/plugins/AutoFormat/AutoFormat.ts
- packages/roosterjs-editor-plugins/lib/plugins/AutoFormat/index.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/textFeatures.ts
- packages/roosterjs-editor-plugins/test/AutoFormat/autoFormatTest.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/textFeaturesTest.ts
- packages/roosterjs-editor-plugins/test/TestHelper.ts
- packages/roosterjs-editor-types/lib/enum/ExperimentalFeatures.ts
- packages/roosterjs-editor-types/lib/interface/ContentEditFeatureSettings.ts
Refactor the AutoHyphen into a new plugin for Auto Format
> Refactor auto hyphen experimental flight

- demo/index.html
- demo/scripts/controls/BuildInPluginState.ts
- demo/scripts/controls/MainPane.tsx
- demo/scripts/controls/MainPaneBase.tsx
- demo/scripts/controls/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controls/sidePane/editorOptions/OptionsPane.tsx
- demo/scripts/controls/sidePane/editorOptions/codes/ButtonsCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/DarkModeCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/EditorCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/ReactEditorCode.ts
- demo/scripts/controls/sidePane/editorOptions/codes/RibbonButtonCode.ts
- demo/scripts/controls/sidePane/formatState/FormatStatePane.scss
- demo/scripts/controls/sidePane/formatState/FormatStatePane.tsx
- index.html
1. Unified page title to be "RoosterJs Demo Site"
2. Remove unuseful options: showRibbon, supportDarkMode
3. Fix format state color for dark mode
4. Show more state in format pane: isInTable, isAndroid, isMobileOrTablet
5. Remove state for IE and Edge (old)
> improve demo site

- demo/scripts/controls/MainPane.tsx
- packages-ui/roosterjs-react/lib/emoji/components/EmojiIcon.tsx
- packages-ui/roosterjs-react/lib/emoji/components/EmojiPane.tsx
- packages-ui/roosterjs-react/lib/emoji/type/EmojiPaneStyles.ts
- packages-ui/roosterjs-react/lib/index.ts
When mouse over or select the emoji, change emoji box background color
> [Rooster-react] Add style for emoji in selection

- packages/roosterjs-editor-api/lib/format/setAlignment.ts
- packages/roosterjs-editor-api/test/format/setAlignmentTest.ts
List item should be proper aligned even when styled.
> Fix align list item when styled

- packages/roosterjs-editor-plugins/test/ContentEdit/features/tableFeaturesTest.ts
This PR adds Unit Tests for the ContentEdit Feature for Tables.
> Add TableFeature Tests

- packages/roosterjs-editor-api/lib/format/toggleBullet.ts
- packages/roosterjs-editor-api/lib/format/toggleNumbering.ts
- packages/roosterjs-editor-api/lib/utils/toggleListType.ts
- packages/roosterjs-editor-plugins/lib/plugins/AutoFormat/AutoFormat.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
Add different apiNames for automatic formatting.
Add parameter to disable AutoFormat.
> Auto format detection 

- package.json
> RoosterJs 8.28.0

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/utils/getAutoNumberingListStyle.ts
Ensure list will be trigger only by the right combination of characters.
> Fix numbering list triggers

- package.json
- packages/roosterjs-editor-api/lib/table/insertTable.ts
#1145 
Fix a regression from #1169 : add a null check in insertTable()
> 8.29.1 Fix #1178

- package.json
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
> Version bump 8.29.2 to 8.29.3

- .github/workflows/build-and-deploy.yml
- .github/workflows/publish.yml
Integrate #1181 into release branch
> Integrate the publish script into release branch

- package.json
- packages/roosterjs-editor-dom/lib/edit/adjustInsertPosition.ts
Hotfix Cherry picked from [4110bd77936c0bc89b858d1a169a8fefbd49ae83](https://github.com/microsoft/roosterjs/commit/4110bd77936c0bc89b858d1a169a8fefbd49ae83)
> Fix infinite loop when inserting a table and editor does not contain any element

- .github/workflows/build-and-test.yml
- .github/workflows/publish.yml
- README.md
- index.html
- package.json
- packages/roosterjs-editor-api/lib/format/getFormatState.ts
> Version bump 8.29.4 to 8.29.5

- packages/roosterjs-editor-dom/lib/list/setListItemStyle.ts
Reverts microsoft/roosterjs#1228
The change is not work as expected.
> Revert "fix：when toggle list type,list symbol style maybe incorrect"

- packages/roosterjs-editor-dom/lib/list/VListItem.ts
- packages/roosterjs-editor-dom/lib/list/setListItemStyle.ts
- packages/roosterjs-editor-dom/test/list/setListItemStyleTest.ts
Add #1228 again and fix the issue causing the list item to not change sometimes.
> Add again fix：when toggle list type,list symbol style maybe incorrect #1228

- packages/roosterjs-content-model/lib/domToModel/processors/tableProcessor.ts
- packages/roosterjs-content-model/package.json
- packages/roosterjs-content-model/test/domToModel/processors/tableProcessorTest.ts
Integrate #1226 into release branch and publish Content Model 0.0.3
> Integrate #1226 into release branch and publish Content Model 0.0.3

- packages/roosterjs-editor-plugins/test/paste/convertPasteContentFromPowerPoint.ts
- packages/roosterjs-editor-plugins/test/paste/convertSingleImageTests.ts
- packages/roosterjs-editor-plugins/test/paste/pasteTestUtils.ts
- packages/roosterjs-editor-plugins/test/paste/word/CustomDataTests.ts
> Add Unit Tests to SingleImage, PPT Paste Converters and WordCustomData

- packages/roosterjs-editor-types/lib/enum/BulletListType.ts
Fix max value for bullet list type that must be the same of the biggest value.
> Fix max value for bullet list type

- packages/roosterjs-editor-core/lib/corePlugins/CopyPastePlugin.ts
Fix CopyPaste plugin to enable strict mode of the core plugin package.
> [Enable Strict Mode Core Plugin Part 1] - Fix CopyPaste plugin to enable strict mode

- package.json
- packages/roosterjs-editor-dom/lib/utils/Browser.ts
Add https://github.com/microsoft/roosterjs/commit/cd8c6c0ebfd0abbc309630bfeb310e478d7df7de to release
> Bump Release version

- .vscode/launch.json
Add more commands to debug Unit tests in vscode
> Add debug unit test commands to launch.json file 

- packages/roosterjs-editor-core/test/coreApi/selectTableTest.ts
Skip unstable test case selectTableTest since it fails randomly.
> Skip unstable test case

- package.json
- packages-ui/roosterjs-react/lib/contextMenu/menus/createImageEditMenuProvider.tsx
- packages-ui/roosterjs-react/lib/contextMenu/types/ContextMenuItem.ts
- packages-ui/roosterjs-react/lib/contextMenu/utils/createContextMenuProvider.ts
> 8.33.1: Fix #1310

- packages/roosterjs-editor-core/lib/editor/Editor.ts
When click anywhere in the editor, change selection.
> Trigger selection when click

- packages/roosterjs-content-model/lib/formatHandlers/list/listLevelMetadataFormatHandler.ts
- packages/roosterjs-editor-dom/lib/list/setBulletListMarkers.ts
- packages/roosterjs-editor-dom/test/list/VListItemTest.ts
- packages/roosterjs-editor-dom/test/list/setBulletListMarkersTest.ts
Change arrows and square marker bullet list type.
> Change arrow and square marker

- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
Fix [173917](https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/173917)
Add a null check.
> Fix 173917

- packages/roosterjs-editor-dom/lib/list/VListChain.ts
- packages/roosterjs-editor-dom/test/list/VListChainTest.ts
When committing a list the start number of the list to ensure the list chain will be keep correct. 
Before:
After:
> fix set list chain after setnumbering

- demo/scripts/controls/contentModel/components/format/BlockFormatView.tsx
- demo/scripts/controls/contentModel/components/model/ContentModelBlockView.tsx
- demo/scripts/controls/contentModel/components/model/ContentModelHRView.scss
- demo/scripts/controls/contentModel/components/model/ContentModelHRView.tsx
- demo/scripts/controls/contentModel/components/model/ContentModelParagraphView.tsx
- packages/roosterjs-content-model/lib/domToModel/context/defaultProcessors.ts
- packages/roosterjs-content-model/lib/domToModel/context/defaultStyles.ts
- packages/roosterjs-content-model/lib/domToModel/processors/hrProcessor.ts
- packages/roosterjs-content-model/lib/index.ts
- packages/roosterjs-content-model/lib/modelApi/creators/createHR.ts
- packages/roosterjs-content-model/lib/modelToDom/context/defaultContentModelHandlers.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleBlock.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleHr.ts
- packages/roosterjs-content-model/lib/publicApi/selection/hasSelectionInBlock.ts
- packages/roosterjs-content-model/lib/publicTypes/block/ContentModelBlock.ts
- packages/roosterjs-content-model/lib/publicTypes/block/ContentModelHR.ts
- packages/roosterjs-content-model/lib/publicTypes/context/DomToModelSettings.ts
- packages/roosterjs-content-model/lib/publicTypes/context/ModelToDomSettings.ts
- packages/roosterjs-content-model/lib/publicTypes/enum/BlockType.ts
- packages/roosterjs-content-model/test/domToModel/processors/hrProcessorTest.ts
- packages/roosterjs-content-model/test/modelApi/creators/creatorsTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleBlockTest.ts
- packages/roosterjs-content-model/test/modelToDom/handlers/handleHRTest.ts
- packages/roosterjs-content-model/test/publicApi/selection/hasSelectionInBlockTest.ts
#1093 
Support HR element in Content Model
- Add data type
- Add processor and handler
- Add test case
> Support HR in content model

- packages/roosterjs-editor-plugins/lib/plugins/AutoFormat/AutoFormat.ts
When user press a key, check if the key exist before calculate the length event.
> Add check key typed check

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/AutoFormat/AutoFormat.ts
small fix: https://github.com/microsoft/roosterjs/pull/1372
> Version bump 

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/listFeatures.ts
Hot fix: https://github.com/microsoft/roosterjs/pull/1379
> [Hot fix] Add null check for list style type. 

- packages/roosterjs-content-model/lib/formatHandlers/common/sizeFormatHandler.ts
- packages/roosterjs-content-model/package.json
- packages/roosterjs-content-model/test/formatHandlers/common/sizeFormatHandlerTest.ts
Fix #1411, publish roosterjs-content-model@0.0.7
> Publish the fix to Content Model image size bug

- demo/scripts/controls/contentModel/components/model/ContentModelEntityView.tsx
- packages/roosterjs-content-model/lib/domToModel/processors/entityProcessor.ts
- packages/roosterjs-content-model/lib/modelApi/creators/createEntity.ts
- packages/roosterjs-content-model/lib/modelToDom/handlers/handleEntity.ts
- packages/roosterjs-content-model/package.json
- packages/roosterjs-content-model/test/modelApi/creators/creatorsTest.ts
Integrate #1416 to release branch, and publish Content Model 0.0.8
> Content Model: fix inline entity loses format issue (#1416), Publish Content Model 0.0.8

- demo/scripts/controls/contentModel/components/format/formatPart/WordBreakFormatRenderer.ts
- demo/scripts/controls/contentModel/components/model/ContentModelTableCellView.tsx
- package.json
- packages/roosterjs-content-model/lib/formatHandlers/common/wordBreakFormatHandler.ts
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/index.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelTableCellFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/format/FormatHandlerTypeMap.ts
- packages/roosterjs-content-model/lib/publicTypes/format/formatParts/WordBreakFormat.ts
- packages/roosterjs-content-model/package.json
- packages/roosterjs-content-model/test/formatHandlers/common/wordBreakFormatHandlerTest copy.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/markdownFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/markdownFeaturesTest.ts
Additional changes needed this week
> Bump 8.39.1

- demo/scripts/controls/sidePane/apiPlayground/region/GetSelectedRegionsPane.tsx
- packages/roosterjs-editor-api/lib/format/clearFormat.ts
- packages/roosterjs-editor-api/lib/format/setAlignment.ts
- packages/roosterjs-editor-api/lib/format/setIndentation.ts
- packages/roosterjs-editor-api/lib/utils/blockWrap.ts
- packages/roosterjs-editor-api/test/format/toggleBlockQuoteTest.ts
- packages/roosterjs-editor-core/lib/coreApi/ensureTypeInContainer.ts
- packages/roosterjs-editor-core/lib/editor/Editor.ts
- packages/roosterjs-editor-core/test/coreApi/ensureTypeInContainerTest.ts
- packages/roosterjs-editor-dom/lib/list/createVListFromRegion.ts
- packages/roosterjs-editor-dom/lib/region/getSelectedBlockElementsInRegion.ts
- packages/roosterjs-editor-dom/lib/utils/createElement.ts
- packages/roosterjs-editor-dom/test/utils/createElementTest.ts
- packages/roosterjs-editor-types/lib/enum/KnownCreateElementDataIndex.ts
Add #1469 again without the position change in ensureTypeInContainer
> Add #1469 again

- packages/roosterjs-content-model/lib/modelApi/selection/adjustWordSelection.ts
- packages/roosterjs-content-model/test/modelApi/selection/adjustWordSelectionTest.ts
Fix scenario where format was wrongly applied where the cursor was located at the end of a word
> End of word format fix

- packages/roosterjs-editor-plugins/lib/plugins/ImageEdit/ImageEdit.ts
When the focus goes out of the editor, remove image wrapper.
> Fix image edit on blur

- packages/roosterjs-content-model/lib/publicApi/block/setSpacing.ts
setSpacing public api doesn't have documentation, add some
> Add missing setSpacing comment

- packages/roosterjs-content-model/lib/modelApi/common/retrieveModelFormatState.ts
- packages/roosterjs-content-model/test/modelApi/common/retrieveModelFormatStateTest.ts
When selection contains multiple different values of a format property, return undefined for that format.
For example, when a selection contains font size 10px and 12px, since they are different value, the fontSize in result will be undefined.
> Content Model: Improve getFormatState

- packages/roosterjs-editor-api/lib/format/insertEntity.ts
Add Flight check before adding delimiters to inline readonly Entities
> Add flight check in InsertEntity

- packages/roosterjs-content-model/lib/editor/ContentModelPlugin.ts
- packages/roosterjs-content-model/package.json
- packages/roosterjs-content-model/test/editor/ContentModelPluginTest.ts
Integrate #1641 into release branch, and publish Content Model 0.3.1
> Content Model 0.3.1: Integrate #1641

- packages/roosterjs-editor-plugins/lib/plugins/Paste/Paste.ts
- packages/roosterjs-editor-plugins/lib/plugins/Paste/tsconfig.child.json
Add strict mode in Paste Plugin
> Strict mode in paste plugin

- package.json
- packages/roosterjs-editor-dom/lib/blockElements/getBlockElementAtNode.ts
- packages/roosterjs-editor-plugins/lib/plugins/ContentEdit/features/entityFeatures.ts
- packages/roosterjs-editor-plugins/test/ContentEdit/features/inlineEntityFeatureTest.ts
Bump package to patch an issue with delimiters fixed in #1725
> Bump to 8.45.1 for hotfix

- packages/roosterjs-editor-dom/lib/htmlSanitizer/getAllowedValues.ts
- packages/roosterjs-editor-types/lib/interface/HtmlSanitizerOptions.ts
As the comments mentioned, the value type should allow `null`.
> Make additionalTagReplacements allow `null` value type.

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/Paste/excelConverter/convertPastedContentFromExcel.ts
> Bump 8.45.2

- demo/scripts/controls/contentModel/components/format/SegmentFormatView.tsx
- demo/scripts/controls/contentModel/components/format/formatPart/LetterSpacingFormatRenderer.ts
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/formatHandlers/segment/letterSpacingFormatHandler.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelSegmentFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/format/FormatHandlerTypeMap.ts
- packages/roosterjs-content-model/lib/publicTypes/format/formatParts/LetterSpacingFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/index.ts
- packages/roosterjs-content-model/test/formatHandlers/segment/letterSpacingFormatHandlerTest.ts
Support "letter-spacing" CSS style in ContentModelSegmentFormat to improve content model fidelity.
> Content Model Fidelity improvement 5: Support letter-spacing style

- packages/roosterjs-editor-core/lib/coreApi/transformColor.ts
VSO 208247 https://outlookweb.visualstudio.com/Outlook%20Web/_workitems/edit/208247/?triage=true
I have no idea how this can happen, and the callstack doesn't make sense at all.
So here I just remove the function call to arrayPush(), but do iteration use our own code. At least this should be able to show a better callstack if this happens again.
> Try fix 208247 COMPONENT ERROR: Maximum call stack size exceeded

- demo/scripts/controls/contentModel/components/format/formatPart/TableLayoutFormatRenderer.ts
- demo/scripts/controls/contentModel/components/model/ContentModelTableView.tsx
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/formatHandlers/table/tableLayoutFormatHandler.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelTableFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/format/FormatHandlerTypeMap.ts
- packages/roosterjs-content-model/lib/publicTypes/format/formatParts/TableLayoutFormat.ts
- packages/roosterjs-content-model/lib/publicTypes/index.ts
- packages/roosterjs-content-model/test/formatHandlers/table/tableLayoutFormatHandlerTest.ts
When pasting a table with table layout we are not parsing the style causing the table to look different.
Adding table layout to parse and apply this style.
> Add TableLayout Format Handler

- packages/roosterjs-editor-core/lib/corePlugins/EntityPlugin.ts
- packages/roosterjs-editor-core/test/corePlugins/entityPluginTest.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/210769/?triage=true
When drag a readonly entity, we will call preventDefault() to stop this action since readonly entity should be be changed using drag and drop.
> Fix #210769

- demo/scripts/controls/contentModel/components/model/ContentModelTableCellView.tsx
- packages/roosterjs-content-model/lib/editor/plugins/PastePlugin/ContentModelPastePlugin.ts
- packages/roosterjs-content-model/lib/editor/plugins/PastePlugin/utils/deprecatedColorParser.ts
- packages/roosterjs-content-model/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model/lib/publicTypes/format/ContentModelTableCellFormat.ts
- packages/roosterjs-content-model/package.json
- packages/roosterjs-content-model/test/editor/plugins/ContentModelPastePluginTest.ts
Cherrypick couple of bugfixes:
#1897 
#1896
> Bump Content model to 0.9.1

- package.json
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
> Bump RoosterJS to 8.50.1

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/TableResize.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableEditor.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableResizer.ts
- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableSelector.ts
Reverts microsoft/roosterjs#1919 since it causes issue #1932
> Fix #1932, Revert "Fix table selector and resizer"

- packages/roosterjs-editor-plugins/lib/plugins/TableResize/editors/TableResizer.ts
The table resizer located on the bottom right corner of tables sometimes overlaps outside of them.
A method was added to hide the resizer while dragging as well as not make it visible if dragging ends outside of editing area.
> Hide Table Resizer while dragging

- README.md
This Pull Request fixes a typographical error in the README.md file.
Corrected "flexable" to "flexible" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
> remove typo flexible

- demo/scripts/controls/ribbonButtons/contentModel/tableEditButtons.ts
- packages-content-model/roosterjs-content-model-editor/lib/index.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/block/setModelAlignment.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/table/alignTable.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/table/alignTableCell.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/table/insertTableColumn.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/table/insertTableRow.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/table/mergeTableColumn.ts
- packages-content-model/roosterjs-content-model-editor/lib/modelApi/table/mergeTableRow.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicApi/table/editTable.ts
- packages-content-model/roosterjs-content-model-editor/lib/publicTypes/parameter/TableOperation.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/alignTableCellTest.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/alignTableTest.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/insertTableColumnTest.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/insertTableRowTest.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/mergeTableColumnTest.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/table/mergeTableRowTest.ts
I'm removing dependencies to enums, start from `TableOperation`
I'm adding a new string literal type to replace the const enum TableOperation.
> Standalone editor: TableOperation

- packages-content-model/roosterjs-content-model-editor/lib/publicApi/utils/formatWithContentModel.ts
- packages-content-model/roosterjs-content-model-editor/test/editor/plugins/paste/e2e/cmPasteFromExcelTest.ts
When paste an image do insert max-height.
> Remove max-height when paste image

- packages-content-model/roosterjs-content-model-editor/lib/modelApi/selection/setSelection.ts
- packages-content-model/roosterjs-content-model-editor/test/modelApi/selection/setSelectionTest.ts
https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/237217/?triage=true
When set selection under a table, need to pass start/end selection marker into sub function to make sure it got selected.
> Fix #237217

- packages/roosterjs-editor-core/lib/corePlugins/ImageSelection.ts
- packages/roosterjs-editor-core/test/corePlugins/imageSelectionTest.ts
Select images only when isClicking is true in the PluginMouseUpEvent.
> Only select image on click

- demo/scripts/controls/ContentModelEditorMainPane.tsx
- packages-content-model/roosterjs-content-model-core/lib/editor/DarkColorHandlerImpl.ts
- packages-content-model/roosterjs-content-model-core/lib/editor/createStandaloneEditorCore.ts
- packages-content-model/roosterjs-content-model-core/package.json
- packages-content-model/roosterjs-content-model-core/test/editor/DarkColorHandlerImplTest.ts
- packages-content-model/roosterjs-content-model-dom/lib/domToModel/utils/addSelectionMarker.ts
- packages-content-model/roosterjs-content-model-dom/lib/index.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelApi/common/addSegment.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelApi/common/ensureParagraph.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/processors/childProcessorTest.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/utils/addSelectionMarkerTest.ts
- packages-content-model/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- packages-content-model/roosterjs-content-model-plugins/test/edit/keyboardInputTest.ts
- packages-content-model/roosterjs-content-model-types/lib/editor/StandaloneEditorOptions.ts
- versions.json
Bump Content Model version to 0.21.1 to fix some bugs:
https://github.com/microsoft/roosterjs/pull/2239
https://github.com/microsoft/roosterjs/pull/2240
> Bump Content Model version to 0.21.1

- packages-content-model/roosterjs-content-model-core/lib/coreApi/formatContentModel.ts
- packages-content-model/roosterjs-content-model-core/test/coreApi/formatContentModelTest.ts
- versions.json
> Bump roosterjs-content-model-core to 0.21.3 to integrate #2259

- packages-content-model/roosterjs-content-model-core/lib/utils/paste/createPasteFragment.ts
- packages-content-model/roosterjs-content-model-core/test/utils/paste/createPasteFragmentTest.ts
Reverts microsoft/roosterjs#2321 since we don't need it any more
> Revert "Workaround a paste issue"

- packages-content-model/roosterjs-content-model-core/lib/editor/DOMHelperImpl.ts
- packages-content-model/roosterjs-content-model-core/test/editor/DOMHelperImplTest.ts
- packages-content-model/roosterjs-content-model-editor/lib/editor/ContentModelEditor.ts
- packages-content-model/roosterjs-content-model-types/lib/parameter/DOMHelper.ts
Add API getDomAttribute and setDomAttribute to DOMHelper.
> StandaloneEditor: Support get/setDOMAttribute

- packages-content-model/roosterjs-content-model-dom/lib/domToModel/processors/generalProcessor.ts
- packages-content-model/roosterjs-content-model-dom/lib/formatHandlers/defaultFormatHandlers.ts
- packages-content-model/roosterjs-content-model-dom/lib/modelToDom/handlers/handleGeneralModel.ts
- packages-content-model/roosterjs-content-model-dom/test/domToModel/processors/generalProcessorTest.ts
- packages-content-model/roosterjs-content-model-dom/test/modelToDom/handlers/handleBlockTest.ts
- packages-content-model/roosterjs-content-model-dom/test/modelToDom/handlers/handleGeneralModelTest.ts
- packages-content-model/roosterjs-content-model-types/lib/format/ContentModelFormatMap.ts
#2380 For general model, although we don't parse any format but just reuse all existing formats, we still need to do color transformation, especially when do initial rendering.
> Content Model: Fix #2380

- packages-content-model/roosterjs-content-model-core/lib/publicApi/model/exportContent.ts
- packages-content-model/roosterjs-content-model-core/test/publicApi/model/exportContentTest.ts
- packages/roosterjs-editor-adapter/lib/editor/EditorAdapter.ts
- versions.json
Please see #2443 for more information.
> Patch version bump: Support adding options for exportContent (#2443)

- .eslintrc.js
Add eslint rule to disallow default export, and skip old code
> Add eslint rule to disallow default export

- packages/roosterjs-content-model-plugins/lib/edit/deleteSteps/deleteList.ts
- packages/roosterjs-content-model-plugins/test/edit/deleteSteps/deleteListTest.ts
If the cursor is before the text in a list item, unlist the list item.
> Unlist after backspace

- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionState.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionsPane.tsx
- demo/scripts/controlsV2/sidePane/editorOptions/codes/AutoFormatCode.ts
- demo/scripts/controlsV2/sidePane/editorOptions/codes/PluginsCode.ts
- demo/scripts/controlsV2/sidePane/editorOptions/codes/SimplePluginCode.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/list/getListTypeStyle.ts
- versions.json
Add https://github.com/microsoft/roosterjs/pull/2549 to fix auto bullets.
> [Patch fix]: Rooster-content-model-plugins Version 9.0.1

- packages/roosterjs-content-model-dom/lib/constants/ChangeSource.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/list/keyboardListTrigger.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
We need the info that auto format list and auto format happened to trigger the AutoFormat Settings UI in OWA side, so when auto hyphen or auto list happens, trigger event.
> Trigger auto format events

- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/link/createLink.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/link/createLinkTest.ts
When a link is created using AutoFormat Plugin, trigger event using AutoLink change source.
> Trigger AutoLink

- packages/roosterjs-content-model-core/lib/command/paste/mergePasteContent.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardDelete.ts
- packages/roosterjs-content-model-plugins/lib/edit/keyboardInput.ts
- versions.json
See #2633 and #2634 for more details
> Bump version to 9.3.1: Hot fix #2633

- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-dom/lib/modelApi/editing/mergeModel.ts
- packages/roosterjs-content-model-dom/test/modelApi/editing/mergeModelTest.ts
- versions.json
Patch release with #2681 & #2684
> Patch RoosterJS to 9.4.1

- packages/roosterjs-content-model-plugins/test/watermark/WatermarkPluginTest.ts
> Fixed WatermarkPlugin test build failure

- packages/roosterjs-content-model-plugins/lib/index.ts
- packages/roosterjs-content-model-plugins/lib/paste/DefaultSanitizers.ts
Move DefaultSanitizers to public api
> Export DefaultSanitizers to be available in roosterjs-content-model-plugins package

- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/findEditingImage.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/findEditingImageTest.ts
- versions.json
Add patch fix for the bug https://github.com/microsoft/roosterjs/pull/2794
> Bump RoosterJs Plugins to 9.10.1

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
- versions.json
Add change https://github.com/microsoft/roosterjs/pull/2817.
> Patch fix RoosterJS Plugins package

- packages/roosterjs-content-model-dom/lib/modelApi/editing/mergeModel.ts
- packages/roosterjs-content-model-dom/test/modelApi/editing/mergeModelTest.ts
- packages/roosterjs-content-model-types/lib/parameter/MergeModelOption.ts
Add two new types of mergeFormat, PreferSource and PreferTarget.
> Add `preferSource` and `preferTarget` merge options to mergeModel API.

- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/Cropper/createImageCropperTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/Resizer/createImageResizerTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/Rotator/createImageRotatorTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/createImageWrapperTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/updateWrapperTest.ts
Fix unit tests for AutoFormat and ImageEdit.
> Fix test for AutoFormat and ImageEdit 

- packages/roosterjs-content-model-plugins/lib/index.ts
- packages/roosterjs-content-model-plugins/lib/watermark/isModelEmptyFast.ts
#2877 
Export isModelEmptyFast and let it accept block group
> Export isModelEmptyFast and let it accept block group

- versions.json
Bump RoosterJS Legacy Adapter to version 8.62.4.
> Bump RoosterJS Adapter

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
- versions.json
Add the fix https://github.com/microsoft/roosterjs/pull/2912
> [Hot fix] Bump RoosterJS Plugins 9.16.1

- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/ExperimentalFeatures.tsx
- demo/scripts/controlsV2/sidePane/editorOptions/Plugins.tsx
- packages/roosterjs-content-model-core/lib/coreApi/formatContentModel/formatContentModel.ts
- packages/roosterjs-content-model-core/lib/corePlugin/selection/SelectionPlugin.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-dom/lib/config/defaultContentModelFormatMap.ts
- packages/roosterjs-content-model-dom/lib/config/defaultHTMLStyleMap.ts
- packages/roosterjs-content-model-dom/lib/modelApi/editing/applyTableFormat.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/handlers/handleTable.ts
- packages/roosterjs-content-model-dom/test/endToEndTest.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/AutoFormatPlugin.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/interface/AutoFormatOptions.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/list/keyboardListTrigger.ts
- packages/roosterjs-content-model-plugins/lib/edit/inputSteps/handleEnterOnList.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/tableEdit/editors/features/CellResizer.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/AutoFormatPluginTest.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/list/keyboardListTriggerTest.ts
- packages/roosterjs-content-model-plugins/test/edit/inputSteps/handleEnterOnListTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
- packages/roosterjs-content-model-plugins/test/tableEdit/cellResizerTest.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/ContentModelTableCellFormat.ts
- packages/roosterjs-content-model-types/lib/editor/ExperimentalFeature.ts
- packages/roosterjs-content-model-types/lib/parameter/FormatContentModelContext.ts
- packages/roosterjs-editor-adapter/lib/corePlugins/BridgePlugin.ts
- packages/roosterjs-editor-adapter/test/corePlugins/BridgePluginTest.ts
- versions.json
> Version bump to 9.19.0

- packages/roosterjs-content-model-core/lib/corePlugin/cache/CachePlugin.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/CachePluginTest.ts
- packages/roosterjs-content-model-dom/lib/domToModel/processors/linkProcessor.ts
- packages/roosterjs-content-model-dom/test/domToModel/processors/linkProcessorTest.ts
- packages/roosterjs-content-model-types/lib/editor/EditorOptions.ts
- versions.json
Bump Rooster main version to 9.24.0
> Bump RoosterJS 9.24.0

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- versions.json
Patch fix `roosterjs-content-model-plugins` to version 9.24.1 to add the fix https://github.com/microsoft/roosterjs/pull/2994
> Patch fix Rooster Plugins 9.24.1

- packages/roosterjs-content-model-api/lib/publicApi/link/insertLink.ts
- packages/roosterjs-content-model-api/test/publicApi/link/insertLinkTest.ts
When the image is selected, do not replace the image with the link, add the link to image segment.
> Insert link in the image

- packages/roosterjs-content-model-core/test/overrides/listMetadataApplierTest.ts
- packages/roosterjs-content-model-dom/lib/constants/UnorderedListStyleMap.ts
- packages/roosterjs-content-model-plugins/test/paste/e2e/cmPasteFromPowerPointDesktopTest.ts
Instead of using a square character, this change updates the square style to use the 'square' style.
> Change square style 

- packages/roosterjs-content-model-api/lib/modelApi/link/promoteLink.ts
- packages/roosterjs-content-model-api/test/modelApi/link/promoteLinkTest.ts
- packages/roosterjs-content-model-plugins/lib/autoFormat/link/createLink.ts
- packages/roosterjs-content-model-plugins/test/autoFormat/link/createLinkTest.ts
When the text segment already has link, do not create the link again.
> Fix auto link

- demo/scripts/controlsV2/mainPane/MainPane.tsx
- demo/scripts/controlsV2/sidePane/editorOptions/EditorOptionsPlugin.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionState.ts
- demo/scripts/controlsV2/sidePane/editorOptions/OptionsPane.tsx
- packages/roosterjs-content-model-core/lib/corePlugin/cache/CachePlugin.ts
- packages/roosterjs-content-model-core/test/coreApi/formatContentModel/formatContentModelTest.ts
- packages/roosterjs-content-model-core/test/coreApi/restoreUndoSnapshot/restoreSnapshotHTMLTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/CachePluginTest.ts
- packages/roosterjs-content-model-core/test/corePlugin/cache/updateCacheTest.ts
- packages/roosterjs-content-model-plugins/test/paste/e2e/testUtils.ts
- packages/roosterjs-content-model-types/lib/pluginState/CachePluginState.ts
The editor option "disableCache" is not used any more. So let's graduate it.
This mostly change test code, and skip checking its value when create editor.
> Graduate option "disableCache"

- packages/roosterjs-content-model-plugins/lib/imageEdit/ImageEditPlugin.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/imageEditUtils.ts
- packages/roosterjs-content-model-plugins/lib/imageEdit/utils/updateWrapper.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/ImageEditPluginTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/imageEditUtilsTest.ts
- packages/roosterjs-content-model-plugins/test/imageEdit/utils/updateWrapperTest.ts
Before creating the image wrapper, check if the paragraph is RTL mode. 
Before:
After:
> Fix RTL for Image Selection

- packages/roosterjs-content-model-core/lib/coreApi/setContentModel/setContentModel.ts
- packages/roosterjs-content-model-core/test/coreApi/setContentModel/setContentModelTest.ts
- packages/roosterjs-content-model-dom/lib/modelToDom/handlers/handleParagraph.ts
- versions.json
Integrate #3137 into release branch and bump version to 9.35.1
> Patch to 9.35.1

- packages/roosterjs-content-model-core/lib/corePlugin/contextMenu/ContextMenuPlugin.ts
- versions.json
Include this change in release, https://github.com/microsoft/roosterjs/pull/3159
> Patch fix to 9.37.1

- packages/roosterjs-content-model-dom/lib/formatHandlers/common/roleFormatHandler.ts
- packages/roosterjs-content-model-dom/lib/formatHandlers/defaultFormatHandlers.ts
- packages/roosterjs-content-model-dom/test/formatHandlers/block/displayFormatHandlerTest.ts
- packages/roosterjs-content-model-dom/test/formatHandlers/common/roleFormatHandlerTest.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/ContentModelTableFormat.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/FormatHandlerTypeMap.ts
- packages/roosterjs-content-model-types/lib/contentModel/format/formatParts/RoleFormat.ts
- packages/roosterjs-content-model-types/lib/index.ts
Add a format handler for the Aria "role" attribute, which describes elements for use by accessibility tools.
> Add role format handler
